.\" Manpage for am_i_online
.TH man 1 "14 July 2022" "202207181340-git" "am_i_online"

.SH NAME
am_i_online

.SH DESCRIPTION
Check for internet connection

.SH SYNOPSIS
am_i_online [options]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting
.TP
.B \-\-force
Force internet exists as true 
.TP
.B \-\-error
Only show message if no internet
.TP
.B \-\-console                
Show output messages
.TP
.B \-\-message                
Set custom message
.TP
.B \-\-site                   
Specify site
.TP
.B \-\-code                   
Custom http status code
.TP
.B \-\-loop                   
Keeps running on a 10 second loop

.SH EXAMPLES
.TP
.B am_i_online \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/am_i_online/settings.conf
.TP
.I
/usr/local/bin/am_i_online

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.com>
