.\" Manpage for am_i_online
.TH man 1 "02 February 2026" "202602020740-git" "am_i_online"

.SH NAME
am_i_online

.SH DESCRIPTION
Check for internet connection

.SH SYNOPSIS
am_i_online [options]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting
.TP
.B \-\-force          
force true
.TP
.B \-\-error    
show only errors
.TP
.B \-\-console  
show output messages
.TP
.B \-\-message  
set custom message
.TP
.B \-\-site     
specify site
.TP
.B \-\-code     
custom http status code
.TP
.B \-\-loop     
keeps running on a 10 second loop


.SH EXAMPLES
.TP
.B am_i_online \-\-code 200 \-\-site google.com \-\-message 'Test conection to google'

.SH EXIT CODES
.TP
0 connected
.TP
1 not connected
.TP
3 missing program

.SH FILES
.TP
.I
~/.config/myscripts/am_i_online/settings.conf
.TP
.I
/usr/local/bin/am_i_online

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
