.\" Manpage for anime-dl
.TH man 1 "14 July 2022" "202602020740-git" "anime-dl"

.SH NAME
anime-dl

.SH DESCRIPTION
Search for anime to download or watch

.SH SYNOPSIS
anime-dl [options] [query]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting.
.TP
.B \-v
use VLC as the media player.
.TP
.B \-s
watch anime together with friends, using Syncplay (mpv only).
.TP
.B \-d
download episode.
.TP
.B \-c
continue watching anime from history.
.TP
.B \-f
use fzf for anime selection.
.TP
.B \-q
set video quality (best|worst|360|480|720|1080).
.TP
.B \-a
specify episode to watch.
.TP
.B \-p
download episode to specified directory.
.TP
.B \-r
select provider to scrape first [1-7].

.SH EXAMPLES
.TP
.B anime-dl \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/anime-dl/settings.conf
.TP
.I
/usr/local/bin/anime-dl

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
