.\" Manpage for anonymize
.TH man 1 "14 July 2022" "202602020740-git" "anonymize"

.SH NAME
anonymize

.SH DESCRIPTION
 Anonymous web access

.SH SYNOPSIS
anonymize [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting
.TP
.B \-\-freenet
Launch freenet browser
.TP
.B \-\-tor
Launch tor browser
.TP
.B \-\-i2p 
Launch i2p browser
.TP
.B \-\-download 
Re-download installers for i2p/freenet
.TP
.B \-\-console
Output to console
.TP
.B proxy
Set proxy [port] [name] [link] :
proxy 9080 tor https://check.torproject.org

.SH EXAMPLES
.TP
.B anonymize \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/anonymize/settings.conf
.TP
.I
/usr/local/bin/anonymize

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
