.\" Manpage for append_path
.TH man 1 "14 July 2022" "202602020740-git" "append_path"

.SH NAME
append_path

.SH DESCRIPTION
Append a folder to the system/user PATH

.SH SYNOPSIS
append_path [options] /path/to/file OR /path/to/dir

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B append_path /path/do/dir

.SH FILES
.TP
.I
~/.config/myscripts/append_path/settings.conf
.TP
.I
/usr/local/bin/append_path

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
