.\" Manpage for ask_yes_no_question
.TH man 1 "14 July 2022" "202207211058-git" "ask_yes_no_question"

.SH NAME
ask_yes_no_question

.SH DESCRIPTION
ask user a question and execute command

.SH SYNOPSIS
ask_yes_no_question [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B ask_yes_no_question "Update available\nDo you want to update?" "sudo apt upgrade -yy"

.SH FILES
.TP
.I
~/.config/myscripts/ask_yes_no_question/settings.conf
.TP
.I
/usr/local/bin/ask_yes_no_question

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
