.\" Manpage for auto_tail
.TH man 1 "14 July 2022" "202602020740-git" "auto_tail"

.SH NAME
auto_tail

.SH DESCRIPTION


.SH SYNOPSIS
auto_tail [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B auto_tail \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/auto_tail/settings.conf
.TP
.I
/usr/local/bin/auto_tail

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
