.\" Manpage for automate
.TH man 1 "14 July 2022" "202207211059-git" "automate"

.SH NAME
automate

.SH DESCRIPTION
 Script to control roku and hue devices

.SH SYNOPSIS
automate [options] [command]
play stop pause toggle state.
.SH OPTIONS
.TP 
.B play
Start video and turn off hue lights.
.TP 
.B stop 
Stop video and turn on hue lights.
.TP 
.B pause
Start/Stop video and turn off/on hue lights depending on state.
.TP 
.B toggle
Start/Stop video and turn off/on hue lights depending on state.
.TP 
.B state [json/text]
Get data back with [json] or [text].
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B automate \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/automate/settings.conf
.TP
.I
/usr/local/bin/automate

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
