.\" Manpage for auto_tail
.TH man 1 "04 May 2026" "202605041300-git" "auto_tail"

.SH NAME
auto_tail \- Dynamic log monitor that auto-tails files and adapts to new additions

.SH DESCRIPTION
Monitors one or more directories (up to 5 levels deep) and tails all files found within them.
Automatically restarts the tail process when new files appear. Defaults to ~/.local/log when
no directories are given.

.SH SYNOPSIS
auto_tail [options] [dir1] [dir2] ...

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir [path]
Add a directory to monitor.
.TP
.B \-\-lines [N]
Show last N lines of each file on start (default: 10).
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting.

.SH EXAMPLES
.TP
.B auto_tail \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/auto_tail/settings.conf
.TP
.I
/usr/local/bin/auto_tail

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
