.\" Manpage for backupapp
.TH man 1 "07 May 2026" "202605071853-git" "backupapp"

.SH NAME
backupapp

.SH DESCRIPTION
 Backup files and folders

.SH SYNOPSIS
backupapp [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-term
Start in a new terminal window
.TP
.B \-\-console
Open the interactive menu
.TP
.B \-\-once
Run without saving a project config
.TP
.B \-\-yes, \-\-auto
Non-interactive (auto-confirm; cron-safe)
.TP
.B \-\-cron <add|del|list|all>
Schedule, remove, list, or run all cron-driven backups
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH COMMANDS
.TP
.B [new|run] <name> <dir>
Run or create a backup
.TP
.B create <name> <dir>
Create a saved project config without running a backup
.TP
.B cron all|list|add|del
Manage cron-driven backups

.SH EXAMPLES
.TP
.B backupapp \-\-help
backupapp [name] [/path/to/dirs /path/to/files]
.TP
.B backupapp Documents ~/Documents
Run a backup of ~/Documents (saves a config on first run)
.TP
.B backupapp cron add Documents ~/Documents "0 2 * * *"
Schedule the Documents backup to run nightly at 02:00
.TP
.B backupapp cron list
List currently scheduled backupapp cron jobs

.SH FILES
.TP
.I
~/.config/myscripts/backupapp/settings.conf
.TP
.I
/usr/local/bin/backupapp

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
