.\" Manpage for cheat.sh
.TH man 1 "14 July 2022" "202207211101-git" "cheat.sh"

.SH NAME
cheat.sh

.SH DESCRIPTION
 Get help with commands

.SH SYNOPSIS
cheat.sh [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B cheat.sh \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/cheat.sh/settings.conf
.TP
.I
/usr/local/bin/cheat.sh

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
