.\" Manpage for clean-system
.TH man 1 "07 May 2026" "202605071902-git" "clean-system"

.SH NAME
clean-system

.SH DESCRIPTION
 remove old logs

.SH SYNOPSIS
clean-system [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-silent
Suppress non-error output
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH DESCRIPTION
With no arguments, runs logrotate (system-wide and the optional
$HOME/.config/logrotate/config), removes rotated/archived logs in
/var/log older than 7 days (matching *.gz, *.old, *.<digits>, and
year-stamped names), purges /var/spool/uptimed and
/var/lib/downtimed/downtimedb (briefly stopping and restarting the
respective services), and prunes per-user $HOME/.local/tmp (>1 day) and
$HOME/.local/log (>7 days).

.SH EXAMPLES
.TP
.B clean-system \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/clean-system/settings.conf
.TP
.I
/usr/local/bin/clean-system

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
