.\" Manpage for cloudflare
.TH man 1 "14 July 2022" "202207211103-git" "cloudflare"

.SH NAME
cloudflare

.SH DESCRIPTION
 cloudflare api script

.SH SYNOPSIS
cloudflare [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B cloudflare \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/cloudflare/settings.conf
.TP
.I
/usr/local/bin/cloudflare

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
