.\" Manpage for cmd_exists
.TH man 1 "14 July 2022" "202602020740-git" "cmd_exists"

.SH NAME
cmd_exists

.SH DESCRIPTION
 Check to see if command exists

.SH SYNOPSIS
cmd_exists [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B cmd_exists \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/cmd_exists/settings.conf
.TP
.I
/usr/local/bin/cmd_exists

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
