.\" Manpage for config
.TH man 1 "02 February 2026" "202602020740-git" "config"

.SH NAME
config

.SH DESCRIPTION
 Add dotfiles/config files to a git repo

.SH SYNOPSIS
config [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B config \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/config/settings.conf
.TP
.I
/usr/local/bin/config

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
