.\" Manpage for covid19
.TH man 1 "14 July 2022" "202602020740-git" "covid19"

.SH NAME
covid19

.SH DESCRIPTION
 script to track the covid-19 outbreak

.SH SYNOPSIS
covid19 [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B covid19 \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/covid19/settings.conf
.TP
.I
/usr/local/bin/covid19

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
