.\" Manpage for gen-gitattr
.TH man 1 "14 July 2022" "202602020740-git" "gen-gitattr"

.SH NAME
gen-gitattr

.SH DESCRIPTION


.SH SYNOPSIS
gen-gitattr [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B gen-gitattr \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/gen-gitattr/settings.conf
.TP
.I
/usr/local/bin/gen-gitattr

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
