.\" Manpage for get_city_id
.TH man 1 "08 April 2023" "202304081323-git" "get_city_id"

.SH NAME
get_city_id

.SH DESCRIPTION
find id of city

.SH SYNOPSIS
get_city_id [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B get_city_id \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/get_city_id/settings.conf
.TP
.I
/usr/local/bin/get_city_id

.SH TODO
Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
