.TH MULTIMEDIA "1" "December 2025" "multimedia 202208131711-git" "User Commands"
.SH NAME
multimedia \- Interactive multimedia application launcher menu
.SH SYNOPSIS
.B multimedia
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
.B multimedia
is an interactive menu-driven script for launching multimedia applications. It provides a convenient interface to access various media players, editors, and related tools installed on the system.
.PP
When launched, multimedia presents a menu of available multimedia applications, allowing users to quickly select and launch their preferred media tools without remembering individual command names.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B multimedia
Launch the multimedia application menu
.SH FILES
.TP
.B ~/.config/myscripts/multimedia/settings.conf
User configuration file for multimedia preferences
.TP
.B ~/.local/log/multimedia/
Log file directory for error tracking
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Opens in a terminal if not already running in one
.IP \(bu 2
Menu options depend on installed applications
.IP \(bu 2
Uses rofi or dmenu for the menu interface when available
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR music (1),
.BR mpdclient (1),
.BR rofi (1)
