.TH MYIP "1" "December 2025" "myip 202208131959-git" "User Commands"
.SH NAME
myip \- Display local and public IP addresses
.SH SYNOPSIS
.B myip
[\fI\,OPTIONS\/\fR] [\fI\,COMMAND\/\fR] [\fI\,VERSION\/\fR]
.SH DESCRIPTION
.B myip
is a utility script for displaying IP address information. It can show both local (LAN) and public (WAN) IP addresses, supporting both IPv4 and IPv6 protocols.
.PP
The script can also retrieve geolocation and other information about IP addresses using external APIs.
.SH COMMANDS
.TP
.B local [4|6]
Show local IP address. Specify 4 for IPv4 or 6 for IPv6
.TP
.B public [4|6]
Show public IP address. Specify 4 for IPv4 or 6 for IPv6
.TP
.B 4
Show both local and public IPv4 addresses
.TP
.B 6
Show both local and public IPv6 addresses
.TP
.B info
Show detailed information about your IP address including geolocation
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available commands
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B myip
Show all IP addresses (local and public, IPv4 and IPv6)
.TP
.B myip local 4
Show local IPv4 address only
.TP
.B myip public 6
Show public IPv6 address only
.TP
.B myip info
Display detailed IP information and geolocation
.SH FILES
.TP
.B ~/.config/myscripts/myip/settings.conf
User configuration file for myip preferences
.TP
.B ~/.local/log/myip/
Log file directory for error tracking
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 4
Network connectivity issue
.SH NOTES
.IP \(bu 2
Requires internet connection for public IP detection
.IP \(bu 2
Uses external services like ifconfig.me or ipinfo.io
.IP \(bu 2
IPv6 detection requires IPv6 connectivity
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR ip (8),
.BR ifconfig (8),
.BR curl (1)
