.TH MYPS "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
myps \- Display user process information
.SH SYNOPSIS
.B myps
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
.B myps
is a utility script for displaying information about the current user's running processes. It provides a simplified view of processes owned by the current user.
.PP
The script wraps the standard ps command with convenient defaults for showing user-relevant process information.
.SH OPTIONS
.TP
.BR \-\-dir " " \fI\,DIRECTORY\/\fR
Set the working directory
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B myps
Display current user's processes
.SH FILES
.TP
.B ~/.config/myscripts/myps/settings.conf
User configuration file for myps preferences
.TP
.B ~/.local/log/myps/
Log file directory for error tracking
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Shows only processes owned by the current user
.IP \(bu 2
Wraps the standard ps command
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR ps (1),
.BR top (1),
.BR htop (1)
