.TH MYVMMANAGER "1" "December 2025" "myvmmanager 202208141321-git" "User Commands"
.SH NAME
myvmmanager \- Virtual machine manager launcher
.SH SYNOPSIS
.B myvmmanager
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
.B myvmmanager
is a launcher script for virtual machine management tools. It detects and launches available virtualization management applications like virt-manager, VirtualBox, or VMware.
.PP
The script provides a unified interface for accessing VM management tools regardless of which virtualization platform is installed.
.SH OPTIONS
.TP
.BR \-\-dir " " \fI\,DIRECTORY\/\fR
Set the working directory
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B myvmmanager
Launch the virtual machine manager
.SH FILES
.TP
.B ~/.config/myscripts/myvmmanager/settings.conf
User configuration file for myvmmanager preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
No VM manager found
.SH NOTES
.IP \(bu 2
Supports virt-manager, VirtualBox, VMware
.IP \(bu 2
Detects available virtualization platforms
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR virt-manager (1),
.BR VirtualBox (1),
.BR virsh (1)
