.TH NOTIFY-DAEMON "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
notify-daemon \- Manage notification daemon services
.SH SYNOPSIS
.B notify-daemon
[\fI\,OPTIONS\/\fR] [\fI\,COMMAND\/\fR]
.SH DESCRIPTION
.B notify-daemon
is a script for managing notification daemon services on Linux systems. It provides commands to start, stop, restart, and configure various notification daemons including dunst, xfce4-notifyd, and deadd.
.PP
The script can also switch between different notification daemons and check their status.
.SH COMMANDS
.TP
.B start
Start the notification daemon
.TP
.B stop
Stop the notification daemon
.TP
.B restart
Restart the notification daemon
.TP
.B status
Check the daemon status
.TP
.B enable
Enable autostart for the notification daemon
.TP
.B disable
Disable autostart
.TP
.B show
Show notifications
.TP
.B ask
Check if notification client is available
.TP
.B client
Launch notification client configuration
.TP
.B dunst
Use dunst as the notification daemon
.TP
.B xfce4
Use xfce4-notifyd as the notification daemon
.TP
.B deadd
Use deadd notification center
.TP
.B server start|stop|restart
Control the notification server
.SH OPTIONS
.TP
.BR \-\-term
Run in a terminal window
.TP
.BR \-\-ask
Check for notification client
.TP
.BR \-\-help
Display help message with usage information and available commands
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B notify-daemon start
Start the notification daemon
.TP
.B notify-daemon status
Check if daemon is running
.TP
.B notify-daemon dunst
Switch to dunst notification daemon
.TP
.B notify-daemon server restart
Restart the notification server
.SH FILES
.TP
.B ~/.config/myscripts/notify-daemon/settings.conf
User configuration file for notify-daemon preferences
.TP
.B ~/.config/dunst/dunstrc
Dunst configuration file
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
No notification daemon found
.SH NOTES
.IP \(bu 2
Supports multiple notification daemons
.IP \(bu 2
Can run as autostart service
.IP \(bu 2
Integrates with various desktop environments
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR dunst (1),
.BR notify-send (1),
.BR notifications (1)
