.TH NOTIFICATIONS "1" "December 2025" "notifications 202208141433-git" "User Commands"
.SH NAME
notifications \- Send desktop notifications to users
.SH SYNOPSIS
.B notifications
[\fI\,OPTIONS\/\fR] [\fI\,TITLE\/\fR] [\fI\,MESSAGE\/\fR]
.SH DESCRIPTION
.B notifications
is a script for sending desktop notifications to users. It provides a unified interface for sending notifications that works across different notification daemons and systems.
.PP
The script can send notifications to the current user or broadcast to all logged-in users.
.SH COMMANDS
.TP
.B \fI\,TITLE\/\fR \fI\,MESSAGE\/\fR
Send a notification with the specified title and message
.SH OPTIONS
.TP
.BR \-\-all " " \fI\,TITLE\/\fR " " \fI\,MESSAGE\/\fR
Send a notification to all logged-in users
.TP
.BR \-\-ask " " \fI\,TITLE\/\fR " " \fI\,MESSAGE\/\fR
Check if a notification client is installed before sending
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B notifications "Hello" "This is a test message"
Send a notification with title and message
.TP
.B notifications --all "Alert" "System maintenance in 5 minutes"
Send notification to all users
.SH FILES
.TP
.B ~/.config/myscripts/notifications/settings.conf
User configuration file for notifications preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
No notification daemon available
.SH NOTES
.IP \(bu 2
Uses notify-send, dunstify, or other notification tools
.IP \(bu 2
Supports various notification daemons (dunst, xfce4-notifyd, etc.)
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR notify-send (1),
.BR notify-daemon (1),
.BR dunst (1)
