.\" Manpage for port_test
.TH man 1 "14 October 2025" "202208141906-git" "port_test"

.SH NAME
port_test \- test if a network port is in use

.SH DESCRIPTION
A utility to test if a network port is currently in use on the system. Can also generate random available port numbers.

.SH SYNOPSIS
port_test [options] [command] [port] [name]

.SH COMMANDS
.TP
.B random
Generate and return a random available port number
.TP
.B <port>
Test if specified port is in use (default behavior)

.SH OPTIONS
.TP
.B --help
Display help message
.TP
.B --version
Show script version
.TP
.B --config
Generate user configuration file
.TP
.B --options
Show all available options
.TP
.B --debug
Enable debugging output
.TP
.B --raw
Remove formatting from output
.TP
.B --silent
Suppress output messages

.SH EXAMPLES
.TP
.B port_test 80
Test if port 80 is in use
.TP
.B port_test 8080
Test if port 8080 is in use
.TP
.B port_test random
Get a random available port number
.TP
.B port_test 3000 myapp
Test port 3000 for myapp

.SH EXIT STATUS
.TP
.B 0
Port is available (not in use)
.TP
.B 1
Port is in use
.TP
.B 2
Error occurred during testing

.SH FILES
.TP
.I ~/.config/myscripts/port_test/settings.conf
User configuration file

.SH NOTES
port_test checks port availability using system tools like netstat or ss.

The random command generates port numbers in the ephemeral port range and verifies they are not in use.

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/scripts/issues

.SH SEE ALSO
netstatg(1), netstatl(1), netstat(8), ss(8), lsof(8)

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
