.TH POSTIT "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
postit \- Create and update blog posts from terminal using GitHub
.SH SYNOPSIS
.B postit
[\fI\,OPTIONS\/\fR] [\fI\,COMMAND\/\fR] [\fI\,ARGUMENTS\/\fR]
.SH DESCRIPTION
.B postit
is a script for creating and updating blog posts directly from the terminal. It uses GitHub as the backend for storing and publishing posts, making it easy to manage static site content.
.PP
The script provides commands for creating new posts, editing existing ones, and managing post metadata.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B postit new "My Blog Post"
Create a new blog post with the given title
.TP
.B postit edit "post-name"
Edit an existing blog post
.TP
.B postit list
List all existing posts
.SH FILES
.TP
.B ~/.config/myscripts/postit/settings.conf
User configuration file for postit preferences
.SH ENVIRONMENT
.TP
.B GITHUB_TOKEN
GitHub personal access token for repository access
.TP
.B POSTIT_REPO
GitHub repository for blog posts
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
Required command (git, gh) not found
.SH NOTES
.IP \(bu 2
Uses GitHub as backend storage
.IP \(bu 2
Supports markdown format for posts
.IP \(bu 2
Integrates with static site generators
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR gh (1),
.BR git (1),
.BR readme-2-post (1)
