.TH POST2SOCIAL "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
post2social \- Post to mastodon and twitter
.SH SYNOPSIS
.B post2social
[\fI\,OPTIONS\/\fR] [\fI\,MESSAGE\/\fR]
.SH DESCRIPTION
.B post2social
is a script for posting messages to social media platforms. It supports posting to Mastodon and Twitter simultaneously, providing a unified interface for social media updates.
.PP
The script can post text messages and optionally include media attachments to multiple platforms at once.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B post2social "Hello world!"
Post a message to all configured social platforms
.TP
.B post2social --config
Set up API credentials for social platforms
.SH FILES
.TP
.B ~/.config/myscripts/post2social/settings.conf
User configuration file for post2social preferences and API credentials
.SH ENVIRONMENT
.TP
.B MASTODON_TOKEN
Mastodon API access token
.TP
.B TWITTER_API_KEY
Twitter API key for authentication
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
Required API credentials not found
.SH NOTES
.IP \(bu 2
Requires API credentials for each platform
.IP \(bu 2
Supports Mastodon and Twitter
.IP \(bu 2
Messages are posted simultaneously to all configured platforms
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR toot (1),
.BR twurl (1),
.BR social (1)
