.TH RADIOREFERENCE "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
radioreference \- Play RadioReference/Broadcastify streams
.SH SYNOPSIS
.B radioreference
[\fI\,OPTIONS\/\fR] [\fI\,STREAM_ID\/\fR]
.SH DESCRIPTION
.B radioreference
is a script for playing live audio streams from RadioReference and Broadcastify. It provides access to police, fire, EMS, and other public safety radio communications.
.PP
The script allows streaming scanner feeds directly from the command line using various media players.
.SH OPTIONS
.TP
.BR \-\-term
Open in a terminal window
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B radioreference
Launch interactive stream selection
.TP
.B radioreference 12345
Play stream with specified ID
.SH FILES
.TP
.B ~/.config/myscripts/radioreference/settings.conf
User configuration file for radioreference preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
Required command (media player) not found
.TP
.B 4
Network connection failed
.SH NOTES
.IP \(bu 2
Streams public safety radio communications
.IP \(bu 2
Requires internet connection
.IP \(bu 2
Works with mpv, vlc, or mplayer
.SH DEPENDENCIES
.TP
.B Required:
.RS
.IP \(bu 2
mpv, vlc, or mplayer - For stream playback
.IP \(bu 2
curl - For stream fetching
.RE
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR mpv (1),
.BR vlc (1),
.BR mplayer (1)
