.TH RANDOM-STRING "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
random-string \- Generate random strings
.SH SYNOPSIS
.B random-string
[\fI\,OPTIONS\/\fR] [\fI\,LENGTH\/\fR]
.SH DESCRIPTION
.B random-string
is a script for generating random strings of specified length. It can be used for creating passwords, tokens, identifiers, and other random character sequences.
.PP
The script supports various character sets and output formats for different use cases.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B random-string
Generate a random string with default length
.TP
.B random-string 32
Generate a 32-character random string
.TP
.B random-string 16 | xclip
Generate and copy to clipboard
.SH FILES
.TP
.B ~/.config/myscripts/random-string/settings.conf
User configuration file for random-string preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Uses /dev/urandom for randomness
.IP \(bu 2
Supports alphanumeric and special characters
.IP \(bu 2
Useful for password generation
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR pwgen (1),
.BR openssl (1),
.BR uuidgen (1)
