.TH README-2-POST "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
readme-2-post \- Create a markdown file from a README file
.SH SYNOPSIS
.B readme-2-post
[\fI\,OPTIONS\/\fR] [\fI\,README_FILE\/\fR] [\fI\,OUTPUT_FILE\/\fR]
.SH DESCRIPTION
.B readme-2-post
is a script for converting README files into blog post format. It transforms GitHub-style README files into markdown suitable for static site generators like Jekyll or Hugo.
.PP
The script can add front matter, adjust formatting, and prepare content for publication.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B readme-2-post README.md post.md
Convert README.md to post.md
.TP
.B readme-2-post ./README.md
Convert and output to stdout
.SH FILES
.TP
.B ~/.config/myscripts/readme-2-post/settings.conf
User configuration file for readme-2-post preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 2
Input file not found
.SH NOTES
.IP \(bu 2
Adds YAML front matter for blog posts
.IP \(bu 2
Adjusts relative links and images
.IP \(bu 2
Works with Jekyll, Hugo, and other generators
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR postit (1),
.BR pandoc (1),
.BR jekyll (1)
