.TH RMD "1" "December 2025" "rmd 202509191545-git" "User Commands"
.SH NAME
rmd \- Remove files and directories recursively
.SH SYNOPSIS
.B rmd
[\fI\,OPTIONS\/\fR] [\fI\,FILE\/\fR]...
.SH DESCRIPTION
.B rmd
is a script for safely removing files and directories recursively. It includes safety checks to prevent accidental deletion of critical system files and directories.
.PP
The script protects against common mistakes like wildcard deletions at root level.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B rmd directory/
Remove a directory and its contents
.TP
.B rmd file1 file2
Remove multiple files
.SH FILES
.TP
.B ~/.config/myscripts/rmd/settings.conf
User configuration file for rmd preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 2
Dangerous operation prevented
.SH NOTES
.IP \(bu 2
Includes safety checks to prevent catastrophic deletions
.IP \(bu 2
Prevents wildcard deletions at root level
.IP \(bu 2
Wrapper around rm with additional protections
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR rm (1),
.BR rmdir (1),
.BR trash-cli (1)
