.TH ROKU "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
roku \- Home automation Roku control script
.SH SYNOPSIS
.B roku
[\fI\,OPTIONS\/\fR] [\fI\,COMMAND\/\fR] [\fI\,ARGUMENTS\/\fR]
.SH DESCRIPTION
.B roku
is a script for controlling Roku devices via their External Control Protocol (ECP) API. It provides command-line control over Roku streaming devices on your local network.
.PP
The script can send remote control commands, launch apps, and query device information.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH COMMANDS
.TP
.B up, down, left, right
Navigation keys
.TP
.B select, back, home
Action keys
.TP
.B play, pause
Playback control
.TP
.B volumeup, volumedown, mute
Volume control
.TP
.B power
Power toggle
.SH EXAMPLES
.TP
.B roku home
Navigate to home screen
.TP
.B roku play
Start/resume playback
.TP
.B roku volumeup
Increase volume
.SH FILES
.TP
.B ~/.config/myscripts/roku/settings.conf
User configuration file for roku preferences and device IP
.SH ENVIRONMENT
.TP
.B ROKU_IP
IP address of the Roku device
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 4
Network connection failed
.SH NOTES
.IP \(bu 2
Uses Roku's External Control Protocol (ECP)
.IP \(bu 2
Requires Roku device on local network
.IP \(bu 2
Device must have ECP enabled
.SH DEPENDENCIES
.TP
.B Required:
.RS
.IP \(bu 2
curl - For API requests
.RE
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR curl (1)
