.TH RUN_COMMAND "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
run_command \- Wrapper script for running commands in the background
.SH SYNOPSIS
.B run_command
[\fI\,OPTIONS\/\fR] [\fI\,COMMAND\/\fR] [\fI\,ARGUMENTS\/\fR]
.SH DESCRIPTION
.B run_command
is a wrapper script for executing commands in the background. It handles output redirection, logging, and process management for background tasks.
.PP
The script provides a consistent interface for launching and managing background processes.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B run_command myapp --daemon
Run myapp in background
.TP
.B run_command --log /var/log/app.log myapp
Run with logging
.SH FILES
.TP
.B ~/.config/myscripts/run_command/settings.conf
User configuration file for run_command preferences
.TP
.B ~/.local/log/run_command/
Log files for background processes
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
Command not found
.SH NOTES
.IP \(bu 2
Redirects output to log files
.IP \(bu 2
Detaches process from terminal
.IP \(bu 2
Handles signals appropriately
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR nohup (1),
.BR screen (1),
.BR tmux (1)
