.\" Manpage for screenshot-menu
.TH man 1 "10 September 2025" "202509092137-git" "screenshot-menu"

.SH NAME
screenshot-menu

.SH DESCRIPTION
Interactive screenshot utility with multiple capture modes and save destinations.

.SH SYNOPSIS
screenshot-menu [options]

.SH SCREENSHOT TYPES
.TP
.B Fullscreen
Capture entire screen
.TP
.B Active window
Capture active window
.TP
.B Selected region
Select area to capture
.TP
.B Monitor selection
Capture specific monitor

.SH SAVE DESTINATIONS
.TP
.B File
Save to disk
.TP
.B Clipboard
Copy to clipboard
.TP
.B Both
Save to file and clipboard

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting
.TP
.B \-\-silent
Silent mode operation
.TP
.B \-\-dir <path>
Set save directory

.SH EXAMPLES
.TP
.B screenshot-menu
Launch interactive menu
.TP
.B screenshot-menu \-\-dir ~/Pictures
Set custom save directory

.SH FILES
.TP
.I
~/.config/myscripts/screenshot-menu/settings.conf
.TP
.I
/usr/local/bin/screenshot-menu

.SH DEPENDENCIES
maim, xrandr, xdotool, xclip (for clipboard), rofi or dmenu

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>