.\" Manpage for search-menu
.TH man 1 "11 September 2025" "202208161737-git" "search-menu"

.SH NAME
search-menu \- Interactive search engine interface with dmenu/rofi

.SH DESCRIPTION
A configurable search engine interface that provides organized access to various search engines through an interactive dmenu/rofi menu. Features categorized search providers, search history, and direct search capabilities.

.SH SYNOPSIS
search-menu [options] [category|command] [arguments...]

.SH COMMANDS
.TP
.B Interactive Mode (no arguments)
Opens dmenu/rofi interface for engine selection and search input
.TP
.B list [category]
List available search engines for all categories or specific category
.TP
.B search <engine> <query>
Perform direct search without interactive menu

.SH CATEGORIES
.TP
.B development
Development tools and code repositories
.br
GitHub, GitLab, StackOverflow, SourceForge, Google Open Source
.TP
.B engines
General search engines
.br
Scour.li (default), Google, DuckDuckGo, Brave, Bing, Startpage, SearX
.TP
.B news
News sources and reference materials
.br
Google News, Wikipedia, Wiktionary, Hacker News, CNN, BBC, Reuters
.TP
.B media
Video and social media platforms
.br
YouTube, Reddit, Odysee
.TP
.B os
Operating system documentation
.br
Arch Wiki, Alpine Linux Wiki
.TP
.B packages
Package managers and software repositories
.br
Alpine packages, Arch packages, pkgs.org
.TP
.B tech
Technical documentation and package registries
.br
DevDocs, MDN, Docker Hub, npm, PyPI, Crates.io, Go packages
.TP
.B security
Security research and vulnerability databases
.br
CVE/NVD, Exploit-DB, Shodan, VirusTotal, CVE Details

.SH OPTIONS
.TP
.B \-\-providers
Show all available search providers and engines
.TP
.B \-\-help
Display help message
.TP
.B \-\-version
Display current version
.TP
.B \-\-config
Generate configuration file
.TP
.B \-\-options
Show all available options
.TP
.B \-\-debug
Enable debugging output
.TP
.B \-\-raw
Remove all formatting from output
.TP
.B \-\-silent
Suppress non-error output

.SH EXAMPLES
.TP
.B search-menu
Open interactive search menu
.TP
.B search-menu development
Open development-focused search engines
.TP
.B search-menu search google "bash scripting"
Search Google directly for "bash scripting"
.TP
.B search-menu list tech
List all technical documentation search engines
.TP
.B search-menu engines
Show general search engines menu
.TP
.B search-menu security
Access security research databases

.SH FILES
.TP
.I
~/.config/myscripts/search-menu/settings.conf
.TP
.I
/usr/local/bin/search-menu

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
