.\" Manpage for send-notify
.TH man 1 "14 October 2025" "202602020740-git" "send-notify"

.SH NAME
send-notify \- wrapper for notify-send to send desktop notifications

.SH DESCRIPTION
A wrapper script for notify-send that provides enhanced notification functionality including sending notifications to all users and checking for notification client availability.

.SH SYNOPSIS
send-notify [options] [title] [message]

.SH BASIC USAGE
.TP
.B send-notify <title> <message>
Send a desktop notification with title and message
.TP
.B send-notify --all <title> <message>
Send notification to all logged-in users
.TP
.B send-notify --ask
Check if a notification client is installed and available

.SH OPTIONS
.TP
.B --all
Send notification to all logged-in users
.TP
.B --ask
Check if notification client is available
.TP
.B --help
Display help message
.TP
.B --version
Show script version
.TP
.B --config
Generate user configuration file
.TP
.B --options
Show all available options
.TP
.B --debug
Enable debugging output
.TP
.B --raw
Remove formatting from output

.SH EXAMPLES
.TP
.B send-notify "Build Complete" "Your project has finished building"
Send a simple notification
.TP
.B send-notify --all "System Update" "System will reboot in 5 minutes"
Send notification to all users
.TP
.B send-notify --ask
Check if notification system is available
.TP
.B send-notify "Warning" "Disk space low"
Send a warning notification

.SH NOTIFICATION CLIENTS
send-notify supports various notification clients:
.TP
.B notify-send
Standard freedesktop notification system
.TP
.B dunst
Lightweight notification daemon
.TP
.B terminal-notifier
macOS terminal notifications
.TP
.B Others
Any freedesktop-compatible notification daemon

.SH FILES
.TP
.I ~/.config/myscripts/send-notify/settings.conf
User configuration file

.SH ENVIRONMENT VARIABLES
.TP
.B SEND_NOTIFY_CLIENT
Override default notification client
.TP
.B SEND_NOTIFY_URGENCY
Set notification urgency (low, normal, critical)
.TP
.B SEND_NOTIFY_ICON
Default icon for notifications

.SH NOTES
send-notify requires a notification daemon to be running (e.g., notification-daemon, dunst, or equivalent).

When using --all, the script sends notifications to all logged-in users, useful for system administrators.

.SH REQUIREMENTS
.TP
.B notify-send
Freedesktop notification utility
.TP
.B Notification daemon
dunst, notification-daemon, or equivalent

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/scripts/issues

.SH SEE ALSO
notify-send(1), dunst(1), notification-daemon(1)

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
