.TH SHORTENURL "1" "December 2025" "shortenurl 202208161758-git" "User Commands"
.SH NAME
shortenurl \- URL shortener
.SH SYNOPSIS
.B shortenurl
[\fI\,OPTIONS\/\fR] [\fI\,URL\/\fR]
.SH DESCRIPTION
.B shortenurl
is a script for shortening URLs using various URL shortening services. It provides a command-line interface to create short URLs.
.PP
The script can use multiple shortening services and optionally copy the result to clipboard.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B shortenurl https://example.com/very/long/url
Shorten the given URL
.TP
.B shortenurl https://github.com/user/repo
Get a short URL for a GitHub repository
.SH FILES
.TP
.B ~/.config/myscripts/shortenurl/settings.conf
User configuration file for shortenurl preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 4
Network connection failed
.SH NOTES
.IP \(bu 2
Uses various URL shortening APIs
.IP \(bu 2
Results can be copied to clipboard
.IP \(bu 2
Requires internet connection
.SH DEPENDENCIES
.TP
.B Required:
.RS
.IP \(bu 2
curl - For API requests
.RE
.TP
.B Optional:
.RS
.IP \(bu 2
xclip - For clipboard support
.RE
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR curl (1),
.BR xclip (1)
