.TH SOCIAL "1" "December 2025" "social 202208162203-git" "User Commands"
.SH NAME
social \- Social media menu written in bash
.SH SYNOPSIS
.B social
[\fI\,OPTIONS\/\fR] [\fI\,PLATFORM\/\fR]
.SH DESCRIPTION
.B social
is a menu-driven script for accessing various social media platforms and services. It provides a unified interface for launching social media clients and web interfaces.
.PP
The script can launch platform-specific clients or open web versions in a browser.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B social
Launch interactive social media menu
.TP
.B social mastodon
Open Mastodon client
.SH FILES
.TP
.B ~/.config/myscripts/social/settings.conf
User configuration file for social preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Menu-driven interface
.IP \(bu 2
Supports multiple platforms
.IP \(bu 2
Can use CLI or web interfaces
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR post2social (1),
.BR toot (1)
