.TH TASKS "1" "December 2025" "tasks 202208170256-git" "User Commands"
.SH NAME
tasks \- Wrapper for task management
.SH SYNOPSIS
.B tasks
[\fI\,OPTIONS\/\fR] [\fI\,COMMAND\/\fR] [\fI\,ARGUMENTS\/\fR]
.SH DESCRIPTION
.B tasks
is a wrapper script for task management applications. It provides a unified interface for managing tasks and to-do items from the command line.
.PP
The script integrates with various task management backends.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH COMMANDS
.TP
.B add TASK
Add a new task
.TP
.B list
List all tasks
.TP
.B done ID
Mark task as done
.SH EXAMPLES
.TP
.B tasks add "Review code"
Add a new task
.TP
.B tasks list
Show all tasks
.SH FILES
.TP
.B ~/.config/myscripts/tasks/settings.conf
User configuration file for tasks preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Wrapper for task management tools
.IP \(bu 2
Command-line interface
.IP \(bu 2
Persistent task storage
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR task (1),
.BR todo.txt-cli (1)
