.TH TIMEIS "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
timeis \- Get current time for any timezone
.SH SYNOPSIS
.B timeis
[\fI\,OPTIONS\/\fR] [\fI\,TIMEZONE\/\fR]
.SH DESCRIPTION
.B timeis
is a script for displaying the current time in any timezone. It provides a simple way to check the time in different locations around the world.
.PP
The script supports standard timezone names and abbreviations.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B timeis
Show local time
.TP
.B timeis UTC
Show time in UTC
.TP
.B timeis America/New_York
Show time in New York
.TP
.B timeis Europe/London
Show time in London
.SH FILES
.TP
.B ~/.config/myscripts/timeis/settings.conf
User configuration file for timeis preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Supports standard timezone names
.IP \(bu 2
Uses system timezone database
.IP \(bu 2
Lists available timezones with --list
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR date (1),
.BR timedatectl (1),
.BR tzselect (8)
