.\" Manpage for timer
.TH man 1 "09 Sep 2025" "202509092128-git" "timer"

.SH NAME
timer

.SH DESCRIPTION
 Set a timer

.SH SYNOPSIS
timer [options] [time]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting
.TP
.B \-\-silent
Suppress status messages

.SH TIME FORMATS
.TP
.B 5
5 seconds (default)
.TP
.B 30s
30 seconds
.TP
.B 5m
5 minutes
.TP
.B 2h
2 hours
.TP
.B 1d
1 day
.TP
.B 1w
1 week
.TP
.B 1M
1 month
.TP
.B 1y
1 year

.SH EXAMPLES
.TP
.B timer
Sets a default 60 second timer
.TP
.B timer 30
Sets a 30 second timer
.TP
.B timer 5m
Sets a 5 minute timer
.TP
.B timer 2h
Sets a 2 hour timer

.SH FILES
.TP
.I ~/.config/myscripts/timer/settings.conf
User configuration file

.SH AUTHOR
Jason Hempstead (jason@casjaysdev.pro)

.SH COPYRIGHT
Copyright (c) 2022 Jason Hempstead, Casjays Developments

.SH LICENSE
WTFPL

.SH SEE ALSO
sleep(1), at(1), crontab(1)