.TH TYPE "1" "December 2025" "type 202208180109-git" "User Commands"
.SH NAME
type \- Bash builtin type wrapper
.SH SYNOPSIS
.B type
[\fI\,OPTIONS\/\fR] [\fI\,NAME\/\fR]...
.SH DESCRIPTION
.B type
is a wrapper script for the bash builtin type command. It provides information about command types (alias, function, builtin, file, or keyword).
.PP
The script extends the builtin with additional formatting and options.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B type ls
Show type of ls command
.TP
.B type cd echo
Show types of multiple commands
.SH FILES
.TP
.B ~/.config/myscripts/type/settings.conf
User configuration file for type preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
Command not found
.SH NOTES
.IP \(bu 2
Wrapper for bash builtin type
.IP \(bu 2
Shows command locations
.IP \(bu 2
Identifies aliases and functions
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR which (1),
.BR whereis (1),
.BR command (1)
