.TH UPDATE-LECERTS "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
update-lecerts \- Update Let's Encrypt certificates
.SH SYNOPSIS
.B update-lecerts
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
.B update-lecerts
is a script for managing and renewing Let's Encrypt SSL/TLS certificates. It automates the certificate renewal process and can copy certificates to appropriate locations.
.PP
The script integrates with certbot for certificate management.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B update-lecerts
Renew certificates
.TP
.B update-lecerts --force
Force certificate renewal
.SH FILES
.TP
.B ~/.config/myscripts/update-lecerts/settings.conf
User configuration file for update-lecerts preferences
.TP
.B /etc/letsencrypt/
Let's Encrypt certificate directory
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 3
Certbot not found
.SH NOTES
.IP \(bu 2
Integrates with certbot
.IP \(bu 2
Automates certificate renewal
.IP \(bu 2
Can distribute certificates
.SH DEPENDENCIES
.TP
.B Required:
.RS
.IP \(bu 2
certbot - Let's Encrypt client
.RE
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2023 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR certbot (1)
