.TH UPDATE-MOTD "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
update-motd \- Update the MOTD and ISSUE files
.SH SYNOPSIS
.B update-motd
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
.B update-motd
is a script for updating the system Message of the Day (MOTD) and pre-login issue files. It regenerates these files with current system information.
.PP
The script can include system stats, IP addresses, and custom messages.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B update-motd
Update MOTD with system info
.SH FILES
.TP
.B ~/.config/myscripts/update-motd/settings.conf
User configuration file for update-motd preferences
.TP
.B /etc/motd
Message of the day file
.TP
.B /etc/issue
Pre-login message file
.TP
.B /etc/issue.net
Remote login message file
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 2
Permission denied (requires root)
.SH NOTES
.IP \(bu 2
Requires root privileges
.IP \(bu 2
Updates MOTD and issue files
.IP \(bu 2
Includes system information
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR update-ip (1),
.BR motd (5),
.BR issue (5)
