.TH URLDECODE "1" "December 2025" "urldecode 202208180247-git" "User Commands"
.SH NAME
urldecode \- Decode a URL-encoded string
.SH SYNOPSIS
.B urldecode
[\fI\,OPTIONS\/\fR] [\fI\,STRING\/\fR]
.PP
echo \fI\,STRING\/\fR | .B urldecode
.SH DESCRIPTION
.B urldecode
is a script for decoding URL-encoded strings. It converts percent-encoded characters (like %20) back to their original form.
.PP
The script handles standard URL encoding used in web URLs and query strings.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B urldecode "hello%20world"
Output: hello world
.TP
.B echo "foo%3Dbar" | urldecode
Output: foo=bar
.SH FILES
.TP
.B ~/.config/myscripts/urldecode/settings.conf
User configuration file for urldecode preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Decodes percent-encoded characters
.IP \(bu 2
Handles standard URL encoding
.IP \(bu 2
Supports stdin input
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR urlencode (1)
