.TH URLENCODE "1" "December 2025" "urlencode 202208180257-git" "User Commands"
.SH NAME
urlencode \- Encode a string for URL use
.SH SYNOPSIS
.B urlencode
[\fI\,OPTIONS\/\fR] [\fI\,STRING\/\fR]
.PP
echo \fI\,STRING\/\fR | .B urlencode
.SH DESCRIPTION
.B urlencode
is a script for URL-encoding strings. It converts special characters to percent-encoded format suitable for use in URLs.
.PP
The script handles all characters that need encoding for safe URL transport.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B urlencode "hello world"
Output: hello%20world
.TP
.B echo "foo=bar" | urlencode
Output: foo%3Dbar
.SH FILES
.TP
.B ~/.config/myscripts/urlencode/settings.conf
User configuration file for urlencode preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.SH NOTES
.IP \(bu 2
Encodes special characters
.IP \(bu 2
RFC 3986 compliant
.IP \(bu 2
Supports stdin input
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR urldecode (1)
