.TH USB-WRITER "1" "December 2025" "202602020740-git" "User Commands"
.SH NAME
usb-writer \- Create bootable USB with multi-boot support
.SH SYNOPSIS
.B usb-writer
[\fI\,OPTIONS\/\fR] [\fI\,ISO_FILE\/\fR] [\fI\,DEVICE\/\fR]
.SH DESCRIPTION
.B usb-writer
is a script for creating bootable USB drives with multi-boot support. It can write ISO images to USB drives and set up GRUB for booting multiple operating systems.
.PP
The script supports automatic GRUB menu generation for added ISO files.
.SH OPTIONS
.TP
.BR \-\-help
Display help message with usage information and available options
.TP
.BR \-\-config
Generate or regenerate user configuration file with default settings
.TP
.BR \-\-version
Show script version information and exit
.TP
.BR \-\-options
Display all available command-line options
.TP
.BR \-\-debug
Enable debug mode with verbose output and command tracing (set -x)
.TP
.BR \-\-raw
Disable colorized output for plain text display
.SH EXAMPLES
.TP
.B usb-writer ubuntu.iso /dev/sdb
Write Ubuntu ISO to USB drive
.TP
.B usb-writer --add fedora.iso /dev/sdb
Add Fedora to multi-boot USB
.TP
.B usb-writer --list /dev/sdb
List ISOs on multi-boot USB
.SH FILES
.TP
.B ~/.config/myscripts/usb-writer/settings.conf
User configuration file for usb-writer preferences
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
General error
.TP
.B 2
Permission denied (requires root)
.TP
.B 3
Device not found
.SH NOTES
.IP \(bu 2
Multi-boot support with GRUB
.IP \(bu 2
Auto-generates boot menu
.IP \(bu 2
Supports ISO management
.IP \(bu 2
WARNING: Overwrites USB drive contents
.SH DEPENDENCIES
.TP
.B Required:
.RS
.IP \(bu 2
dd - For writing ISO
.IP \(bu 2
grub-install - For GRUB (multi-boot)
.RE
.SH BUGS
Report bugs at: https://github.com/casjay-dotfiles/scripts/issues
.SH AUTHOR
Written by Jason Hempstead (CasjaysDev)
.SH COPYRIGHT
Copyright \(co 2022 Jason Hempstead, Casjays Developments
.br
License: WTFPL (Do What The F*** You Want To Public License)
.SH SEE ALSO
.BR dd (1),
.BR grub-install (8)
