.\" Manpage for weather
.TH man 1 "09 Sep 2025" "202509092118-git" "weather"

.SH NAME
weather

.SH DESCRIPTION
 weather in your console

.SH SYNOPSIS
weather [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all available options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting
.TP
.B \-\-silent
Suppress status messages
.TP
.B \-\-airport [code]
Set location using airport code
.TP
.B \-\-zipcode [code]
Set location using zip code
.TP
.B \-\-citystate [city,state]
Set location to city,state
.TP
.B \-\-local
Use local geolocation
.TP
.B \-\-default
Use default location settings
.TP
.B \-\-flags [flags]
Set additional api flags

.SH COMMANDS
.TP
.B weather
Get weather based on geolocation
.TP
.B city [cityName]
Get weather for specified city
.TP
.B image [cityName]
Download weather image
.TP
.B moon [cityName]
Show moon phases for location
.TP
.B simple [cityName]
Get results in simple format
.TP
.B script
Cached weather for scripts
.TP
.B v2 [cityName]
Use version 2 of weather api
.TP
.B v3 [cityName]
Use version 3 of weather api
.TP
.B info
Show current location settings
.TP
.B :help
Show help from weather api

.SH EXAMPLES
.TP
.B weather
Show weather for current location
.TP
.B weather city "New York"
Show weather for New York
.TP
.B weather \-\-zipcode 12345
Set location using zip code
.TP
.B weather moon
Show moon phases for current location
.TP
.B weather simple
Get simple weather format
.TP
.B weather v2
Use version 2 API

.SH FILES
.TP
.I
~/.config/myscripts/weather/settings.conf
.TP
.I
/usr/local/bin/weather

.SH ENVIRONMENT
.TP
.B WEATHER_MY_LOCATION_ZIP
Default zip code for weather location
.TP
.B WEATHER_MY_LOCATION_NAME
Default location name for weather
.TP
.B MYLOCATION_ZIP
System zip code setting
.TP
.B MYLOCATION_NAME
System location name setting

.SH TODO
 Better documentation

.SH LICENSE
WTFPL

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>