#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="am_i_online"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121657-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  am_i_online --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 16:57 EDT
# @File              :  am_i_online
# @Description       :  Manual for am_i_online
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$am_i_online}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "am_i_online")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "am_i_online: Check for internet connection"
__printf_help " " "                                                  "
__printf_help "5" "Usage: am_i_online [options]"
__printf_help "4" "am_i_online --force                               - Returns true"
__printf_help "4" "am_i_online --error                               - Show error message"
__printf_help "4" "am_i_online --show                                - Shows status"
__printf_help "4" "am_i_online --console                             - Prints output to console"
__printf_help "4" "am_i_online --message                             - Custom message"
__printf_help "4" "am_i_online --site                                - Use another site"
__printf_help "4" "am_i_online --code                                - Status code to check"

__printf_head "5" "Other Options"
__printf_help "4" "am_i_online --config                              - Generate user config file"
__printf_help "4" "am_i_online --version                             - Show script version"
__printf_help "4" "am_i_online --help                                - Shows this message"
__printf_help "4" "am_i_online --options                             - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "$APPNAME_README "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
