#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This is what I use for my system scripts
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202207042244-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  LICENSE.md
# @ReadME            :  anime-dl --help
# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created           :  Tuesday, Jul 05, 2022 13:46 EDT
# @File              :  anime-dl
# @Description       :  Search and download anime
# @TODO              :
# @Other             :
# @Resource          :
# @sudo/root         :  no
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
APPNAME_README="anime-dl"
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-systemmgr}")" | grep "${1:-}"; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__version() { __grep_head 'Version' "$(type -P "${2:-systemmgr}")" | __sed_head | head -n1 | grep '^'; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "$APPNAME_README: $(__grep_head "Description" "$APPNAME_README" | __sed_head)"
__printf_help " " "                                                  "
__printf_help "5" "Usage: $APPNAME_README [-c,-a,-d,-q,-v]"
__printf_help "4" "-c                                                - continue watching anime from history"
__printf_help "4" "-a                                                - specify episode to watch"
__printf_help "4" "-h                                                - show helptext"
__printf_help "4" "-d                                                - download episode"
__printf_help "4" "-p                                                - download episode to specified directory"
__printf_help "4" "-q                                                - set video quality (best|worst|360|480|720|1080)"
__printf_help "4" "-v                                                - use VLC as the media player"
__printf_help "4" "-D                                                - delete history"
__printf_help "4" "-U                                                - fetch update from github"
__printf_help "4" "-V                                                - print version number and exit"
__printf_help " " "                                                  "
__printf_head "5" "Other $APPNAME_README Options"
__printf_help "4" "$APPNAME_README --config                          - Generate user config file"
__printf_help "4" "$APPNAME_README --version                         - Show script version"
__printf_help "4" "$APPNAME_README --help                            - Shows this message"
__printf_help "4" "$APPNAME_README --options                         - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "$APPNAME_README "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
