#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="automate"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108121038-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : automate --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Aug 12, 2021 10:38 EDT
# @File          : automate
# @Description   : Manual for automate
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$automate}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "automate")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "automate: Script to control roku and hue devices"
__printf_help " " "                                                  "
__printf_help "4" "Usage: automate [pause,play,stop,toggle]"
__printf_help " " "                                                  "
__printf_help "4" "$APPNAME_README automate pause                    -  Turn hue lights on/off and play/pause roku"
__printf_help "4" "$APPNAME_README automate play                     -  Turn hue lights off and play roku"
__printf_help "4" "$APPNAME_README automate stop                     -  Turn hue lights on and stop roku"
__printf_help "4" "$APPNAME_README automate toggle                   -  Same as pause"

__printf_head "5" "           Other  Options"
__printf_help "4" "$APPNAME_README --config                      -  Generate user config file"
__printf_help "4" "$APPNAME_README --version                     -  Show script version"
__printf_help "4" "$APPNAME_README --help                        -  Shows this message"
__printf_help "4" "$APPNAME_README --options                         -  Shows all available options"

#__printf_head "5" "           This is a work in progress"
#__printf_help "4" " "

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"
