#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="backupapp"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108121657-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : backupapp --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Aug 12, 2021 16:57 EDT
# @File          : backupapp
# @Description   : Manual for backupapp
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$backupapp}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "backupapp")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "backupapp: Backup files and folders"
__printf_help " " "                                                  "
__printf_help "4" "Usage: backupapp [backupName Directory]"
__printf_help " " "                                                  "
__printf_help "4" "$APPNAME_README --cron                            -  Run cron options"
__printf_help "4" "$APPNAME_README --term                            -  Run in terminal"
__printf_head "5" "           cron  Options [add,del,list]"
__printf_help "4" "$APPNAME_README --cron add                        -  Save cron job"
__printf_help "4" "$APPNAME_README --cron del                        -  Delete cron job"
__printf_help "4" "$APPNAME_README --cron list                       -  List cron jobs"
__printf_help "4" " -  "
__printf_help " " "                                                  "
__printf_head "5" "Other  Options"
__printf_help "4" "$APPNAME_README -c, --config                      - generate user config file"
__printf_help "4" "$APPNAME_README -v, --version                     - show script version"
__printf_help "4" "$APPNAME_README -h, --help                        - Shows this message"
__printf_help "4" "$APPNAME_README --options                         - files used for completion"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "$APPNAME_README "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"
