#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "2" "A simple blogging script"
printf_help "4" 'blog page "./path_to_page" "title_of_page"  | Create a blog page'
printf_help "4" 'blog post "title_of_post"                   | Create a new post'
printf_newline
printf_help "4" 'blog new "./directory" "title"              | create blog post in a different dir'
printf_newline
printf_help "4" 'blog -c name                                | use a different config'
printf_help "4" 'blog config                                 | create a default config'
printf_help "4" 'blog config name directory                  | create a custom config'
printf_newline
printf_help "4" 'By default the blog dir is '$BLOG_DIR''
printf_help "4" 'however, this can be changed with the BLOG_DIR variable'
