#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="blog"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121835-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  blog --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 18:35 EDT
# @File              :  blog
# @Description       :  Manual for blog
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$blog}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "blog")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "blog: Blogging script using github pages"
__printf_help " " "                                                  "
__printf_help "5" "Usage: blog [page,post,new]"

__printf_help "4" 'blog page "./path_to_page" "title_of_page"        - Create a blog page'
__printf_help "4" 'blog post "title_of_post"                         - Create a new post'
__printf_help "4" 'blog new "./directory" "title"                    - create blog post in a different dir'
__printf_help "4" 'blog config                                       - create a default config'
__printf_help "4" 'blog config name directory                        - create a custom config'
__printf_help "4" 'blog -c name                                      - use a different config'

__printf_head "5" "Other Options"
__printf_help "4" "blog --config                                     - Generate user config file"
__printf_help "4" "blog --version                                    - show script version"
__printf_help "4" "blog --help                                       - Shows this message"
__printf_help "4" "blog --options                                    - Shows all available options"
__printf_help " " "                                                  "
__printf_help "4" ''
#__printf_head "5" "By default the blog dir is $BLOG_DIR"
__printf_help "4" 'however, this can be changed with the BLOG_DIR variable'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
