#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="calendar"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  calendar --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  calendar
# @Description       :  Manual for calendar
# @TODO              :
# @Other             :
# @Resource          :  https://github.com/coreymwamba/estonta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$calendar}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "calendar")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "calendar: A calendar written in bash"
__printf_help " " "                                                  "
__printf_help "5" "Usage: calendar []"

__printf_help "calendar                                              - Show all events"
__printf_help "calendar add                                          - Add event in console."
__printf_help "calendar guia                                         - Add event using a graphical dialog interface."
__printf_help "calendar gui                                          - Graphical calendar display of events (can also add events)."
__printf_help "calendar category=TEXT                                - List all saved events filtered by category."
__printf_help "calendar summary=TEXT                                 - List all saved events filtered by summary."
__printf_help "calendar date=DATE_STRING                             - Find events matching the date string."
__printf_help "calendar find START_DATE_STRING END_DATE_STRING       - Find events within a date range."

__printf_head "5" "Other Options"
__printf_help "4" "calendar --config                                 - Generate user config file"
__printf_help "4" "calendar --version                                - Show script version"
__printf_help "4" "calendar --help                                   - Shows this message"
__printf_help "4" "calendar --options                                - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "calendar "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
