#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This is what I use for my system scripts
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# REPLACE_THIS_WITH_HEADER_INFO
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
APPNAME_README="client-installs"
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$gitadmin}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "gitadmin")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "client-installs: $(__grep_head "Description" "${client-installs:-client-installs help}" | __sed_head)"
__printf_help " " "                                                  "
__printf_help "5" "Usage: client-installs []"
__printf_help "4" "  - "
__printf_help " " "                                                  "
__printf_head "5" "Other client-installs Options"
__printf_help "4" "client-installs --config                          - Generate user config file"
__printf_help "4" "client-installs --version                         - Show script version"
__printf_help "4" "client-installs --help                            - Shows this message"
__printf_help "4" "client-installs --options                         - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "client-installs "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
