#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="cloudflare"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108042358-git
# @Author            :  casjay
# @Contact           :  casjay
# @License           :  WTFPL
# @ReadME            :  cloudflare --help
# @Copyright         :  Copyright: (c) 2021 casjay, casjay
# @Created           :  Wednesday, Aug 04, 2021 23:58 EDT
# @File              :  cloudflare
# @Description       :  Manual for cloudflare
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$cloudflare}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "cloudflare")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
printf '\n'
__printf_head "5" "cloudflare: cloudflare api script"
__printf_help " " "                                                  "
__printf_help "5" "Usage: cloudflare [create,update,delete,list,verify]"

__printf_help "4" "cloudflare create [zone record type proxy]        - Create a new hostname"
__printf_help "4" "cloudflare update [zone record type proxy]        - Update a hostname"
__printf_help "4" "cloudflare delete [zone]                          - Delete a hostname"
__printf_help "4" "cloudflare list [--full]                          - List the hostnames in zone"
__printf_help "4" "cloudflare verify                                 - Verify api key"

__printf_head "5" "Other Options"
__printf_help "4" "cloudflare --config                               - Generate user config file"
__printf_help "4" "cloudflare --version                              - Show script version"
__printf_help "4" "cloudflare --help                                 - Shows this message"
__printf_help "4" "cloudflare --options                              - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "cloudflare "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
