#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="__cmd_exists"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108042358-git
# @Author            :  casjay
# @Contact           :  casjay
# @License           :  WTFPL
# @ReadME            :  __cmd_exists --help
# @Copyright         :  Copyright: (c) 2021 casjay, casjay
# @Created           :  Wednesday, Aug 04, 2021 23:58 EDT
# @File              :  __cmd_exists
# @Description       :  Manual for __cmd_exists
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$__cmd_exists}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "__cmd_exists")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
printf '\n'
__printf_head "5" "__cmd_exists: Check to see if command exists"
__printf_help " " "                                                  "
__printf_help "5" "Usage: __cmd_exists [--ask,--show,--error]"

__printf_help "4" "__cmd_exists --ask                                  - Ask to install if missing"
__printf_help "4" "__cmd_exists --error                                - Show errors"
__printf_help "4" "__cmd_exists --show                                 - Show command path"

__printf_head "5" "Other Options"
__printf_help "4" "__cmd_exists --config                               - Generate user config file"
__printf_help "4" "__cmd_exists --version                              - Show script version"
__printf_help "4" "__cmd_exists --help                                 - Shows this message"
__printf_help "4" "__cmd_exists --options                              - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "__cmd_exists "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
