#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="config"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108042358-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : config --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Wednesday, Aug 04, 2021 23:58 EDT
# @File          : config
# @Description   : Manual for config
# @TODO          : 
# @Other         : 
# @Resource      : https://www.atlassian.com/git/tutorials/dotfiles
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$config}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "config")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "config: Add dotfiles/config files to a git repo"
printf '\n'
__printf_help "2" "A git utility for keeping your dotfiles in a git repo"
__printf_help "4" "usage: config init add commit push help set remote checkout"
__printf_help "4" " "
__printf_help "4" "These are common config commands used in various situations:"
__printf_help "4" " "
__printf_help "4" "start a working area"
__printf_help "4" "init       Create an empty config repository or reinitialize an existing one"
__printf_help "4" " "
__printf_help "4" "work on the current change"
__printf_help "4" "add        Add file contents to the index"
__printf_help "4" "mv         Move or rename a file, a directory, or a symlink"
__printf_help "4" "reset      Reset current HEAD to the specified state"
__printf_help "4" "rm         Remove files from the working tree and from the index"
__printf_help "4" " "
__printf_help "4" "examine the history and state"
__printf_help "4" "bisect     Use binary search to find the commit that introduced a bug"
__printf_help "4" "grep       Print lines matching a pattern"
__printf_help "4" "log        Show commit logs"
__printf_help "4" "show       Show various types of objects"
__printf_help "4" "status     Show the working tree status"
__printf_help "4" " "
__printf_help "4" "grow, mark and tweak your common history"
__printf_help "4" "branch     List, create, or delete branches"
__printf_help "4" "checkout    Switch branches or restore working tree files"
__printf_help "4" "commit     Record changes to the repository"
__printf_help "4" "diff       Show changes between commits, commit and working tree, etc"
__printf_help "4" "merge      Join two or more development histories together"
__printf_help "4" "rebase     Reapply commits on top of another base tip"
__printf_help "4" "tag        Create, list, delete or verify a tag object signed with GPG"
__printf_help "4" " "
__printf_help "4" "collaborate"
__printf_help "4" "fetch      Download objects and refs from another repository"
__printf_help "4" "pull       Fetch from and integrate with another repository or a local branch"
__printf_help "4" "push       Update remote refs along with associated objects"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

