#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="config"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  config --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  config
# @Description       :  Manual for config
# @TODO              : 
# @Other             : 
# @Resource          :  https://www.atlassian.com/git/tutorials/dotfiles
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$config}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "config")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "config: Add dotfiles/config files to a git repo"
__printf_help " " "                                                  "
__printf_help "5" "Usage: config [init,add,commit,push,help,set,remote,checkout]"
__printf_head "4" "start a working area"
__printf_help "4" "config init                                       - Create an empty config repository or reinitialize an existing one"

__printf_head "4" "work on the current change"
__printf_help "4" "config add                                        - Add file contents to the index"
__printf_help "4" "config mv                                         - Move or rename a file, a directory, or a symlink"
__printf_help "4" "config reset                                      - Reset current HEAD to the specified state"
__printf_help "4" "config rm                                         - Remove files from the working tree and from the index"

__printf_head "4" "examine the history and state"
__printf_help "4" "config bisect                                     - Use binary search to find the commit that introduced a bug"
__printf_help "4" "config grep                                       - Print lines matching a pattern"
__printf_help "4" "config log                                        - Show commit logs"
__printf_help "4" "config show                                       - Show various types of objects"
__printf_help "4" "config status                                     - Show the working tree status"

__printf_head "4" "grow, mark and tweak your common history"
__printf_help "4" "config branch                                     - List, create, or delete branches"
__printf_help "4" "config checkout                                   - Switch branches or restore working tree files"
__printf_help "4" "config commit                                     - Record changes to the repository"
__printf_help "4" "config diff                                       - Show changes between commits, commit and working tree, etc"
__printf_help "4" "config merge                                      - Join two or more development histories together"
__printf_help "4" "config rebase                                     - Reapply commits on top of another base tip"
__printf_help "4" "config tag                                        - Create, list, delete or verify a tag object signed with GPG"

__printf_head "4" "collaborate"
__printf_help "4" "config fetch                                      - Download objects and refs from another repository"
__printf_help "4" "config pull                                       - Fetch from and integrate with another repository or a local branch"
__printf_help "4" "config push                                       - Update remote refs along with associated objects"

__printf_head "5" "Other Options"
__printf_help "4" "config --config                                   - Generate user config file"
__printf_help "4" "config --version                                  - Show script version"
__printf_help "4" "config --help                                     - Shows this message"
__printf_help "4" "config --options                                  - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "config "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
