#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="desktopmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  desktopmgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  desktopmgr
# @Description       :  Manual for desktopmgr
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$desktopmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "desktopmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "desktopmgr: Desktop ManaGeR"
__printf_help " " "                                                  "
__printf_help "5" "Usage: desktopmgr []"

__printf_help "4" "desktopmgr version                                     - show the version info"
__printf_help "4" "desktopmgr available                                   - list available dotfiles"
__printf_help "4" "desktopmgr list                                        - list installed dotfiles"
__printf_help "4" "desktopmgr search                                      - find a dotfile"
__printf_help "4" "desktopmgr install                                     - install a dotfile"
__printf_help "4" "desktopmgr update                                      - update the dotfiles"
__printf_help "4" "desktopmgr personal                                    - update personal dotfiles"

__printf_head "5" "Other Options"
__printf_help "4" "desktopmgr --config                                    - Generate user config file"
__printf_help "4" "desktopmgr --version                                   - Show script version"
__printf_help "4" "desktopmgr --help                                      - Shows this message"
__printf_help "4" "desktopmgr --options                                   - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "desktopmgr "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
