#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="devenvmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  devenvmgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  devenvmgr
# @Description       :  Manual for devenvmgr
# @TODO              :  Create user config
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$devenvmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "devenvmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "devenvmgr: Setup a development environment"
__printf_help " " "                                                  "
__printf_help "5" "Usage: devenvmgr [options]"

__printf_help "4" "devenvmgr import                                  - Import a site from git"
__printf_help "4" "devenvmgr static                                  - Create static site"
__printf_help "4" "devenvmgr jekyll                                  - Setup a jekyll site"
__printf_help "4" "devenvmgr hugo                                    - Setup a hugo site"
__printf_help "4" "devenvmgr ruby                                    - Setup a ruby dev enviroment"
__printf_help "4" "devenvmgr python                                  - Setup a python dev enviroment"
__printf_help "4" "devenvmgr perl                                    - Setup a perl dev enviroment"
__printf_help "4" "devenvmgr php                                     - Setup a php dev enviroment"
__printf_help "4" "devenvmgr node                                    - Setup a node dev enviroment"
__printf_help "4" "devenvmgr vue                                     - Setup a vue dev enviroment"
__printf_help "4" "devenvmgr react                                   - Setup a react dev enviroment"
__printf_help "4" "devenvmgr express                                 - Setup a express dev enviroment"
__printf_help "4" "devenvmgr create-project                          - Setup a new website"
__printf_help "4" "devenvmgr html                                    - Setup a blank site"
__printf_help "4" "devenvmgr mevn                                    - Setup a mevn dev enviroment"
__printf_help "4" "devenvmgr shellcheck                              - Setup shellcheck"
__printf_help "4" "devenvmgr editorconfig                            - Setup editorconfig"
__printf_help "4" "devenvmgr package                                 - Setup a node enviroment"
__printf_help "4" "devenvmgr prettier                                - Setup prettier"
__printf_help "4" "devenvmgr eslint                                  - Setup eslint"
__printf_help "4" "devenvmgr download                                - Download an enviroment"

__printf_head "5" "devenvmgr: start [jekyll]"
__printf_help "4" "devenvmgr start jekyll                            - Launch jekyll"

__printf_head "5" "Other Options"
__printf_help "4" "devenvmgr --config                                - Generate user config file"
__printf_help "4" "devenvmgr --version                               - Show script version"
__printf_help "4" "devenvmgr --help                                  - Shows this message"
__printf_help "4" "devenvmgr --options                               - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "devenvmgr "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
