#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="dockermgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108230234-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  dockermgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created           :  Monday, Aug 23, 2021 02:34 EDT
# @File              :  dockermgr
# @Description       :  Manual for dockermgr
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$dockermgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "dockermgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "dockermgr: docker script to manage containers"
__printf_help "" ""
__printf_help "5" "Usage: dockermgr [options]"
__printf_help "4" "dockermgr init                           - Initialize dockermgr"
__printf_help "4" "dockermgr run                            - run a container"
__printf_help "4" "dockermgr test                           - test a docker image"
__printf_help "4" "dockermgr exec                           - execute a command in a container"
__printf_help "4" "dockermgr enter                          - enter a container"
__printf_help "4" "dockermgr connect                        - connect to a container"
__printf_help "4" "dockermgr active                         - show active containers"
__printf_help "4" "dockermgr inactive                       - show inactive containers"
__printf_help "4" "dockermgr network                        - show docker network info"
__printf_help "4" "dockermgr minikube                       - install Minikube"
__printf_help "4" "dockermgr k3b                            - install Kubernetes"
__printf_help "4" "dockermgr rancher                        - install Rancher"
__printf_help "4" "dockermgr helm                           - install helm"
__printf_help "4" "dockermgr ds                             - install dockstarter"
__printf_help "4" "dockermgr rm                             - remove a container"
__printf_help "4" "dockermgr ps                             - show running containers"
__printf_help "4" "dockermgr rmi                            - remove an image"
__printf_help "4" "dockermgr status                         - show docker status"
__printf_help "4" "dockermgr list                           - list preconfigured installation scripts"
__printf_help "4" "dockermgr available                      - show available installation scripts"
__printf_help "4" "dockermgr search                         - search for preconfigured installation scripts"
__printf_help "4" "dockermgr install                        - install via preconfigured installation scripts"
__printf_help "4" "dockermgr update                         - update preconfigured installation scripts"
__printf_help "4" "dockermgr download                       - download git repo"
__printf_help "4" "dockermgr remove                         - remove the docker script"
__printf_help "4" "dockermgr pull                           - update docker images"
__printf_help "4" "dockermgr log                            - Show container logs"
__printf_help "4" "dockermgr api                            - docker hub API actions"
__printf_help "" ""
__printf_help "" ""
__printf_head "5" "Other Options"
__printf_help "4" "dockermgr --config                       - Generate user config file"
__printf_help "4" "dockermgr --version                      - Show script version"
__printf_help "4" "dockermgr --help                         - Shows this message"
__printf_help "4" "dockermgr --options                      - Shows all available options"
__printf_help "4" "dockermgr --version                      - Show version info"
__printf_help " " "                                         "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "dockermgr "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
