#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="emojis"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108042359-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : emojis --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Wednesday, Aug 04, 2021 23:59 EDT
# @File          : emojis
# @Description   : Manual for emojis
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$emojis}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "emojis")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "emojis: show and choose an emoji"
printf '\n'
__printf_help "4" '           🙄😆 emojify - emojis on the command line 😱😄'
__printf_help "4" '-h|help|-help|--help        | This help!                  | emojis help'
__printf_help "4" '-s|search|-search|--search  | search for an emoji         | emojis search smile'
__printf_help "4" '-l|list|-list|--list        | list all available emojis   | emojis list'
__printf_help "4" '-p|print|-print|--print     | print to console            | emojis print "Hello :smile:" '
__printf_help "4" '-update|update|--update     | update emojify              | emojis update'
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

