#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="emojis"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108042359-git
# @Author            :  casjay
# @Contact           :  casjay
# @License           :  WTFPL
# @ReadME            :  emojis --help
# @Copyright         :  Copyright: (c) 2021 casjay, casjay
# @Created           :  Wednesday, Aug 04, 2021 23:59 EDT
# @File              :  emojis
# @Description       :  Manual for emojis
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$emojis}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "emojis")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
printf '\n'
__printf_head "5" "emojis: show and choose an emoji"

__printf_help "4" 'emojify - emojis on the command line'
__printf_help "4" 'emojis search                                     - search for an emoji      '
__printf_help "4" 'emojis list                                       - list all available emojis'
__printf_help "4" 'emojis print                                      - print to console         '
__printf_help "4" 'emojis update                                     - update emojify           '

__printf_head "5" "Other Options"
__printf_help "4" "emojis --config                                   - generate user config file"
__printf_help "4" "emojis --version                                  - show script version"
__printf_help "4" "emojis --help                                     - Shows this message"
__printf_help "4" "emojis --options                                  - Shows all available options"
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "check_app "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
