#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="fontmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108042359-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : fontmgr --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Wednesday, Aug 04, 2021 23:59 EDT
# @File          : fontmgr
# @Description   : Manual for fontmgr
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$fontmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "fontmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "fontmgr: Install system fonts"
printf '\n'
__printf_help "4" "A Package Manager for all systems   |   Usage: sudo fontmgr command"
__printf_help "4" "fontmgr version              - show the version info          | IE: fontmgr version Hack"
__printf_help "4" "fontmgr makecache            - update font cache              | IE: fontmgr makecache"
__printf_help "4" "fontmgr list                 - list all installable fonts     | IE: fontmgr list"
__printf_help "4" "fontmgr list-installed       - list installed fonts           | IE: fontmgr list-installed"
__printf_help "4" "fontmgr search               - find font                      | IE: fontmgr search font"
__printf_help "4" "fontmgr search-installed     - search installed fonts         | IE: fontmgr search-installed font"
__printf_help "4" "fontmgr install              - install a font                 | IE: fontmgr install font"
__printf_help "4" "fontmgr remove               - remove a font                  | IE: fontmgr remove font"
__printf_help "4" "fontmgr update               - update the fonts               | IE: fontmgr update"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

