#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="fontmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  fontmgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  fontmgr
# @Description       :  Manual for fontmgr
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$fontmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "fontmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "fontmgr: Install system fonts"
__printf_help " " "                                                  "
__printf_help "5" "Usage: fontmgr []"
__printf_help "4" "fontmgr version                                   - show the version info"
__printf_help "4" "fontmgr makecache                                 - update font cache"
__printf_help "4" "fontmgr list                                      - list all installable fonts"
__printf_help "4" "fontmgr list-installed                            - list installed fonts"
__printf_help "4" "fontmgr search                                    - find font"
__printf_help "4" "fontmgr search-installed                          - search installed fonts"
__printf_help "4" "fontmgr install                                   - install a font"
__printf_help "4" "fontmgr remove                                    - remove a font"
__printf_help "4" "fontmgr update                                    - update the fonts"
__printf_help " " "                                                  "
__printf_head "5" "Other Options"
__printf_help "4" "fontmgr --config                                  - Generate user config file"
__printf_help "4" "fontmgr --version                                 - Show script version"
__printf_help "4" "fontmgr --help                                    - Shows this message"
__printf_help "4" "fontmgr --options                                 - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "fontmgr "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
