#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="gen-script"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050000-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : gen-script --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:00 EDT
# @File          : gen-script
# @Description   : Manual for gen-script
# @TODO          : Reactor code/Group Functions/Create separate gen-header script
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$gen-script}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "gen-script")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "gen-script: Create a script from template"
printf '\n'
__printf_help "4" "Usage: gen-script template filename options"
__printf_head "5" "Main options"
__printf_help "4" "-a, --options               - Generates the options file for completion"
__printf_help "4" "-c, --copy                  - Copy the sample scripts to ~/.config/gen-script/files"
__printf_help "4" "-g. --config                - Creates the config file"
__printf_help "4" "-f, --function              - Generates the function options"
__printf_help "4" "-head, --header             - Generates header: See header options"
__printf_head "5" "Header options"
__printf_help "4" "-h, --help                  -  Show this message"
__printf_help "4" "-a, --all                   -  Show options"
__printf_help "4" "-f, --functions             -  Shows functions"
__printf_help "4" "-d, --description           -  Creates the description for file header"
__printf_help "4" "-t, --todo                  -  Add a TODO to file header"
__printf_help "4" "-c, --copy                  -  Adds a copyrigth to file header"
__printf_help "4" "-o, --other                 -  Adds an other to the file header"
__printf_help "4" "-r, --res                   -  Adds resources to the file header"
__printf_help "4" "-i, --type                  -  Adds type to functions: user system"
__printf_help "4" "-p, --prev                  -  Will set header based on an existing file"
__printf_help "4" "-u, --user                  -  Generate a script for suitable for local user"
__printf_help "4" "-l, --license               -  Adds the license type to header"
__printf_help "4" "-e, --no                    -  Don't ask to edit file"
__printf_help "4" "-k, --keep                  -  Will not overwrite an existing file"
__printf_help "4" "--replace                   -  Imports and creates a new header to replace an older one"
__printf_help "4" "--raw                       -  Generate a raw header"
__printf_help ""
__printf_help "4" "Other types: devenv dfmgr dockermgr fontmgr iconmgr pkmgr systemmgr thememgr wallpapermgr"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

