#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="gen-caddy"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  gen-caddy --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  gen-caddy
# @Description       :  Manual for gen-caddy
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$gen-caddy}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "gen-caddy")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "gen-caddy: Setup caddy web server"
__printf_help " " "                                                  "
__printf_help "5" "Usage: gen-caddy []"
__printf_help "gen-caddy reverse port                                - Proxy to localhost:PORT."
__printf_help "gen-caddy start                                       - Start Caddy."
__printf_help "gen-caddy stop                                        - Stop/Shutdown Caddy."
__printf_help "gen-caddy reload                                      - Reload Caddy."
__printf_help "gen-caddy restart                                     - Restart Caddy."
__printf_help "gen-caddy status                                      - Check Caddy is running or not"
__printf_help "gen-caddy install                                     - Install Caddy on fresh OS."
__printf_help "gen-caddy install-naked                               - Install only Caddy and no prompt."
__printf_help "gen-caddy edit                                        - Edit Caddyfile using nano or default editor."
__printf_help "gen-caddy service                                     - Make Caddy start on boot (upstart/systemd)."
__printf_help "gen-caddy update                                      - Update Caddy."
__printf_help "gen-caddy delete                                      - Uninstall Caddy and data."
__printf_help "gen-caddy version                                     - Print version information."
__printf_help "gen-caddy about                                       - About Caddy Installer."
__printf_help " " "                                                  "
__printf_head "5" "Other Options"
__printf_help "4" "gen-caddy --config                                - Generate user config file"
__printf_help "4" "gen-caddy --version                               - Show script version"
__printf_help "4" "gen-caddy --help                                  - Shows this message"
__printf_help "4" "gen-caddy --options                               - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "gen-caddy "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
