#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="gitadmin"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050000-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : gitadmin --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:00 EDT
# @File          : gitadmin
# @Description   : Manual for gitadmin
# @TODO          : Organize this a lot better
# @Other         : Convert this to my bash system scripts
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$gitadmin}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "gitadmin")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "gitadmin: push/clone/pull from github/gitlab/private repo"
printf '\n'
__printf_head "5" "           Other $APPNAME_README Options"
__printf_help "4" "$APPNAME_README --user             -  List user repos [userName]"
__printf_help "4" "$APPNAME_README --org              -  List organization repos [orgNAME]"
__printf_help "4" "$APPNAME_README --single           -  clone a single repo [repoURL]"
__printf_help "4" "$APPNAME_README --config           -  generate user config file"
__printf_help "4" "$APPNAME_README --version          -  show script version"
__printf_help "4" "$APPNAME_README --help             -  Shows this message"
__printf_help "4" "$APPNAME_README --options          -  Shows all available options"

__printf_help "4" "           gitadmin options"
__printf_help "4" "$APPNAME_README init               -  Initialize current project into a git repo"
__printf_help "4" "$APPNAME_README setup              -  Initialize current project into a git repo"
__printf_help "4" "$APPNAME_README stow               -  Keep your dotfiles in a repo"
__printf_help "4" "$APPNAME_README status             -  Show repo status"
__printf_help "4" "$APPNAME_README log                -  Show the git log"
__printf_help "4" "$APPNAME_README branch             -  Rename the current branch"
__printf_help "4" "$APPNAME_README commit             -  Commit the current changes"
__printf_help "4" "$APPNAME_README update             -  Run git pull on all repos"
__printf_help "4" "$APPNAME_README user               -  Clone/Pull all repos owned by you"
__printf_help "4" "$APPNAME_README create             -  Create a new github repo [userName repoName]"
__printf_help "4" "$APPNAME_README delete             -  Deletes a github repo [userName repoName]"
__printf_help "4" "$APPNAME_README push               -  Push a project to a remote repo"
__printf_help "4" "$APPNAME_README pull               -  Update a local git repo"
__printf_help "4" "$APPNAME_README clone              -  Clone a git repo [remoteURL] [localDIR]"
__printf_help "4" "$APPNAME_README repos              -  Show all your public repos [userName]"
__printf_help "4" "$APPNAME_README newsite            -  Create a site using template [siteName] [repo|GITADMIN_DOMAIN_TEMPLATE]"

__printf_head "5" "           Remote Repo options [remoteURL]"
__printf_help "4" "$APPNAME_README remote show        -  Show the current remote server "
__printf_help "4" "$APPNAME_README remote add         -  Add new remote url [remoteURL]"

__printf_head "5" "           Orginization options [userName]"
__printf_help "4" "$APPNAME_README org all            -  Clone/Pull all orgs owned by you [userName]"
__printf_help "4" "$APPNAME_README org push           -  Push all your local repos to remote [userName]"
__printf_help "4" "$APPNAME_README org pull           -  Update all your local repos from remote [userName]"
__printf_help "4" "$APPNAME_README org clone          -  Clone a repo [userName]"

__printf_head "5" "           Gitgub Gist options [userName]"
__printf_help "4" "$APPNAME_README gist create        -  Create a new github gist [userName]"
__printf_help "4" "$APPNAME_README gist delete        -  Delete a github gist [userName]"
__printf_help "4" "$APPNAME_README gist edit          -  Edit github gist [userName]"
__printf_help "4" "$APPNAME_README gist list          -  List github gists [userName]"
__printf_help "4" "$APPNAME_README gist search        -  Search for github gist [userName]"

__printf_head "5" "           Single Repo Actions [userName]"
__printf_help "4" "$APPNAME_README single all         -  Push all repos in ~/Projects/*/[userName]/*"
__printf_help "4" "$APPNAME_README single init        -  gitadmin single init"
__printf_help "4" "$APPNAME_README single clone       -  Clone a repo [RemoteURL]"
__printf_help "4" "$APPNAME_README single push        -  Push your local repo to remote"
__printf_help "4" "$APPNAME_README single pull        -  Run git pull on repo"

__printf_head "5" "           Github User Repo Actions [userName/repo]"
__printf_help "4" "$APPNAME_README github init        -  gitadmin single init"
__printf_help "4" "$APPNAME_README github clone       -  Clone a repo [RemoteURL]"
__printf_help "4" "$APPNAME_README github push        -  Push your local repo to remote"
__printf_help "4" "$APPNAME_README github pull        -  Run git pull on repo"
__printf_help "4" "$APPNAME_README github remote      -  Add new remote url [userName/repoName]"

__printf_head "5" "           Gitlab User Repo Actions [userName/repo]"
__printf_help "4" "$APPNAME_README gitlab init        -  gitadmin single init"
__printf_help "4" "$APPNAME_README gitlab clone       -  Clone a repo [RemoteURL]"
__printf_help "4" "$APPNAME_README gitlab push        -  Push your local repo to remote"
__printf_help "4" "$APPNAME_README gitlab pull        -  Run git pull on repo"
__printf_help "4" "$APPNAME_README gitlab remote      -  Add new remote url [userName/repoName]"

__printf_head "5" "           Private User Repo Actions [userName/repo]"
__printf_help "4" "$APPNAME_README private init       -  gitadmin single init"
__printf_help "4" "$APPNAME_README private clone      -  Clone a repo [RemoteURL]"
__printf_help "4" "$APPNAME_README private push       -  Push your local repo to remote"
__printf_help "4" "$APPNAME_README private pull       -  Run git pull on repo"
__printf_help "4" "$APPNAME_README private remote     -  Add new remote url [userName/repoName]"

__printf_head "5" "           Gitub Issue Options [list,count,create,edit] [userName] [repoName]"
__printf_help "4" "$APPNAME_README issues count       -  Show how many issues exist"
__printf_help "4" "$APPNAME_README issues list        -  Show current github issues for current project"
__printf_help "4" "$APPNAME_README issues create      -  Create a new issue"
__printf_help "4" "$APPNAME_README issues edit        -  Edit a current issue"

__printf_head "5" "           This is a work in progress"
__printf_help "4" "$APPNAME_README cron               -  Autoupdate all repos using cron"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"
