#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="gitadmin"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  gitadmin --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  gitadmin
# @Description       :  Manual for gitadmin
# @TODO              :  Organize this a lot better
# @Other             :  Convert this to my bash system scripts
# @Resource          :  Somethings may be broken due to variable changes
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$gitadmin}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "gitadmin")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "gitadmin: push/clone/pull from github/gitlab/private repo"

__printf_head "6" "Usage gitadmin [directory] options arguments"
__printf_help "4" "gitadmin --user                                   - List user repos [userName]"
__printf_help "4" "gitadmin --org                                    - List organization repos [orgNAME]"
__printf_help "4" "gitadmin --single                                 - clone a single repo [repoURL]"

__printf_head "4" "gitadmin options"
__printf_help "4" "gitadmin shorten                                  - Shorten any github url [URL] [name]"
__printf_help "4" "gitadmin init                                     - Initialize current project into a git repo"
__printf_help "4" "gitadmin setup                                    - Initialize current project into a git repo"
__printf_help "4" "gitadmin stow                                     - Keep your dotfiles in a repo"
__printf_help "4" "gitadmin status                                   - Show repo status"
__printf_help "4" "gitadmin log                                      - Show the git log"
__printf_help "4" "gitadmin branch                                   - Rename the current branch"
__printf_help "4" "gitadmin commit                                   - Commit the current changes"
__printf_help "4" "gitadmin update                                   - Run git pull on all repos"
__printf_help "4" "gitadmin create                                   - Create a new github repo [userName repoName]"
__printf_help "4" "gitadmin delete                                   - Deletes a github repo [userName repoName]"
__printf_help "4" "gitadmin push                                     - Push a project to a remote repo"
__printf_help "4" "gitadmin pull                                     - Update a local git repo"
__printf_help "4" "gitadmin clone                                    - Clone a git repo [remoteURL] [localDIR]"
__printf_help "4" "gitadmin repos                                    - Show all your public repos [userName]"
__printf_help "4" "gitadmin newsite                                  - Create a site using template [siteName] [repo|GITADMIN_DOMAIN_TEMPLATE]"

__printf_head "5" "Remote Repo options [remoteURL]"
__printf_help "4" "gitadmin remote show                              - Show the current remote server "
__printf_help "4" "gitadmin remote add                               - Add new remote url [remoteURL]"

__printf_head "5" "Orginization options [userName]"
__printf_help "4" "gitadmin user                                     - Clone/Pull all repos owned by you"
__printf_help "4" "gitadmin user list                                - Clone/Pull all repos owned by you [userName]"

__printf_head "5" "Orginization options [userName]"
__printf_help "4" "gitadmin orgs all                                 - Clone/Pull all orgs owned by you [userName]"
__printf_help "4" "gitadmin orgs push                                - Push all your local repos to remote [userName]"
__printf_help "4" "gitadmin orgs pull                                - Update all your local repos from remote [userName]"
__printf_help "4" "gitadmin orgs clone                               - Clone a repo [userName]"

__printf_head "5" "Gitgub Gist options [userName]"
__printf_help "4" "gitadmin gist create                              - Create a new github gist [userName]"
__printf_help "4" "gitadmin gist delete                              - Delete a github gist [userName]"
__printf_help "4" "gitadmin gist edit                                - Edit github gist [userName]"
__printf_help "4" "gitadmin gist list                                - List github gists [userName]"
__printf_help "4" "gitadmin gist search                              - Search for github gist [userName]"

__printf_head "5" "Single single Actions [userName]"
__printf_help "4" "gitadmin single all                               - Push all repos in ~/Projects/*/[userName]/*"
__printf_help "4" "gitadmin single init                              - gitadmin single init"
__printf_help "4" "gitadmin single clone                             - Clone a repo [RemoteURL]"
__printf_help "4" "gitadmin single push                              - Push your local repo to remote"
__printf_help "4" "gitadmin single pull                              - Run git pull on repo"

__printf_head "5" "Github github Repo Actions [userName/repo]"
__printf_help "4" "gitadmin github init                              - gitadmin single init"
__printf_help "4" "gitadmin github clone                             - Clone a repo [RemoteURL]"
__printf_help "4" "gitadmin github push                              - Push your local repo to remote"
__printf_help "4" "gitadmin github pull                              - Run git pull on repo"
__printf_help "4" "gitadmin github remote                            - Add new remote url [userName/repoName]"

__printf_head "5" "Gitlab gitlab Repo Actions [userName/repo]"
__printf_help "4" "gitadmin gitlab init                              - gitadmin single init"
__printf_help "4" "gitadmin gitlab clone                             - Clone a repo [RemoteURL]"
__printf_help "4" "gitadmin gitlab push                              - Push your local repo to remote"
__printf_help "4" "gitadmin gitlab pull                              - Run git pull on repo"
__printf_help "4" "gitadmin gitlab remote                            - Add new remote url [userName/repoName]"

__printf_head "5" "Private private Repo Actions [userName/repo]"
__printf_help "4" "gitadmin private init                             - gitadmin single init"
__printf_help "4" "gitadmin private clone                            - Clone a repo [RemoteURL]"
__printf_help "4" "gitadmin private push                             - Push your local repo to remote"
__printf_help "4" "gitadmin private pull                             - Run git pull on repo"
__printf_help "4" "gitadmin private remote                           - Add new remote url [userName/repoName]"

__printf_head "5" "Gitub Issue Options [list,count,create,edit] [userName] [repoName]"
__printf_help "4" "gitadmin issues count                             - Show how many issues exist"
__printf_help "4" "gitadmin issues list                              - Show current github issues for current project"
__printf_help "4" "gitadmin issues create                            - Create a new issue"
__printf_help "4" "gitadmin issues edit                              - Edit a current issue"

__printf_head "5" "Other Options"
__printf_help "4" "gitadmin --config                                 - Generate user config file"
__printf_help "4" "gitadmin --version                                - Show script version"
__printf_help "4" "gitadmin --help                                   - Shows this message"
__printf_help "4" "gitadmin --options                                - Shows all available options"

__printf_head "5" "This is a work in progress"
__printf_help "4" "gitadmin cron                                     - Autoupdate all repos using cron"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
