#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="iconmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050000-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : iconmgr --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:00 EDT
# @File          : iconmgr
# @Description   : Manual for iconmgr
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$iconmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "iconmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "iconmgr: Install icons"
printf '\n'
__printf_help "4" "          A Package Manager for all systems   |   Usage: sudo iconmgr command"
__printf_help "4" "iconmgr version              - show the version info          | IE: iconmgr version N.I.B."
__printf_help "4" "iconmgr makecache            - update icon cache              | IE: iconmgr makecache"
__printf_help "4" "iconmgr list                 - list all installable icons     | IE: iconmgr list"
__printf_help "4" "iconmgr list-installed       - list installed icons           | IE: iconmgr list-installed"
__printf_help "4" "iconmgr search               - find icon                      | IE: iconmgr search icon"
__printf_help "4" "iconmgr search-installed     - search installed icons         | IE: iconmgr search-installed icon"
__printf_help "4" "iconmgr install              - install a icon                 | IE: iconmgr install icon"
__printf_help "4" "iconmgr remove               - remove a icon                  | IE: iconmgr remove icon"
__printf_help "4" "iconmgr update               - update the icons               | IE: iconmgr update"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

