#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This is what I use for my system scripts
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# REPLACE_THIS_WITH_HEADER_INFO
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
APPNAME_README="latest-iso"
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-systemmgr}")" | grep "${1:-}"; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__version() { __grep_head 'Version' "$(type -P "${2:-systemmgr}")" | __sed_head | head -n1 | grep '^'; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "$APPNAME_README: $(__grep_head "Description" "$APPNAME_README" | __sed_head)"
__printf_help " " ""
__printf_help "5" "Usage: $APPNAME_README [shortname,url] [filename] [options]"
__printf_help "4" "$APPNAME_README --all                             - Download all available ISOs"
__printf_help "4" "$APPNAME_README iso                               - Download iso from URL"
__printf_help "4" "$APPNAME_README alpinelinux                       - Download latest alpinelinux ISO"
__printf_help "4" "$APPNAME_README archolinux                        - Download latest archolinux ISO"
__printf_help "4" "$APPNAME_README debian                            - Download latest debian ISO"
__printf_help "4" "$APPNAME_README heads                             - Download latest heads ISO"
__printf_help "4" "$APPNAME_README kali                              - Download latest kali ISO"
__printf_help "4" "$APPNAME_README tails                             - Download latest tails ISO"
__printf_help "4" "$APPNAME_README parrot                            - Download latest parrotos ISO"
__printf_help "4" "$APPNAME_README peppermint                        - Download latest pepperment ISO"
__printf_help "4" "$APPNAME_README photon                            - Download latest photon ISO"
__printf_help "4" "$APPNAME_README tinylinux                         - Download latest tinylinux ISO"
__printf_help " " ""
__printf_head "5" "Other $APPNAME_README Options"
__printf_help "4" "$APPNAME_README --config                          - Generate user config file"
__printf_help "4" "$APPNAME_README --version                         - Show script version"
__printf_help "4" "$APPNAME_README --help                            - Shows this message"
__printf_help "4" "$APPNAME_README --options                         - Shows all available options"
__printf_help " " ""
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "$APPNAME_README "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
