#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="latest-releases"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050000-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : latest-releases --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:00 EDT
# @File          : latest-releases
# @Description   : Manual for latest-releases
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$latest-releases}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "latest-releases")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "latest-releases: Check github for the latest release"
printf '\n'
__printf_help "4" "Add these 2 lines to ${auth_path}, modify the values for your info and save it:"
__printf_help "4" 'export GITHUB_USERNAME="yourname" '
__printf_help "4" 'export GITHUB_PERSONAL_ACCESS_TOKEN="youraccesstoken" '
__printf_help "4" "Add your list of GitHub repos to ${github_path}."
__printf_help "4" "Separate out each entry on a new line and only include the owner/repo."
__printf_help "4" "Here's an example of what that file could look like:"
__printf_help "4" "pallets/flask"
__printf_help "4" "phoenixframework/phoenix"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

