#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="logr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050000-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : logr --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:00 EDT
# @File          : logr
# @Description   : Manual for logr
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$logr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "logr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "logr: A logging script"
printf '\n'
__printf_help "4" "A simple logging utility"
__printf_help "4" "Usage       : log mycommand"
__printf_help "4" "-name       : custom log name"
__printf_help "4" "--clean     : remove old logs"
__printf_help "4" "--show      : will show all output"
__printf_help "4" "--silent    : no output"
__printf_help "4" "--err       : show only error"
__printf_help "4" "--noerr     : hide error mesaages"
__printf_help "4" "--list      : list all logs"
__printf_help "4" "--open      : open logdir"
__printf_help "2" "Default logdir: $LOGDIR/logr"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

