#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="logr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108050000-git
# @Author            :  casjay
# @Contact           :  casjay
# @License           :  WTFPL
# @ReadME            :  logr --help
# @Copyright         :  Copyright: (c) 2021 casjay, casjay
# @Created           :  Thursday, Aug 05, 2021 00:00 EDT
# @File              :  logr
# @Description       :  Manual for logr
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$logr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "logr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
printf '\n'
__printf_head "5" "logr: A logging script"
__printf_help " " "                                                  "
__printf_help "5" "Usage: logr []"

__printf_help "4" "logr -name                                        - Custom log name"
__printf_help "4" "logr --clean                                      - Remove old logs"
__printf_help "4" "logr --show                                       - Will show all output"
__printf_help "4" "logr --silent                                     - No output"
__printf_help "4" "logr --err                                        - Show only error"
__printf_help "4" "logr --noerr                                      - Hide error mesaages"
__printf_help "4" "logr --list                                       - List all logs"
__printf_help "4" "logr --open                                       - Open logdir"

__printf_head "5" "Other logr Options"
__printf_help "4" "logr --config                                     - Generate user config file"
__printf_help "4" "logr --version                                    - Show script version"
__printf_help "4" "logr --help                                       - Shows this message"
__printf_help "4" "logr --options                                    - Shows all available options"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
