#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="metric2imperial"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  metric2imperial --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  metric2imperial
# @Description       :  Manual for metric2imperial
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$metric2imperial}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "metric2imperial")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "metric2imperial: convert Celcius to Fahrenheit"

__printf_help "5" "Usage: metric2imperial []"
__printf_help "4" "metric2imperial f                                 - Convert celcius to Fahrenheit"
__printf_help "4" "metric2imperial mm                                - Convert millimeter to inches"
__printf_help "4" "metric2imperial cm                                - Convert centimeter to inches"
__printf_help "4" "metric2imperial m                                 - Convert meter to feet"
__printf_help "4" "metric2imperial km                                - Convert kilometer to miles"

__printf_head "5" "Other Options"
__printf_help "4" "metric2imperial --config                          - Generate user config file"
__printf_help "4" "metric2imperial --version                         - Show script version"
__printf_help "4" "metric2imperial --help                            - Shows this message"
__printf_help "4" "metric2imperial --options                         - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "metric2imperial "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
