#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="multi_clipboard"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  multi_clipboard --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  multi_clipboard
# @Description       :  Manual for multi_clipboard
# @TODO              :
# @Other             :
# @Resource          :  https://github.com/rcmdnk/multi_clipboard
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$multi_clipboard}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "multi_clipboard")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "multi_clipboard: Utility to keep multiple clipboards"
__printf_help " " "                                                  "
__printf_help "5" "Usage: multi_clipboard []"
__printf_help "multi_clipboard -i [args]                             - Insert [args] to the clipboard list"
__printf_help "multi_clipboard -s [args]                             - Send [args] to the clipboard list and the screen's clipboard"
__printf_help "multi_clipboard -I                                    - Insert the screen's clipboard to the clipboard list"
__printf_help "multi_clipboard -o                                    - Open clipboard list, then select one, which will be placed"
__printf_help "multi_clipboard -O                                    - Same as -o, in addition, send it to the screen's clipboard"
__printf_help "multi_clipboard -g                                    - Get the first one in the clipboard list"
__printf_help "multi_clipboard -w                                    - w/o any other options Launch selection window and return the selected value"
__printf_help "multi_clipboard -W                                    - Similar as -w, but value to the screen's clipboard"
__printf_help "multi_clipboard -x                                    - Send the last clipboard to the clipboard of OS (X server)"
__printf_help "multi_clipboard -c                                    - Clean up clipboard file"
__printf_help "multi_clipboard -S                                    - Use in screen for selection mode"
__printf_help "multi_clipboard snippet                               - Use 'snippet' file instead of saved clipboards."
__printf_help " " "                                                  "
__printf_head "5" "Other Options"
__printf_help "4" "multi_clipboard --config                          - Generate user config file"
__printf_help "4" "multi_clipboard --version                         - Show script version"
__printf_help "4" "multi_clipboard --help                            - Shows this message"
__printf_help "4" "multi_clipboard --options                         - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "multi_clipboard "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
