#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="mydate"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  mydate --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  mydate
# @Description       :  Manual for mydate
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$mydate}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "mydate")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "mydate: Show date"
__printf_help " " "                                                  "
__printf_help "5" "Usage: mydate []"
__printf_help " " "                                                  "
__printf_help "4" "mydate nowtime                                    - Get current time"
__printf_help "4" "mydate nowdate                                    - Get current date"
__printf_help "4" "mydate setver                                     - Set version"
__printf_help "4" "mydate setverfile                                 - Out to ./version.txt"
__printf_help " " "                                                  "
__printf_head "5" "Other Options"
__printf_help "4" "mydate --config                                   - Generate user config file"
__printf_help "4" "mydate --version                                  - Show script version"
__printf_help "4" "mydate --help                                     - Shows this message"
__printf_help "4" "mydate --options                                  - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "mydate "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
