#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="myip"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  myip --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  myip
# @Description       :  Manual for myip
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$myip}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "myip")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "myip: Show IP address"
__printf_help " " "                                                  "
__printf_help "5" "Usage: myip []"
__printf_help "4" "myip                                              - Print current ip addresses"
__printf_help "4" "myip local                                        - Print current local ip address"
__printf_help "4" "myip public                                       - Print current public ip address"
__printf_help "4" "myip local 4                                      - Print current local ip 4 address"
__printf_help "4" "myip local 6                                      - Print current local ip 6 address"
__printf_help "4" "myip public 4                                     - Print current public ip 4 address"
__printf_help "4" "myip public 4                                     - Print current public ip 4 address"
__printf_help " " "                                                  "
__printf_head "5" "Other Options"
__printf_help "4" "myip --config                                     - Generate user config file"
__printf_help "4" "myip --version                                    - Show script version"
__printf_help "4" "myip --help                                       - Shows this message"
__printf_help "4" "myip --options                                    - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "myip "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
