#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="notes"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  notes --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  notes
# @Description       :  Manual for notes
# @TODO              :  Refactor code
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$notes}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "notes")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "notes: Take notes using bash"

__printf_head "5" "Usage: notes []"
__printf_help "4" "notes                                             - Opens your notes in vim"
__printf_help "4" "notes something you want to jot down              - Appends that text to the file"
__printf_help "4" "xclip -o | notes or notes -                       - Appends stdin to the file"

__printf_head "5" "Notes client usage                   "
__printf_help "4" "notes client                                      - used to send notes to the server - same syntax as notes"
__printf_help "4" "notes client message to send                      - Appends that text to the server file"
__printf_help "4" "xclip -o | notes client                           - Appends stdin to the server file"

__printf_head "5" "Notes server usage                   "
__printf_help "4" "notes server                                      - Run notes as a server using netcat"
__printf_help "4" "notes server open                                 - Open your notes on remote server"
__printf_help "4" "notes server open all                             - Open all your notes on remote server"
__printf_help "4" "notes server --status                             - Shows the current status of the server"
__printf_help "4" "notes server --kill                               - Initiates the kill to stop the server"

__printf_head "5" "Notes systemd server usage                   "
__printf_help "4" "notes service systemd                             - Systemd functions"
__printf_help "4" "notes service systemd install                     - Installs notes as a service using systemd"
__printf_help "4" "notes service systemd remove                      - Remove the notes systemd service"
__printf_help "4" "notes service systemd start                       - Start the notes systemd service"
__printf_help "4" "notes service systemd stop                        - Stop the notes systemd service"
__printf_help "4" "notes service systemd restart                     - Restart the notes systemd service"
__printf_help "4" "notes service systemd status                      - Get the notes systemd service status"
__printf_help "4" "notes service systemd run/vars                    - Used by systemd to run the notes server"

__printf_help "3" "All variables can be overwritten by editing the file ~/.config/notes/settings"

__printf_head "5" "Other Options"
__printf_help "4" "notes --config                                    - Generate user config file"
__printf_help "4" "notes --version                                   - Show script version"
__printf_help "4" "notes --help                                      - Shows this message"
__printf_help "4" "notes --options                                   - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "notes "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
