#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="passmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  passmgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  passmgr
# @Description       :  Manual for passmgr
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$passmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "passmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "passmgr: wrapper for the pass command"

__printf_help "5" "Usage: passmgr [options]"
__printf_help "4" "update                                - Update or install the passmgr script"
__printf_help "4" "init                                  - Initialize new password store"
__printf_help "4" "ls [subfolder]                        - List passwords."
__printf_help "4" "find pass-names...                    - List passwords that match pass-names."
__printf_help "4" "show pass-name                        - Show existing password and optionally put it on the clipboard."
__printf_help "4" "grep search-string                    - Search for password files containing search-string when decrypted."
__printf_help "4" "insert                                - Insert new password. Optionally, echo the password back to the console"
__printf_help "4" "edit pass-name                        - Insert a new password or edit an existing password using ${EDITOR:-vi}."
__printf_help "4" "generate                              - Generate a new password."
__printf_help "4" "rm                                    - Remove existing password."
__printf_help "4" "mv                                    - Renames or moves old-path to new-path."
__printf_help "4" "cp                                    - Copies old-path to new-path."
__printf_help "4" "git                                   - If the password store is a git repository, execute a git command"

__printf_head "5" "Other passmgr Options"
__printf_help "4" "passmgr --config                      - Generate user config file"
__printf_help "4" "passmgr --version                     - Show script version"
__printf_help "4" "passmgr --help                        - Shows this message"
__printf_help "4" "passmgr --options                     - Shows all available options"
__printf_help " " "                                      "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "passmgr "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
