#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="pb"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108121904-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : pb --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Aug 12, 2021 19:04 EDT
# @File          : pb
# @Description   : Manual for pb
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$pb}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "pb")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "pb: Send output to a pastebin"
__printf_help " " "                                                  "
__printf_help "5" "Usage: pb []"
__printf_help "4" " "
__printf_help "4" "services: 0x0.st, catbox.moe, clbin.com, dmca.gripe, dumpz.org, fiery.me,"
__printf_help "4" "ix.io, p.iotek.org, pastebin.com, sprunge.us, uguu.se, w1r3.net"
__printf_help "4" " "
__printf_help "4" "examples:"
__printf_help "4" "   pb ix ~/.vimrc"
__printf_help "4" "   pb 0x0 <(ps aux)"
__printf_help "4" "   dmesg | pb iop"
__printf_help "4" "   PB_API_DEV=XXXX PRIVACY=0 pb pb /tmp/leak.txt"
__printf_help " " "                                                  "
__printf_head "5" "Other pb Options"
__printf_help "4" "pb --config                                      - Generate user config file"
__printf_help "4" "pb --version                                     - Show script version"
__printf_help "4" "pb --help                                        - Shows this message"
__printf_help "4" "pb --options                                         - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "pb "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
