#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="pb"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050001-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : pb --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:01 EDT
# @File          : pb
# @Description   : Manual for pb
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$pb}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "pb")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "pb: Send output to a pastebin"
printf '\n'
__printf_help "4" "pb; a command line pastebin service helper"
__printf_help "4" "usage: pb <service> [file|stream]"
__printf_help "4" " "
__printf_help "4" "services:"
__printf_help "4" "   0x0.st, catbox.moe, clbin.com, dmca.gripe,"
__printf_help "4" "   dumpz.org, fiery.me, ix.io, p.iotek.org,"
__printf_help "4" "   pastebin.com, sprunge.us, uguu.se, w1r3.net"
__printf_help "4" ""
__printf_help "4" "environment variables:"
__printf_help "4" "   UA: user-agent string (defaults to some chrome one)"
__printf_help "4" " "
__printf_help "4" "envs for pastebin.com:"
__printf_help "4" "   PB_API_DEV: developer api key [required] https://pastebin.com/api#1"
__printf_help "4" "   PB_API_USR: user api key [optional] https://pastebin.com/api#8"
__printf_help "4" "   PRIVACY: paste visibility  [optional] valid values: public|0, unlisted|1, private|2"
__printf_help "4" "   ANON: paste w/o a user key even if defined [optional]"
__printf_help "4" " "
__printf_help "4" "examples:"
__printf_help "4" "   pb ix ~/.vimrc"
__printf_help "4" "   pb 0x0 <(ps aux)"
__printf_help "4" "   dmesg | pb iop"
__printf_help "4" "   PB_API_DEV=XXXX PRIVACY=0 pb pb /tmp/leak.txt"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

