#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="pkmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050001-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : pkmgr --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:01 EDT
# @File          : pkmgr
# @Description   : Manual for pkmgr
# @TODO          : Refactor code/Add zenity support/Add user conf file
# @Other         : Add BSD support
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$pkmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "pkmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "pkmgr: Manage system packages"
printf '\n'
__printf_help "4" '                A Package Manager for most systems'
__printf_help "4" 'pkmgr dotfiles      - install required packages     | IE: pkmgr dotfiles git'
__printf_help "4" 'pkmgr list          - install from a file           | IE: pkmgr list [full path to list]'
__printf_help "4" 'pkmgr curl          - install from a url            | IE: pkmgr curl debian min [ See '$REPO' for details]'
__printf_help "4" 'pkmgr script        - run a script                  | IE: pkmgr script [ ./pathToScript or http://fullurltoscript ]'
__printf_help "4" 'pkmgr search        - find a package                | IE: pkmgr search myapp'
__printf_help "4" 'pkmgr install       - install a package             | IE: pkmgr install myapp'
__printf_help "4" 'pkmgr remove        - remove a package              | IE: pkmgr remove myapp'
__printf_help "4" 'pkmgr update        - update all packages           | IE: pkmgr update'
__printf_help "4" 'pkmgr clean         - Removes cached files          | IE: pkmgr clean'
__printf_help "4" 'pkmgr makecache     - update package lists          | IE: pkmgr makecache'
__printf_help "4" 'pkmgr silent        - silently install package      | IE: pkmgr silent myapp'
__printf_help "4" 'pkmgr silent-remove - silently remove package       | IE: pkmgr silent-remove myapp'
__printf_help "4" 'pkmgr cron add      - schedule daily updates        | IE: pkmgr cron add'
__printf_help "4" 'pkmgr aliases       - lists the alias for bash      | IE: pkmgr alias'
__printf_help "4" 'pkmgr pip           - install a python package      | IE: pkmgr pip requests'
__printf_help "4" 'pkmgr cpan          - install a perl module         | IE: pkmgr cpan Bundle::Apache'
__printf_help "4" 'pkmgr gem           - install a gem module          | IE: pkmgr gem jekyll'
__printf_help "4" 'pkmgr npm           - install a nodejs module       | IE: pkmgr npm express'
__printf_help "4" 'pkmgr cmd --help    - show help for the command     | IE: pkmgr aliases --help'
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

