#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="pkmgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  pkmgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  pkmgr
# @Description       :  Manual for pkmgr
# @TODO              :  Refactor code/Add zenity support/Add user conf file
# @Other             :  Add BSD support
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$pkmgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "pkmgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "pkmgr: Manage system packages"

__printf_help "5" "Usage: pkmgr []"

__printf_help "4" 'A Package Manager for most systems'
__printf_help "4" 'pkmgr dotfiles                                    - install required packages    |pkmgr dotfiles git'
__printf_help "4" 'pkmgr list                                        - install from a file          |pkmgr list [full path to list]'
__printf_help "4" 'pkmgr curl                                        - install from a url           |pkmgr curl debian min [ See '$REPO' for details]'
__printf_help "4" 'pkmgr script                                      - run a script                 |pkmgr script [ ./pathToScript or http://fullurltoscript ]'
__printf_help "4" 'pkmgr search                                      - find a package               |pkmgr search myapp'
__printf_help "4" 'pkmgr install                                     - install a package            |pkmgr install myapp'
__printf_help "4" 'pkmgr remove                                      - remove a package             |pkmgr remove myapp'
__printf_help "4" 'pkmgr update                                      - update all packages          |pkmgr update'
__printf_help "4" 'pkmgr clean                                       - Removes cached files         |pkmgr clean'
__printf_help "4" 'pkmgr makecache                                   - update package lists         |pkmgr makecache'
__printf_help "4" 'pkmgr silent                                      - silently install package     |pkmgr silent myapp'
__printf_help "4" 'pkmgr silent remove                               - silently remove package      |pkmgr silent remove myapp'
__printf_help "4" 'pkmgr silent upgrade                              - silently upgrade package     |pkmgr silent upgrade myapp'
__printf_help "4" 'pkmgr cron add                                    - schedule daily updates       |pkmgr cron add'
__printf_help "4" 'pkmgr aliases                                     - lists the alias for bash     |pkmgr alias'
__printf_help "4" 'pkmgr pip                                         - install a python package     |pkmgr pip requests'
__printf_help "4" 'pkmgr cpan                                        - install a perl module        |pkmgr cpan Bundle::Apache'
__printf_help "4" 'pkmgr gem                                         - install a gem module         |pkmgr gem jekyll'
__printf_help "4" 'pkmgr npm                                         - install a nodejs module      |pkmgr npm express'
__printf_help "4" 'pkmgr cmd --help                                  - show help for the command    |pkmgr aliases --help'
__printf_head "5" "Other Options"
__printf_help "4" "pkmgr --config                                    - Generate user config file"
__printf_help "4" "pkmgr --version                                   - Show script version"
__printf_help "4" "pkmgr --help                                      - Shows this message"
__printf_help "4" "pkmgr --options                                   - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "pkmgr "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
