#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202111162147-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  LICENSE.md
# @ReadME            :  publishit --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Dec 09, 2021 20:50 EST
# @File              :  publishit
# @Description       :  Publish things
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
APPNAME_README="publishit"
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_remove_empty() { sed '/^\#/d;/^$/d;s#^ ##g'; }
__sed_head_remove() { awk -F'  :' '{print $2}'; }
__sed_head() { sed -E 's|^.*#||g;s#^ ##g;s|^@||g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "${2:-$command}" | grep "${1:-}" | head -n 12 | __sed_head | __sed_remove_empty | grep '^' || return 1; }
__grep_head_remove() { grep -shE '[".#]?@[A-Z]' "${2:-$command}" | grep "${1:-}" | grep -Ev 'GEN_SCRIPT_*|\${|\$\(' | sed_head_remove | sed '/^\#/d;/^$/d;s#^ ##g' | grep '^' || return 1; }
__grep_version() { grep_head ''${1:-Version}'' "${2:-$command}" | __sed_head | __sed_head_remove | __sed_remove_empty | head -n1 | grep '^'; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_help() {
  printf "%b" "$(tput setaf "${2:-4}" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"
  printf '\n'
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# begin
__printf_head "5" "publishit: $(__grep_head "Description" "${publishit:-publishit help}" | __sed_head)"
__printf_help " " "                                                  "
__printf_help "5" "Usage: publishit [docker, npm]"
__printf_help "4" "  - "
__printf_help " " "                                                  "
__printf_head "5" "Other publishit Options"
__printf_help "4" "publishit --config                                      - Generate user config file"
__printf_help "4" "publishit --version                                     - Show script version"
__printf_help "4" "publishit --help                                        - Shows this message"
__printf_help "4" "publishit --options                                         - Shows all available options"
__printf_help " " "                                                  "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit ${exitCode:-0}
