#!/usr/bin/env bash
#----------------
printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  printf_color "\t\t$msg\n" "$color"
}
#----------------
printf_help "4" "Start an HTTP server from a directory"
printf_help "4" "Usage: run_server directory type port"
printf_help "4" "run_server . proxy 3000 20000   -  Requires caddy"
printf_help "4" "run_server . static 20000       -  Requires caddy/gohttpserver"
printf_help "4" "run_server . caddy 20000        -  Requires caddy"
printf_help "4" "run_server . go 20000           -  Requires gohttpserver"
printf_help "4" "run_server . jekyll 20000       -  Requires jekyll"
printf_help "4" "run_server . js 20000           -  Requires node"
printf_help "4" "run_server . php 20000          -  Requires php"
printf_help "4" "run_server . ruby 20000         -  Requires ruby"
printf_help "4" "run_server . python3 20000      -  Requires python3"
printf_help "4" "run_server . python2 20000      -  Requires python2"
printf_help "4" "run_server . netcat 20000       -  Requires netcat"
printf_help "4" "run_server . default 20000      -  Requires python"
printf_help "4" "TODO: add more languages such as lua"
