#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="run_server"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  run_server --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  run_server
# @Description       :  Manual for run_server
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$run_server}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "run_server")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "run_server: Start an HTTP server from a directory"

__printf_help "5" "Usage: run_server [dir app port]"
__printf_help "4" "run_server proxy 3000 20000                       - Requires caddy"
__printf_help "4" "run_server caddy 20000                            - Requires caddy"
__printf_help "4" "run_server static 20000                           - Requires gohttpserver"
__printf_help "4" "run_server go 20000                               - Requires gohttpserver"
__printf_help "4" "run_server jekyll 20000                           - Requires jekyll"
__printf_help "4" "run_server js 20000                               - Requires node"
__printf_help "4" "run_server php 20000                              - Requires php"
__printf_help "4" "run_server ruby 20000                             - Requires ruby"
__printf_help "4" "run_server python3 20000                          - Requires python3"
__printf_help "4" "run_server python2 20000                          - Requires python2"
__printf_help "4" "run_server netcat 20000                           - Requires netcat"
__printf_help "4" "run_server default 20000                          - Requires python"
__printf_help "4" "TODO: add more languages such as lua"

__printf_head "5" "Other run_server Options"
__printf_help "4" "run_server --config                               - Generate user config file"
__printf_help "4" "run_server --version                              - Show script version"
__printf_help "4" "run_server --help                                 - Shows this message"
__printf_help "4" "run_server --options                              - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "run_server "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
