#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="run_server"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050002-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : run_server --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:02 EDT
# @File          : run_server
# @Description   : Manual for run_server
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$run_server}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "run_server")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "run_server: Start an HTTP server from a directory"
printf '\n'
__printf_help "4" "Start an HTTP server from a directory"
__printf_help "4" "Usage: run_server directory type port"
__printf_help "4" "run_server . proxy 3000 20000   -  Requires caddy"
__printf_help "4" "run_server . static 20000       -  Requires caddy/gohttpserver"
__printf_help "4" "run_server . caddy 20000        -  Requires caddy"
__printf_help "4" "run_server . go 20000           -  Requires gohttpserver"
__printf_help "4" "run_server . jekyll 20000       -  Requires jekyll"
__printf_help "4" "run_server . js 20000           -  Requires node"
__printf_help "4" "run_server . php 20000          -  Requires php"
__printf_help "4" "run_server . ruby 20000         -  Requires ruby"
__printf_help "4" "run_server . python3 20000      -  Requires python3"
__printf_help "4" "run_server . python2 20000      -  Requires python2"
__printf_help "4" "run_server . netcat 20000       -  Requires netcat"
__printf_help "4" "run_server . default 20000      -  Requires python"
__printf_help "4" "TODO: add more languages such as lua"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

