#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="se"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108121904-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : se --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Aug 12, 2021 19:04 EDT
# @File          : se
# @Description   : Manual for se
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$se}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "se")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "se: a bash file explorer"
__printf_help " " "                                                  "
__printf_help "5" "Usage: se []"
__printf_help "4" "-a                                                - Show hidden files/directories."
__printf_help "4" "-r                                                - Show file content in the right."
__printf_help "4" "-u                                                - Show file content under the list."
__printf_help "4" "-d                                                - Show content of the directory."
__printf_help "4" "-D                                                - Do not show content of the directory."
__printf_help "4" "-n                                                - No preview."
__printf_help "4" "-C                                                - No confirmation at deletion."
__printf_help "4" "-h                                                - print this help and exit."
__printf_help " " "                                                  "
__printf_head "5" "Other se Options"
__printf_help "4" "se --config                                   - Generate user config file"
__printf_help "4" "se --version                                  - Show script version"
__printf_help "4" "se --help                                     - Shows this message"
__printf_help "4" "se --options                                      - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "se "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
