#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="ss_screenkey"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  ss_screenkey --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  ss_screenkey
# @Description       :  Manual for ss_screenkey
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$ss_screenkey}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "ss_screenkey")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "ss_screenkey: screenkey wrapper"

__printf_help "5" "Usage: ss_screenkey []"
__printf_help "4" "ss_screenkey -d, --debug                          - enable debugging"
__printf_help "4" "ss_screenkey --no-systray                         - do not create system tray icon"
__printf_help "4" "ss_screenkey -t TIMEOUT                           - timeout in seconds"
__printf_help "4" "ss_screenkey -p                                   - set vertical position"
__printf_help "4" "ss_screenkey --persist                            - make window persistent"
__printf_help "4" "ss_screenkey -s                                   - set font size"
__printf_help "4" "ss_screenkey -g GEOMETRY                          - set fixed area/window geometry"
__printf_help "4" "ss_screenkey --key-mode                           - set key processing mode"
__printf_help "4" "ss_screenkey --bak-mode                           - backspace processing mode"
__printf_help "4" "ss_screenkey --mods-mode                          - {normal,emacs,mac,win,tux}"
__printf_help "4" "ss_screenkey -m, --mods-only                      - show only keys with modifiers pressed"
__printf_help "4" "ss_screenkey --multiline                          - span text over multiple lines"
__printf_help "4" "ss_screenkey --vis-shift                          - always show Shift when modifiers are pressed"
__printf_help "4" "ss_screenkey --no-whitespace                      - disable visualization of whitespace"
__printf_help "4" "ss_screenkey --show-settings                      - show settings dialog on start"
__printf_help "4" "ss_screenkey --scr SCREEN                         - show on the specified screen number"
__printf_help "4" "ss_screenkey -f FONT_DESC                         - set font family/weight"
__printf_help "4" "ss_screenkey --font-color                         - set font color"
__printf_help "4" "ss_screenkey --bg-color BG_COLOR                  - background color"
__printf_help "4" "ss_screenkey --opacity OPACITY                    - window opacity (in range 0.0-1.0)"
__printf_help "4" "ss_screenkey --ignore KeySym                      - Ignore the specified KeySym"
__printf_help "4" "ss_screenkey --compr-cnt COUNT                    - Compress key repeats after the specified count"
__printf_help "4" "ss_screenkey --start-disabled                     - do not display anything until explicitly requested"
__printf_help "4" "ss_screenkey --version                            - show version of screenkey"
__printf_help "4" "ss_screenkey -M, --mouse                          - show the mouse buttons"

__printf_head "5" "Other Options"
__printf_help "4" "ss_screenkey --config                             - Generate user config file"
__printf_help "4" "ss_screenkey --version                            - Show script version"
__printf_help "4" "ss_screenkey --help                               - Shows this message"
__printf_help "4" "ss_screenkey --options                            - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "ss_screenkey "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
