#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="sshto"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050002-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : sshto --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:02 EDT
# @File          : sshto
# @Description   : Manual for sshto
# @TODO          : 
# @Other         : 
# @Resource      : https://github.com/vaniacer/sshto
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$sshto}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "sshto")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "sshto: Menu driven ssh client"
printf '\n'
__printf_help "4" "Username       |    Change ssh username to 'GUEST"
__printf_help "4" "ls   -la       |    List Files"
__printf_help "4" "free -h        |    Show free memory"
__printf_help "4" "df   -ih       |    Show free inodes"
__printf_help "4" "df   -h        |    Show free disk space"
__printf_help "4" "Info           |    Full system info"
__printf_help "4" "Sshkey         |    Add my ssh key to 'target'"
__printf_help "4" "Alias          |    Add my usefull aliases to 'target'"
__printf_help "4" "Copy           |    Copy selected file or dir to 'target'"
__printf_help "4" "Dest           |    Change destination folder 'DEST' on 'target'"
__printf_help "4" "Upload         |    Upload file or folder from 'PWD' to 'target: '{DEST}'"
__printf_help "4" "Download       |    Download file or folder from 'target:' '{DEST} to 'PWD'"
__printf_help "4" "Local          |    Change local port 'LOCAL'"
__printf_help "4" "Remote         |    Change remote port 'REMOTE'"
__printf_help "4" "Tunnel         |    Start portunneling from target port REMOTE to local port LOCAL"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

