#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="sshto"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121904-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  sshto --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:04 EDT
# @File              :  sshto
# @Description       :  Manual for sshto
# @TODO              :
# @Other             :
# @Resource          :  https://github.com/vaniacer/sshto
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$sshto}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "sshto")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '\n'
__printf_head "5" "sshto: Menu driven ssh client"

__printf_help "5" "Usage: sshto []"
__printf_head "5" "sshto: Menu driven ssh client"
__printf_help "4" "Username                                          - Change ssh username to 'GUEST"
__printf_help "4" "ls   -la                                          - List Files"
__printf_help "4" "free -h                                           - Show free memory"
__printf_help "4" "df   -ih                                          - Show free inodes"
__printf_help "4" "df   -h                                           - Show free disk space"
__printf_help "4" "Info                                              - Full system info"
__printf_help "4" "Sshkey                                            - Add my ssh key to 'target'"
__printf_help "4" "Alias                                             - Add my usefull aliases to 'target'"
__printf_help "4" "Copy                                              - Copy selected file or dir to 'target'"
__printf_help "4" "Dest                                              - Change destination folder 'DEST' on 'target'"
__printf_help "4" "Upload                                            - Upload file or folder from 'PWD' to 'target: '{DEST}'"
__printf_help "4" "Download                                          - Download file or folder from 'target:' '{DEST} to 'PWD'"
__printf_help "4" "Local                                             - Change local port 'LOCAL'"
__printf_help "4" "Remote                                            - Change remote port 'REMOTE'"
__printf_help "4" "Tunnel                                            - Start portunneling from target port REMOTE to local port LOCAL"

__printf_head "5" "Other sshto Options"
__printf_help "4" "sshto --config                                    - Generate user config file"
__printf_help "4" "sshto --version                                   - Show script version"
__printf_help "4" "sshto --help                                      - Shows this message"
__printf_help "4" "sshto --options                                   - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "sshto "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
