#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="wallpapermgr"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108050003-git
# @Author        : casjay
# @Contact       : casjay
# @License       : WTFPL
# @ReadME        : wallpapermgr --help
# @Copyright     : Copyright: (c) 2021 casjay, casjay
# @Created       : Thursday, Aug 05, 2021 00:03 EDT
# @File          : wallpapermgr
# @Description   : Manual for wallpapermgr
# @TODO          : Refactor Code
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -sE '[".#]?@[A-Z]' "$(type -P "${2:-$wallpapermgr}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "wallpapermgr")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n\t\t$__heading\n\t\t$2\n\t\t$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "\t\t$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
__printf_head "5" "wallpapermgr: Wallpaper installer and manager"
printf '\n'
__printf_help "4" "              A Wallpaper Manager for all systems   |   Usage: wallpapermgr command"
__printf_help "4" "wallpapermgr version              - show the version info           | IE: wallpapermgr version casjay"
__printf_help "4" "wallpapermgr remove               - remove wallpaper pack           | IE: wallpapermgr remove casjay"
__printf_help "4" "wallpapermgr install              - install wallpaper pack          | IE: wallpapermgr install dwt1"
__printf_help "4" "wallpapermgr update               - update wallpaper pack           | IE: wallpapermgr update"
__printf_help "4" " -  "
__printf_help "4" "-c, --config            - generate user config file"
__printf_help "4" "-v, --version           - show script version"
__printf_help "4" "-h, --help              - Shows this message"
__printf_help "4" "--options               - files used for completion"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit "${exitCode:-0}"

