#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME_README="weather"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108050003-git
# @Author            :  casjay
# @Contact           :  casjay
# @License           :  WTFPL
# @ReadME            :  weather --help
# @Copyright         :  Copyright: (c) 2021 casjay, casjay
# @Created           :  Thursday, Aug 05, 2021 00:03 EDT
# @File              :  weather
# @Description       :  Manual for weather
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
__heading="- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__sed_head() { sed 's#..* :##g;s#^ ##g'; }
__grep_head() { grep -shE '[".#]?@[A-Z]' "$(type -P "${2:-$weather}")" | grep "${1:-}"; }
__version() { __grep_head 'Version' "$(type -P "weather")" | __sed_head | head -n1 | grep '^'; }
__printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
__printf_head() { __printf_color "\n$__heading\n$2\n$__heading\n" "$1"; }
__printf_help() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="4"
  local msg="$*"
  shift
  __printf_color "$msg\n" "$color"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Begin help
printf '\n'
__printf_head "5" "weather: weather in your console"

__printf_help "5" "Usage: weather []"
__printf_help "4" "weather city                                      - Weather report for city"
__printf_help "4" "weather v2                                        - Version 2 of wttr.in"
__printf_help "4" "weather img                                       - Create an image file"
__printf_help "4" "weather moon                                      - Get moon phase"
__printf_help "4" "weather :help                                     - See all options"

__printf_head "5" "Other Options"
__printf_help "4" "weather --config                                  - Generate user config file"
__printf_help "4" "weather --version                                 - Show script version"
__printf_help "4" "weather --help                                    - Shows this message"
__printf_help "4" "weather --options                                 - Shows all available options"
__printf_help " " "                                                  "
#__printf_head "5" "This is a work in progress"
#__printf_help "4" "weather "
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end help
printf '\n'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
#exit "${exitCode:-0}"
