#!/usr/bin/env fish
# shellcheck shell=fish
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  GEN_SCRIPT_REPLACE_VERSION
# @@Author           :  GEN_SCRIPT_REPLACE_AUTHOR
# @@Contact          :  GEN_SCRIPT_REPLACE_EMAIL
# @@License          :  GEN_SCRIPT_REPLACE_LICENSE
# @@ReadME           :  GEN_SCRIPT_REPLACE_FILENAME --help
# @@Copyright        :  GEN_SCRIPT_REPLACE_COPYRIGHT
# @@Created          :  GEN_SCRIPT_REPLACE_DATE
# @@File             :  GEN_SCRIPT_REPLACE_FILENAME
# @@Description      :  GEN_SCRIPT_REPLACE_DESC
# @@Changelog        :  GEN_SCRIPT_REPLACE_CHANGELOG
# @@TODO             :  GEN_SCRIPT_REPLACE_TODO
# @@Other            :  GEN_SCRIPT_REPLACE_OTHER
# @@Resource         :  GEN_SCRIPT_REPLACE_RES
# @@Terminal App     :  GEN_SCRIPT_REPLACE_TERMINAL
# @@sudo/root        :  GEN_SCRIPT_REPLACE_SUDO
# @@Template         :  shell/fish
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# shellcheck disable=SC2317
# shellcheck disable=SC2120
# shellcheck disable=SC2155
# shellcheck disable=SC2199
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# script variables
set -g APPNAME (basename (status filename))
set -g VERSION GEN_SCRIPT_REPLACE_VERSION
set -g GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS 0
set -g GEN_SCRIPT_REPLACE_ENV_CWD (realpath "$PWD")
set -g SET_UID (id -u)
set -g SCRIPT_SRC_DIR (cd (dirname (status filename)); and pwd)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
# "output" "number"
if [ "$SHOW_RAW" != true ]
    function __printf_color -d 'print output'
        test $argv[2] && set -l color $argv[2] || set -l color 254
        printf "%b" "$(tput setaf $color 2>/dev/null)" "$argv[1]\n" "$(tput sgr0 2>/dev/null)"
    end
else # Disable colorization
    function __printf_color -d 'print output'
        printf "%b" "$argv[1]\n" | tr -d '\t' | sed '/^%b$/d;s,\x1B\[ 0-9;]*[a-zA-Z],,g'
    end
end
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Define Variables

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Main application
__printf_color "User ID: $SET_UID"
__printf_color "User Name: $RUN_USER" 3
__printf_color "Script Name: $APPNAME" 4
__printf_color "Version: $VERSION" 5
__printf_color "Current Working directory: $GEN_SCRIPT_REPLACE_ENV_CWD" 6
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit $GEN_SCRIPT_REPLACE_ENV_EXIT_STATUS
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ex: ts=2 sw=2 et filetype=sh
