version: '3.8'

services:
  almalinux:
    build:
      context: ..
      dockerfile: containers/Dockerfile
    image: casjaysdev/scripts:almalinux
    container_name: casjaysdev-scripts-almalinux
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'Container is healthy'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - scripts-network

  alpine:
    build:
      context: ..
      dockerfile: containers/Dockerfile.alpine
    image: casjaysdev/scripts:alpine
    container_name: casjaysdev-scripts-alpine
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'Container is healthy'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - scripts-network

networks:
  scripts-network:
    driver: bridge
