#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  GEN_SCRIPT_REPLACE_VERSION
# @@Author           :  GEN_SCRIPT_REPLACE_AUTHOR
# @@Contact          :  GEN_SCRIPT_REPLACE_EMAIL
# @@License          :  GEN_SCRIPT_REPLACE_LICENSE
# @@ReadME           :  GEN_SCRIPT_REPLACE_FILENAME --help
# @@Copyright        :  GEN_SCRIPT_REPLACE_COPYRIGHT
# @@Created          :  GEN_SCRIPT_REPLACE_DATE
# @@File             :  GEN_SCRIPT_REPLACE_FILENAME
# @@Description      :  GEN_SCRIPT_REPLACE_DESC
# @@Changelog        :  GEN_SCRIPT_REPLACE_CHANGELOG
# @@TODO             :  GEN_SCRIPT_REPLACE_TODO
# @@Other            :  GEN_SCRIPT_REPLACE_OTHER
# @@Resource         :  GEN_SCRIPT_REPLACE_RES
# @@sudo/root        :  no
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="$(basename "$0" 2>/dev/null)" # Set build name
VERSION="GEN_SCRIPT_REPLACE_VERSION"   # Set version
USER="${SUDO_USER:-${USER}}"           # Set username
HOME="${USER_HOME:-${HOME}}"           # Set home Directory
SRC_DIR="${BASH_SOURCE%/*}"            # Set the dir to script
PATH="${PATH//:./}"                    # Remove . from path
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set bash options
if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
trap 'exitCode=${exitCode:-$?};[ -n "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" ] && [ -f "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" ] && rm -Rf "$GEN_SCRIPT_REPLACE_ENV_TEMP_FILE" |&__devnull;exit ${exitCode:-$?}' EXIT
[[ "$1" == "--raw" ]] && export SHOW_RAW="true" && __printf_color() { printf '%s\n' "$1" | tr -d '\t\t' | sed '/^%b$/d;s,\x1B\[[0-9;]*[a-zA-Z],,g'; }
set -Eo pipefail
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__devnull() { tee &>/dev/null; }
__devnull2() { eval "$*" 2>/dev/null; }
__logr() { eval "$*" |& tee -a "${LOGFILE:-$GEN_SCRIPT_REPLACE_ENV_LOG_DIR/$APPNAME.log}" |& __devnull; }
__cmd_exist() { command -v "$1" |& __devnull || return 1; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# colorization
[ -n "$SHOW_RAW" ] || __printf_color() { echo -e '\t\t'${2:-}"${1:-}${NC}"; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# output version
__version() { echo -e '\t\t'${GREEN:-}"$VERSION"${NC:-}; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# send notifications
__notifications() {
  [[ -n "$DISPLAY" ]] && [[ -z "$SSH_CONNECTION" ]] &&
    __cmd_exist notifications &>/dev/null && notifications "$@" || echo "$*"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf_readline() {
  local color="$1"
  set -o pipefail
  while read line; do
    __printf_color "$line" "${color:-$WHITE}"
  done |& tee
  set +o pipefail
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__help() {
  [[ -z "$ARRAY" ]] || local array="[${ARRAY//,/ }]"
  [[ -z "$LONGOPTS" ]] || local opts="[--${LONGOPTS//,/ --}]"
  __printf_color "Usage: $APPNAME $opts $array" "$BLUE"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Setup build function
__make_build() {
  local exitCode=1
  local exitCode_make="0"
  local exitCode_cmake="0"
  local exitCode_configure="0"
  if [[ -f "$BUILD_SRC_DIR/CMakeLists.txt" ]]; then
    mkdir -p "$BUILD_SRC_DIR/build" && cd "$BUILD_SRC_DIR/build" || exit 10
    cmake .. 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
    make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
    sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
    exitCode_cmake="$?"
  elif [[ -f "$BUILD_SRC_DIR/configure" ]]; then
    __printf_color "Running configure" "$GREEN"
    make clean 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
    ./configure \
      --prefix="$BUILD_DESTDIR" \
      --with-lx \
      --with-pmenu 2>&1 |
      tee -a "$BUILD_LOG_FILE" |& __devnull
    exitCode_configure="$?"
    if [[ -f "$BUILD_SRC_DIR/Makefile" ]]; then
      __printf_color "Running make" "$GREEN"
      make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
      sudo make 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull &&
        sudo make install
      exitCode_make="$?"
    fi
  elif [[ -f "$BUILD_SRC_DIR/Makefile" ]]; then
    __printf_color "Running make" "$GREEN"
    make clean 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
    make -j$(nproc) 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull || exitCode+=1
    sudo make install DESTDIR="$BUILD_DESTDIR" 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
    exitCode_make="$?"
  fi
  if [[ "$exitCode_configure" = 0 ]] && [[ "$exitCode_make" = 0 ]] && [[ "$exitCode_cmake" = 0 ]]; then
    exitCode=0
  else
    __printf_color "Building $BUILD_NAME has failed" "$RED"
    exit 9
  fi
  return "${exitCode:-$?}"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
# Set main functions
__run_git() {
  if [[ -d ".git" ]]; then
    __printf_color "Updating the git repo" "$CYAN"
    git reset --hard 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull &&
      git pull 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
    if [[ $? = 0 ]]; then
      return 0
    else
      __printf_color "Failed to update: $BUILD_SRC_DIR" "$RED"
      exit 1
    fi
  elif [[ -n "$BUILD_SRC_URL" ]]; then
    __printf_color "Cloning the git repo to: $BUILD_SRC_DIR" "$CYAN"
    git clone "$BUILD_SRC_URL" "$BUILD_SRC_DIR" 2>&1 | tee -a "$BUILD_LOG_FILE" |& __devnull
    if [[ $? = 0 ]]; then
      return 0
    else
      __printf_color "Failed to clone: $BUILD_SRC_URL" "$RED"
      exit 1
    fi
  fi
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__check_log() {
  local exitCode="$?"
  if [[ -f "$BUILD_LOG_FILE" ]]; then
    errors="$(grep -i 'fatal error' "$BUILD_LOG_FILE" || echo '')"
    warnings="$(grep -i 'warning: ' "$BUILD_LOG_FILE" || echo '')"
    if [[ -n "$warnings" ]]; then
      __printf_color "The following warnings have occurred:" "$RED"
      echo -e "$warnings" |& printf_readline
      __printf_color "Log file saved to $BUILD_LOG_FILE" "$YELLOW"
      exitCode=0
    fi
    if [[ -n "$errors" ]] || [[ "$exitCode" -ne 0 ]]; then
      __printf_color "The following errors have occurred:" "$RED"
      echo -e "$errors" |& printf_readline
      __printf_color "Log file saved to $BUILD_LOG_FILE" "$YELLOW"
      exitCode=1
    else
      rm -Rf "$BUILD_LOG_FILE" |& __devnull
      __printf_color "Build of $BUILD_NAME has completed without error" "$GREEN"
      exitCode=0
    fi
  fi
  return "${exitCode:-$?}"
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__packages() {
  # Install required packages
  #__printf_color "Installing required packages"  "$BLUE"
  # if cmd_exists apt-get; then
  #   if cmd_exists pkmgr; then
  #     for pkg in LIST; do
  #        pkmgr silent install "$pkg" |&__devnull
  #        [[ $? = 0 ]] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
  #     done
  #   fi
  # elif cmd_exists dnf; then
  #   if cmd_exists pkmgr; then
  #     for pkg in LIST; do
  #        pkmgr silent install "$pkg" |&__devnull
  #        [[ $? = 0 ]] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
  #     done
  #   fi
  # elif cmd_exists yum; then
  #   if cmd_exists pkmgr; then
  #     for pkg in LIST; do
  #        pkmgr silent install "$pkg" |&__devnull
  #        [[ $? = 0 ]] && __logr "Installed $pkg" || __logr "Warning: Failed to installed $pkg"
  #     done
  #   fi
  # fi
  #__printf_color "Done trying to install packages"  "$YELLOW"
  return
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__init() {
  if [[ -z "$BUILD_FORCE" ]] && [[ -f "$(builtin type -P "$BUILD_NAME" 2>/dev/null)" ]]; then
    __printf_color "$BUILD_NAME is already installed at:" "$RED" 1>&2
    __printf_color "$(builtin type -P "$BUILD_NAME" "$GREEN" 2>/dev/null)"
    __printf_color "run with --force to rebuild" "$YELLOW" 1>&2
    exitCode="0"
    exit 0
  fi
  __printf_color "Initializing build script for $BUILD_NAME" "$PURPLE"
  __printf_color "Saving all output to $BUILD_LOG_FILE" "$CYAN"
  sleep 3
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Check for needed applications
type -P bash |& __devnull || { __printf_color "Missing: bash" "$RED" && exit 1; }
type -P make |& __devnull || { __printf_color "Missing: make" "$RED" && exit 1; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables
exitCode=10
NC="$(tput sgr0 2>/dev/null)"
RESET="$(tput sgr0 2>/dev/null)"
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"
ORANGE="\033[0;33m"
LIGHTRED='\033[1;31m'
BG_GREEN="\[$(tput setab 2 2>/dev/null)\]"
BG_RED="\[$(tput setab 9 2>/dev/null)\]"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Application Folders

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Show warn message if variables are missing

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set options
SETARGS="$*"
SHORTOPTS=""
LONGOPTS="debug,force,help,options,raw,version"
ARRAY=""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Setup application options
setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -a -n "$APPNAME" -- "$@" 2>/dev/null)
eval set -- "${setopts[@]}" 2>/dev/null
while :; do
  case "$1" in
  --debug)
    shift 1
    set -xo pipefail
    export SCRIPT_OPTS="--debug"
    export _DEBUG="on"
    __devnull() { cat -; }
    ;;
  --help)
    shift 1
    __help
    exit
    ;;
  --version)
    shift 1
    __printf_color "$APPNAME Version: $VERSION" "$YELLOW"
    exit
    ;;
  --options)
    echo "--$LONGOPTS" | sed 's|,| --|g'
    exit
    ;;
  --force)
    shift 1
    BUILD_FORCE=true
    ;;
  --raw)
    shift 1
    SHOW_RAW="true"
    ;;
  --)
    shift 1
    break
    ;;
  esac
done
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Redefine functions based on options

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Additional variables
BUILD_NAME="GEN_SCRIPT_REPLACE_APPNAME"
BUILD_SRC_URL="${BUILD_SRC_URL:-}"
BUILD_SRC_DIR="${BUILD_SRC_DIR:-$HOME/.local/share/$BUILD_NAME/source}"
BUILD_LOG_FILE="${BUILD_LOG_FILE:-/tmp/${BUILD_NAME}_build.log}"
if command -v "$BUILD_NAME" | grep -q '^/bin' || command -v "$BUILD_NAME" | grep -q '^/usr/bin'; then
  BUILD_DESTDIR="/usr"
else
  BUILD_DESTDIR="${BUILD_DESTDIR:-/usr/local}"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Main application
if [[ -d "$BUILD_SRC_DIR" ]]; then
  if ! builtin cd "$BUILD_SRC_DIR"; then
    __printf_color "Failed to cd into $BUILD_SRC_DIR" "$RED"
    exit 1
  fi
  __init
  __packages
  __run_git
  __make_build
  __check_log
  exitCode=$?
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# check
if [[ "$exitCode" -eq 10 || "$exitCode" -eq 0 ]] && [[ -n "$(builtin type -P "$BUILD_NAME")" ]]; then
  __printf_color "Successfully installed $BUILD_NAME" "$GREEN"
  exitCode=0
else
  __printf_color "Failed to install $BUILD_NAME" "$RED"
  exitCode=1
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit ${exitCode:-$?}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
