#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
[ "$DEBUGGER" = "on" ] && echo "Enabling debugging" && set -o pipefail -x$DEBUGGER_OPTIONS || set -o pipefail
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
printf '%s\n' "# - - - Initializing GEN_SCRIPT_REPLACE_APPNAME - - - #"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
SERVICE_NAME="GEN_SCRIPT_REPLACE_APPNAME"
SCRIPT_NAME="$(basename "$0" 2>/dev/null)"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export PATH="/usr/local/etc/docker/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# run trap command on exit
trap 'retVal=$?;[ "$SERVICE_IS_RUNNING" != "true" ] && [ -f "$SERVICE_PID_FILE" ] && rm -Rf "$SERVICE_PID_FILE";exit $retVal' SIGINT SIGTERM EXIT
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# import the functions file
if [ -f "/usr/local/etc/docker/functions/entrypoint.sh" ]; then
  . "/usr/local/etc/docker/functions/entrypoint.sh"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# import variables
for set_env in "/root/env.sh" "/usr/local/etc/docker/env"/*.sh "/config/env"/*.sh; do
  [ -f "$set_env" ] && . "$set_env"
done
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Custom functions

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Default predefined variables
WORKDIR=""                                                        # set working directory
DATA_DIR="/data"                                                  # set data directory
RUN_DIR="/run/init.d"                                             # set scripts pid dir
ETC_DIR="/etc/GEN_SCRIPT_REPLACE_APPNAME"                         # set etc directory
CONF_DIR="/config/GEN_SCRIPT_REPLACE_APPNAME"                     # set data directory
LOG_DIR="/data/logs/GEN_SCRIPT_REPLACE_APPNAME"                   # set log directory
WWW_DIR="/data/www/htdocs"                                        # set the web root
DATABASE_DIR="/data/db/GEN_SCRIPT_REPLACE_APPNAME"                # set the database directory
ROOT_FILE_PREFIX="/config/secure/GEN_SCRIPT_REPLACE_APPNAME_root" # where to save password for root user
USER_FILE_PREFIX="/config/secure/GEN_SCRIPT_REPLACE_APPNAME_user" # where to save password for normal user
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Is this service a database server
IS_WEB_SERVER="no"
IS_DATABASE_SERVICE="no"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets use environment for database dir if available
[ -n "$DATABASE_DIR_REPLACE_ENV" ] && DATABASE_DIR="$DATABASE_DIR_REPLACE_ENV"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Additional predefined variables

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# port which service is listening on
SERVICE_PORT=""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Show message before execute
PRE_EXEC_MESSAGE=""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# execute command variables
SERVICE_UID="0"                           # set the user id
SERVICE_USER="root"                       # execute command as another user
EXEC_CMD_BIN="GEN_SCRIPT_REPLACE_APPNAME" # command to execute
EXEC_CMD_ARGS=""                          # command arguments
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Additional variables

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# usernames and passwords
user_name=""
user_pass=""
root_user_name=""
root_user_pass=""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Overwrite variables from files
[ -f "${USER_FILE_PREFIX}_name" ] && user_name="$(<"{USER_FILE_PREFIX}_name")"
[ -f "${USER_FILE_PREFIX}_pass" ] && user_pass="$(<"{USER_FILE_PREFIX}_pass")"
[ -f "${ROOT_FILE_PREFIX}_name" ] && root_user_name="$(<"${ROOT_FILE_PREFIX}_name")"
[ -f "${ROOT_FILE_PREFIX}_pass" ] && root_user_pass="$(<"${ROOT_FILE_PREFIX}_pass")"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# use this function to update config files - IE: change port
__update_conf_files() {
  local exitCode=0

  # create custom directories
  # [ -n "" ] && { [ -d "" ] || { echo "Creating directory $ with permissions 777" && mkdir -p "" && chmod -Rf 777 ""; }; }

  # create default directories
  [ -n "$RUN_DIR" ] && { [ -d "$RUN_DIR" ] || { echo "Creating directory $RUN_DIR with permissions 777" && mkdir -p "$RUN_DIR" && chmod -Rf 777 "$RUN_DIR"; }; }
  [ -n "$LOG_DIR" ] && { [ -d "$LOG_DIR" ] || { echo "Creating directory $LOG_DIR with permissions 777" && mkdir -p "$LOG_DIR" && chmod -Rf 777 "$LOG_DIR"; }; }
  [ -n "$ETC_DIR" ] && { [ -d "$ETC_DIR" ] || { echo "Creating directory $ETC_DIR with permissions 777" && mkdir -p "$ETC_DIR" && chmod -Rf 777 "$ETC_DIR"; }; }
  [ -n "$CONF_DIR" ] && { [ -d "$CONF_DIR" ] || { echo "Creating directory $CONF_DIR with permissions 777" && mkdir -p "$CONF_DIR" && chmod -Rf 777 "$CONF_DIR"; }; }
  # create directories if variable is yes"
  [ "$IS_WEB_SERVER" = "yes" ] && { [ -d "$WWW_DIR" ] || { echo "Creating directory $WWW_DIR with permissions 777" && mkdir -p "$WWW_DIR" && chmod -f 777 "$WWW_DIR"; }; }
  [ "$IS_DATABASE_SERVICE" = "yes" ] && { [ -d "$DATABASE_DIR" ] || { echo "Creating directory $DATABASE_DIR with permissions 777" && mkdir -p "$DATABASE_DIR" && chmod -f 777 "$DATABASE_DIR"; }; }
  # copy config files
  [ -d "$CONF_DIR" ] && cp -Rf "$CONF_DIR/." "$ETC_DIR/"
  # replace variables
  # __replace "" "" "$CONF_DIR/"
  # custom commands

  # other

  return $exitCode
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# function to run before executing
__pre_execute() {
  local exitCode=0

  # fix permissions
  if [ -n "$SERVICE_USER" ] && [ "$SERVICE_USER" != "root" ]; then
    if grep -s -q "$SERVICE_USER:" "/etc/passwd"; then
      chown -Rf $SERVICE_USER:$SERVICE_USER "$ETC_DIR" "$WWW_DIR" "$LOG_DIR" "$RUN_DIR" && echo "changed ownership to $SERVICE_USER"
    fi
  fi

  return $exitCode
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# function to run after executing
__post_execute() {
  local exitCode=0
  sleep 60

  return $exitCode
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# use this function to update config files - IE: change port
__pre_message() {
  local exitCode=0
  [ -n "$user_name" ] && echo "username is:            $username" && echo "$user_name" >"${USER_FILE_PREFIX}_name"
  [ -n "$user_pass" ] && echo "password is:            saved to ${USER_FILE_PREFIX}_pass" && echo "$user_pass" >"${USER_FILE_PREFIX}_pass"
  [ -n "$root_user_name" ] && echo "root username is:  $root_user_name" && echo "$root_user_name" >"${ROOT_FILE_PREFIX}_name"
  [ -n "$root_user_pass" ] && echo "root password is:  saved to ${ROOT_FILE_PREFIX}_pass" && echo "$root_user_pass" >"${ROOT_FILE_PREFIX}_pass"

  return $exitCode
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# use this function to setup ssl support
__update_ssl_conf() {
  local exitCode=0

  return $exitCode
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__create_env() {
  cat <<EOF | tee "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh" &>/dev/null
ENV_WORKDIR="${ENV_WORKDIR:-$WORKDIR}"                            # change to directory
ENV_WWW_DIR="${ENV_WWW_DIR:-$WWW_DIR}"                            # set default web dir
ENV_ETC_DIR="${ENV_ETC_DIR:-$ETC_DIR}"                            # set default etc dir
ENV_DATA_DIR="${ENV_DATA_DIR:-$DATA_DIR}"                         # set default data dir
ENV_CONF_DIR="${ENV_CONF_DIR:-$CONF_DIR}"                         # set default config dir
ENV_DATABASE_DIR="${ENV_DATABASE_DIR:-$DATABASE_DIR}"             # set database dir
ENV_SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"             # execute command as another user
ENV_SERVICE_UID="${ENV_SERVICE_UID:-$SERVICE_UID}"                # set the user id
ENV_SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"             # port which service is listening on
EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"                 # command to execute
EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"              # command arguments
EXEC_CMD_NAME="$(basename "$EXEC_CMD_BIN")"                       # set the binary name

EOF
  [ -f "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh" ] || return 1
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# script to start server
__run_start_script() {
  local user="${SERVICE_USER:-root}"
  local workdir="${WORKDIR:-$WORK_DIR}"
  local cmd="$EXEC_CMD_BIN $EXEC_CMD_ARGS"
  local lc_type="${LC_ALL:-${LC_CTYPE:-$LANG}}"
  local home="${workdir//\/root/\/tmp\/docker}"
  local path="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"
  [ -z "$home" ] && home="${workdir:-/tmp/docker}"
  [ "$home" = "/root" ] && home="/tmp/docker"
  [ "$home" = "$workdir" ] && workdir=""
  # create home
  [ -n "$home" ] && { [ -d "$home" ] || mkdir -p "$home"; }
  [ -n "$workdir" ] && { [ -d "$workdir" ] || mkdir -p "$workdir" || workdir="/tmp"; }
  [ -n "$workdir" ] && __cd "$workdir" || { [ -n "$home" ] && __cd "$home"; } || __cd "/tmp"
  [ "$user" != "root " ] && [ -d "$home" ] && chmod -f 777 "$home"
  [ "$user" != "root " ] && [ -d "$workdir" ] && chmod -f 777 "$workdir"
  echo "Starting service: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
  su_cmd touch $SERVICE_PID_FILE
  __post_execute 2>/dev/stderr | tee -a "/data/logs/entrypoint.log" &>/dev/null &
  su_cmd env -i HOME="$home" LC_CTYPE="$lc_type" PATH="$path" USER="$user" sh -c "$cmd" || return 10
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# simple cd function
__cd() { mkdir -p "$1" && builtin cd "$1" || exit 1; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# process check functions
__pcheck() { [ -n "$(type -P pgrep 2>/dev/null)" ] && pgrep -x "$1" &>/dev/null && return 0 || return 10; }
__pgrep() { __pcheck "${1:-EXEC_CMD_BIN}" || __ps aux 2>/dev/null | grep -Fw " ${1:-$EXEC_CMD_BIN}" | grep -qv ' grep' | grep '^' && return 0 || return 10; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# check if process is already running
__proc_check() {
  local cmd_bin="" cmd_name=""
  cmd_bin="${1:-$EXEC_CMD_NAME}"
  cmd_name="$(basename "${1:-$EXEC_CMD_NAME}")"
  if __pgrep "$cmd_bin" || __pgrep "$cmd_name"; then
    SERVICE_IS_RUNNING="true"
    touch "$SERVICE_PID_FILE"
    echo "$cmd_name is already running"
    return 0
  else
    return 1
  fi
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Allow ENV_ variable - Import env file
[ -f "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh" ] && . "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
SERVICE_EXIT_CODE=0                                           # default exit code
WORKDIR="${ENV_WORKDIR:-$WORKDIR}"                            # change to directory
WWW_DIR="${ENV_WWW_DIR:-$WWW_DIR}"                            # set default web dir
ETC_DIR="${ENV_ETC_DIR:-$ETC_DIR}"                            # set default etc dir
DATA_DIR="${ENV_DATA_DIR:-$DATA_DIR}"                         # set default data dir
CONF_DIR="${ENV_CONF_DIR:-$CONF_DIR}"                         # set default config dir
DATABASE_DIR="${ENV_DATABASE_DIR:-$DATABASE_DIR}"             # set database dir
SERVICE_USER="${ENV_SERVICE_USER:-$SERVICE_USER}"             # execute command as another user
SERVICE_UID="${ENV_SERVICE_UID:-$SERVICE_UID}"                # set the user id
SERVICE_PORT="${ENV_SERVICE_PORT:-$SERVICE_PORT}"             # port which service is listening on
PRE_EXEC_MESSAGE="${ENV_PRE_EXEC_MESSAGE:-$PRE_EXEC_MESSAGE}" # Show message before execute
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# application specific
SERVICE_PID_NUMBER="$(__pgrep)"                                   # check if running
SERVICE_PID_FILE="/run/init.d/$EXEC_CMD_BIN.pid"                  # set the pid file location
EXEC_CMD_BIN="${ENV_EXEC_CMD_BIN:-$EXEC_CMD_BIN}"                 # command to execute
EXEC_CMD_ARGS="${ENV_EXEC_CMD_ARGS:-$EXEC_CMD_ARGS}"              # command arguments
EXEC_CMD_NAME="$(basename "$EXEC_CMD_BIN")"                       # set the binary name
EXEC_CMD_BIN="$(type -P "$EXEC_CMD_BIN" || echo "$EXEC_CMD_BIN")" # set full path
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Allow variables via imports - Overwrite existing
[ -f "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh" ] && . "/config/env/${SERVICE_NAME:-$SCRIPT_NAME}.sh"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ensure the command exists
if [ ! -f "$(type -P "$EXEC_CMD_BIN")" ] && [ -z "$EXEC_CMD_BIN" ]; then
  echo "$EXEC_CMD_BIN is not a valid command"
  exit 2
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Only run check
if [ "$1" = "check" ]; then
  __proc_check "$EXEC_CMD_NAME"
  exit $?
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# show message if env exists
if [ -n "$EXEC_CMD_BIN" ]; then
  [ -n "$SERVICE_USER" ] && echo "Setting up service to run as $SERVICE_USER" || SERVICE_USER="root"
  [ -n "$SERVICE_PORT" ] && echo "$EXEC_CMD_BIN will be running on $SERVICE_PORT" || SERVICE_PORT=""
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# set switch user command
if [ "$SERVICE_USER" = "root" ] || [ -z "$SERVICE_USER" ]; then
  su_cmd() { eval "$@" || return 1; }
elif [ "$(builtin type -P gosu)" ]; then
  su_cmd() { gosu $SERVICE_USER "$@" || return 1; }
elif [ "$(builtin type -P runuser)" ]; then
  su_cmd() { runuser -u $SERVICE_USER "$@" || return 1; }
elif [ "$(builtin type -P sudo)" ]; then
  su_cmd() { sudo -u $SERVICE_USER "$@" || return 1; }
elif [ "$(builtin type -P su)" ]; then
  su_cmd() { su -s /bin/sh - $SERVICE_USER -c "$@" || return 1; }
else
  echo "Can not switch to $SERVICE_USER: attempting to run as root"
  su_cmd() { eval "$@" || return 1; }
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Change to working directory
[ -n "$WORKDIR" ] && __cd "$WORKDIR" && echo "Changed to $PWD"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# show init message
__pre_message
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Initialize ssl
__update_ssl_conf
__update_ssl_certs
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Updating config files
__create_env
__update_conf_files
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# run the pre execute commands
[ -n "$PRE_EXEC_MESSAGE" ] && echo "$PRE_EXEC_MESSAGE"
__pre_execute
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__proc_check "$EXEC_CMD_NAME" && exit 1
__run_start_script "$@" |& tee -a "/data/logs/entrypoint.log"
if [ "$?" -ne 0 ]; then
  echo "Failed to execute: $EXEC_CMD_BIN $EXEC_CMD_ARGS"
  SERVICE_EXIT_CODE=10 SERVICE_IS_RUNNING="false"
  su_cmd rm -Rf "$SERVICE_PID_FILE"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
exit $SERVICE_EXIT_CODE
