#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  GEN_SCRIPT_REPLACE_VERSION
# @Author            :  GEN_SCRIPT_REPLACE_AUTHOR
# @Contact           :  GEN_SCRIPT_REPLACE_EMAIL
# @License           :  GEN_SCRIPT_REPLACE_LICENSE
# @ReadME            :  GEN_SCRIPT_REPLACE_FILENAME --help
# @Copyright         :  GEN_SCRIPT_REPLACE_COPYRIGHT
# @Created           :  GEN_SCRIPT_REPLACE_DATE
# @File              :  GEN_SCRIPT_REPLACE_FILENAME
# @Description       :  GEN_SCRIPT_REPLACE_DESC
# @TODO              :  GEN_SCRIPT_REPLACE_TODO
# @Other             :  GEN_SCRIPT_REPLACE_OTHER
# @Resource          :  GEN_SCRIPT_REPLACE_RES
# @sudo/root         :  no
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="$(basename "$0" 2>/dev/null)"
VERSION="GEN_SCRIPT_REPLACE_VERSION"
HOME="${USER_HOME:-$HOME}"
USER="${SUDO_USER:-$USER}"
RUN_USER="${SUDO_USER:-$USER}"
SRC_DIR="${BASH_SOURCE%/*}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set bash options
if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
trap 'exit $?' HUP INT QUIT TERM EXIT
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
__exec_bash() { [ -n "$1" ] && exec /bin/bash -c "${@:-bash}" || exec /bin/bash || exit 10; }
__find() { ls -A "$*" 2>/dev/null; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
DATA_DIR="${DATA_DIR:-$(__find /data/ 2>/dev/null | grep '^' || false)}"
CONFIG_DIR="${CONFIG_DIR:-$(__find /config/ 2>/dev/null | grep '^' || false)}"
export TZ="${TZ:-America/New_York}"
export HOSTNAME="${HOSTNAME:-casjaysdev-GEN_SCRIPT_REPLACE_APPNAME}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[[ -n "${TZ}" ]] && echo "${TZ}" >/etc/timezone
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[[ -f "/usr/share/zoneinfo/${TZ}" ]] && ln -sf "/usr/share/zoneinfo/${TZ}" "/etc/localtime"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [[ -n "${HOSTNAME}" ]]; then
  echo "${HOSTNAME}" >/etc/hostname
  echo "127.0.0.1 $HOSTNAME localhost" >/etc/hosts
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[[ -d "/config/" ]] && rm -Rf "/config/.gitkeep" || { [[ -n "$CONFIG_DIR" ]] && mkdir -p "/config/"; }
[[ -d "/data/" ]] && rm -Rf "/data/.gitkeep" || { [[ -n "$DATA_DIR" ]] && mkdir -p "/data/"; }
[[ -d "/bin/" ]] && rm -Rf "/bin/.gitkeep" || { [[ -n "$DATA_DIR" ]] && mkdir -p "/bin/"; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [[ -n "$CONFIG_DIR" ]]; then
  for config in $CONFIG_DIR; do
    if [[ -d "/config/$config" ]]; then
      cp -Rf "/config/$config/." "/etc/$config/"
    elif [[ -f "/config/$config" ]]; then
      cp -Rf "/config/$config" "/etc/$config"
    fi
  done
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
case "$1" in
--help)
  echo 'Docker container for '$APPNAME''
  echo "Usage: $APPNAME [healthcheck, bash, command]"
  echo
  exitCode=$?
  ;;
healthcheck)
  echo "$(uname -s) $(uname -m) is running"
  exitCode=$?
  ;;
sh | bash | shell | */bin/sh | */bin/bash)
  shift 1
  __exec_bash "$@"
  exitCode=$?
  ;;
*)
  __exec_bash "$@"
  ;;
esac
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
exit ${exitCode:-$?}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#end
