.\" Manpage for GEN_SCRIPT_REPLACE_APPNAME
.TH man 9 "14 July 2022" "GEN_SCRIPT_REPLACE_VERSION" "GEN_SCRIPT_REPLACE_APPNAME"

.SH NAME
GEN_SCRIPT_REPLACE_APPNAME

.SH SYNOPSIS
GEN_SCRIPT_REPLACE_APPNAME [optionnal argument] [optionnal argument]

.SH DESCRIPTION
GEN_SCRIPT_REPLACE_DESC

.SH OPTIONS
.IP "--version"\f
        Prints help
.IP "--help"\fR
        Prints help
.IP "--debug"\fR
        Prints help
.IP "--help"\fR
        Prints help

.SH FILES
.TP
.I
~/.config/myscripts/GEN_SCRIPT_REPLACE_APPNAME/settings.conf
.TP
.I
/usr/local/bin/GEN_SCRIPT_REPLACE_APPNAME

.SH BUGS
No known bugs.

.SH AUTHOR
written by GEN_SCRIPT_REPLACE_AUTHOR (GEN_SCRIPT_REPLACE_EMAIL)

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/isssues
