#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108120818-git
# @Author        : jason
# @Contact       : jason
# @License       : WTFPL
# @ReadME        : am_i_online --help
# @Copyright     : Copyright: (c) 2021 jason, jason
# @Created       : Thursday, Aug 12, 2021 08:18 EDT
# @File          : am_i_online
# @Description   : am_i_online completion script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_am_i_online() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/am_i_online"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/am_i_online}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1")"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--options --config --version --help --dir"
  local SHORTOPTS="-c -v -h -f -m -s -z"
  local ARRAY="--error --show --console --force --message --site --code"

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--options" ;;
    -c | --config) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--config" ;;
    -h | --help) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--help" ;;
    -v | --version) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--version" ;;
    -z | dir) COMPREPLY=($(compgen -W '$(_filedir)' -- "${cur}")) ;;
    *)
      if [ -n "$FILEDIR" ]; then _filedir; fi
      if [[ "$ARRAY" = "show-none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show-_filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show-commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [[ -n "$ARRAY" ]]; then
        #[ $COMP_CWORD -eq 3 ] && \
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [[ -n "$OPTS" ]]; then
        #[ $COMP_CWORD -gt 3 ] && \
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      elif [[ ${cur} == --* ]]; then
        COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
      elif [[ ${cur} == -* ]]; then
        COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
      fi
      ;;
    esac
  fi
  #[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  #[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  #[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _am_i_online am_i_online
