#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202103290512-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : blog --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Monday, Mar 29, 2021 12:14 EDT
# @File          : blog
# @Description   : Blogging script using github pages
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#blog --options &>/dev/null
_blog() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} ${4:-} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/blog"
  local OPTSDIR="$HOME/.local/share/myscripts/blog/options"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/blog}"
  local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "f" "1" "-iname '*.conf'")"
  local DEFAULTARRAY="$([ -f "$OPTSDIR/array" ] && grep -sEv '#|^$' "$OPTSDIR/array")"
  local DEFAULTOPTS="$([ -f "$OPTSDIR/options" ] && grep -sEv '#|^$' "$OPTSDIR/options" || echo -v -h)"
  local LONGOPTS="$(grep -sEv '#|^$' "$OPTSDIR/long_opts" || echo "$DEFAULTOPTS" | tr ' ' '\n' | grep '\--')"
  local SHORTOPTS="$(grep -sEv '#|^$' "$OPTSDIR/short_opts" || echo "$DEFAULTOPTS" | tr ' ' '\n' | grep -v '\--')"
  local OPTS="$DEFAULTOPTS"
  local ARRAY="$DEFAULTARRAY"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local date="$(date +'%Y-%m-%d')"

  _init_completion || return
  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi
  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
  else
    case ${COMP_WORDS[1]:-$prev} in
    --options) prev="--options" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -c | --config) prev="--config" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -h | --help) prev="--help" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -v | --version) prev="--version" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -f | --file) prev="--file" && COMPREPLY=($(compgen -W '${SEARCHCMD}' -- "${cur}")) ;;
    -) prev="-" && COMPREPLY=($(compgen -W '${SHORTOPTS} ${LONGOPTS}' -- ${cur})) ;;
    config) prev="config" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    copy) prev="copy" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    edit) prev="edit" COMPREPLY=($(compgen -W '$(ls $HOME/.local/share/blogs/*/_*/*)' -- "${cur}")) ;;
    new | page) prev="new" && COMPREPLY=($(compgen -W '{a..z}' -- "${cur}")) ;;
    post) prev="post" && COMPREPLY=($(compgen -W '{a..z}' -- "${cur}")) ;;
    *)
      if [ -n "$FILEDIR" ]; then _filedir; fi
      if [[ "$ARRAY" = "show-none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show-_filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show-commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [[ -n "$ARRAY" ]]; then
        #[ $COMP_CWORD -eq 3 ] && \
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [[ -n "$OPTS" ]]; then
        #[ $COMP_CWORD -gt 3 ] && \
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      fi
      ;;
    esac
    $split && return
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _blog blog
