#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202207211100-git
# @@Author           :  Jason Hempstead
# @@Contact          :  jason@casjaysdev.com
# @@License          :  WTFPL
# @@ReadME           :  buildx --help
# @@Copyright        :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @@Created          :  Thursday, Jul 21, 2022 11:00 EDT
# @@File             :  buildx
# @@Description      :  Docker buildx wrapper
# @@Changelog        :
# @@TODO             :  Better documentation
# @@Other            :
# @@Resource         :
# @@sudo/root        :  no
# @@Template         :  completions/system
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_buildx_completion() {
  ___list_dockerfiles() { find "$1" "./" -maxdepth 3 -name 'Dockerfile*' -type f -not -path '*/.git' 2>/dev/null | grep -v '^$'; }
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local CONFDIR="$HOME/.config/myscripts/buildx"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/buildx}"
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local CONFFILE="settings.conf"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local LONGOPTS="--debug --raw --options --config --version --help --dir "
  local LONGOPTS="--force --all --cleanup --registry --repo --no-registry --no-repo --platform --tag"
  local SHORTOPTS=""
  local ARRAY="init status version api build"
  local API_OPTS="list search sources clone"

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS:---}' -- ${cur})) && compopt -o nospace
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --debug | --raw | --help | --version | --config | --options)
      COMPREPLY=($(compgen -W '${ARRAY} ${LONGOPTS} ${SHORTOPTS}' -- ${cur}))
      return 0
      ;;
    --dir)
      prev="dir"
      [ "$cword" -le 2 ] && _filedir -d ||
        COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
      ;;
    api)
      COMPREPLY=($(compgen -W '${API_OPTS}' -- "$cur"))
      if [[ "$prev" = "clone" ]]; then
        COMPREPLY=($(compgen -W '$(buildx api clone)' -- "$cur"))
      elif [[ "$prev" = "list" ]]; then
        COMPREPLY=($(compgen -o nospace -W '' -- "$cur"))
      elif [[ "$prev" = "search" ]]; then
        COMPREPLY=($(compgen -W '$(echo {0..9} {a..z})' -- "$cur"))
      elif [[ "$prev" = "sources" ]]; then
        COMPREPLY=($(compgen -W '$(buildx api sources)' -- "$cur"))
      fi
      return
      ;;
    build)
      COMPREPLY=($(compgen -W '$(___list_dockerfiles -L)' -- "$cur"))
      return 0
      ;;
    *)
      COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
      return 0
      ;;
    esac
  fi

  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _buildx_completion buildx
