#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  020520211122-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  dmenu_edit_conf --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created           :  Friday, Feb 05, 2021 11:22 EST
# @File              :  dmenu_edit_conf
# @Description       :  autocomplete for dmenu_edit_conf
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_dmenu_edit_conf() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local ARRAY="$(<$CASJAYSDEVDIR/helpers/dmenu_edit_conf/array)"
  _init_completion || return

  case $prev in
  *)
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _dmenu_edit_conf -o default dmenu_edit_conf
