#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108121903-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : dockermgr --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Aug 12, 2021 19:03 EDT
# @File          : dockermgr
# @Description   : docker script to manage containers
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
_dockermgr() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/dockermgr"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/dockermgr}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--options --config --version --help --dir --force --all"
  local SHORTOPTS=""
  local DOCKEROPTS="$(docker ps -a 2>/dev/null | grep -v 'NAMES' | awk '{print $NF}' || return)"
  local DOCKERIMGS="$(docker images 2>/dev/null | grep -vE 'REPOSITORY|<.*.>' | awk '{print $1}' || return)"
  local ARRAY="enter test exec active available connect cron download enter inactive init install k3b "
  local ARRAY+="list log ps rancher remove rm rmi run search status update version ds "
  local LIST="airsonic daapd dictd docker-compose gitea hub ifconfig mailu mariadb mongo nginx-manager "
  local LIST+="nginx-manager-lite portainer postgresql rancher registry registry-web "
  local LIST+="transmission watchtower web-gui webvirtmgr yacht ympd "

  _init_completion || return

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(cron|update|remove) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    [[ $cur == @(*/|[.~])* && $special == @(cron|update|remove|version) ]]
  fi

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options)
      local prev="--options"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --config)
      local prev="--config"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --help)
      local prev="--help"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --version)
      local prev="--version"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --dir)
      local prev="dir"
      _filedir
      return
      ;;

    available)
      local prev="available"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    list)
      local prev="list"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    search)
      local prev="search"
      COMPREPLY=($(compgen -W '$(echo {0..9} {a..z})' -- "${cur}"))
      compopt -o nospace
      ;;

    install)
      local prev="--all"
      COMPREPLY=($(compgen -W '' -- "${cur}")) || { prev="install" && COMPREPLY=($(compgen -W '--all ${LIST}' -- "${cur}")); }
      ;;

    update | cron | remove | version)
      local prev="$special"
      k=0
      i="$HOME/.local/share/CasjaysDev/apps/dockermgr"
      for j in $(compgen -f "$i/$cur"); do
        [ -d "$j" ] && p="${j}"
        COMPREPLY[k++]=${p#$i/}
      done
      return 0
      ;;

    test | enter | exec | connect | run | log | rm)
      local prev="test"
      if [[ ${#COMP_WORDS[*]} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${DOCKEROPTS}' -- "${cur}"))
      fi
      ;;

    rmi)
      local prev="rmi"
      if [[ ${#COMP_WORDS[*]} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${DOCKERIMGS}' -- "${cur}"))
      fi
      ;;

    *)
      if [[ -n "$FILEDIR" ]]; then _filedir; fi
      if [[ "$ARRAY" = "show__none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show__filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show__commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      elif [[ -n "$ARRAY" ]]; then
        [ $COMP_CWORD -lt 2 ] &&
          COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [[ -n "$OPTS" ]]; then
        [ $COMP_CWORD -gt 2 ] &&
          COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      # elif [[ ${cword} -gt 2 ]]; then
      #   return
      # elif [[ ${cword} == 2 ]]; then
      #   _filedir
      #   compopt -o nospace
      #   return
      # elif [[ $cword -eq 1 ]]; then
      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
      #   compopt -o nospace
      #   return
      fi
      ;;
    esac
  fi
  #
  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _dockermgr dockermgr
