#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202108121903-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.com
# @License           :  WTFPL
# @ReadME            :  dockermgr --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:03 EDT
# @File              :  dockermgr
# @Description       :  docker script to manage containers
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
_dockermgr() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  ___docker_ps() { [ -f "$docker" ] && eval $docker ps -a 2>/dev/null | grep -v 'NAMES' | awk '{print $NF}'; }
  ___docker_net() { [ -f "$docker" ] && eval $docker network ls 2>/dev/null | grep -v 'NETWORK' | awk '{print $2}'; }
  ___docker_cont() { [ -f "$docker" ] && eval $docker images 2>/dev/null | grep -vE "REPOSITORY|<.*.>" | awk '{print $1}' | sort -u; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local docker="$(type -P docker 2>/dev/null || type -P podman 2>/dev/null)"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/dockermgr"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/dockermgr}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--raw --options --config --version --help --dir "
  local LONGOPTS+="--force --all --describe --platform --dockerfile --name --info "
  local SHORTOPTS="-p -P -v -m -e -d -u -w"
  local ARRAY="builder api enter test exec active available connect cron download inactive init install k3b minikube "
  local ARRAY+="list log ps rancher remove rm rmi run search status update version ds network helm prune generate "
  LIST="airsonic alpine apache aria2 bun caddy cherokee couchdb daapd ddns debian deno dictd docker gitea "
  LIST+="gohttpserver golang headphones heimdall hello-world hub i2p ifconfig jekyll lenpaste lighttpd link-warden "
  LIST+="mailu mariadb mongodb navidrome nextcloud nginx nginx-manager nginx-manager-lite php pihole podman portainer "
  LIST+="postgres rancher redis registry registry-web soft-serve sqlite3 supabase tor-browser traefik transmission "
  LIST+="uptimekuma vaultwarden watchtower web-gui webvirtmgr whoogle wireguard yacht ympd youtubedl-web "
  SRCS="alpine ampache apache apprise archlinux aria2 bash bind bun caddy centos7 cherokee code "
  SRCS+="codinggarden-travel-log codinggarden-trello-clone commitment couchdb ddns debian deno dictd "
  SRCS+="docker gitea gohttpserver golang headphones homepage homey ifconfig jekyll jellyfin lenpaste lighttpd "
  SRCS+="link-warden mariadb memos mongodb mpd navidrome neovim nextcloud nginx nodejs opencv php php7 podman postgres "
  SRCS+="proftpd python2 python3 readme-to-dockerhub redis registry-web rhel7 rhel8 rhel9 rockylinux rpm-devel soft-serve "
  SRCS+="sqlite3 squidguard ssl-ca supabase systemd system-scripts tftpd theHarvester tools tor tor-browser traefik transmission "
  SRCS+="vaultwarden vim wordpress wttr xfce4 ympd youtube-dl "

  _init_completion || return

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(cron|update|remove) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [[ -v special ]]; then
    [[ $cur == @(*/|[.~])* && $special == @(cron|update|remove|version) ]]
  fi

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options)
      local prev="--options"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --config)
      local prev="--config"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --help)
      local prev="--help"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --version)
      local prev="--version"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --dir)
      local prev="dir"
      _filedir
      return
      ;;

    list | status | helm | available | active | inactive | init | rancher | k3b | ds)
      local prev="endopts"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    search)
      local prev="search"
      COMPREPLY=($(compgen -W '$(echo {0..9} {a..z})' -- "${cur}"))
      compopt -o nospace
      ;;

    install | download)
      local prev="--all"
      COMPREPLY=($(compgen -W '' -- "${cur}")) || { prev="install" && COMPREPLY=($(compgen -W '--all ${LIST}' -- "${cur}")); }
      ;;

    update | cron | remove | version)
      local prev="$special"
      k=0
      i="$HOME/.local/share/CasjaysDev/apps/dockermgr"
      for j in $(compgen -f "$i/$cur"); do
        [ -e "$j" ] && p="${j}" || return
        COMPREPLY[k++]=${p#"$i"/}
      done
      return 0
      ;;

    test | enter | exec | connect | run | log)
      local prev="test"
      if [[ ${#COMP_WORDS[*]} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '$(___docker_ps)' -- "${cur}"))
      fi
      ;;

    rmi)
      local prev="rmi"
      COMPREPLY=($(compgen -W '$(___docker_cont)' -- "${cur}"))
      ;;

    rm)
      local prev="rm"
      COMPREPLY=($(compgen -W '$(___docker_ps)' -- "${cur}"))
      ;;

    pull | push)
      local prev="pull"
      COMPREPLY=($(compgen -W '$(___docker_cont)' -- "${cur}"))
      ;;

    org)
      local prev="org"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    api)
      case "$prev" in
      sources)
        local prev="sources"
        COMPREPLY=($(compgen -W 'help name url' -- "${cur}"))
        compopt -o nospace
        ;;
      clone)
        local prev="clone"
        COMPREPLY=($(compgen -W '${SRCS}' -- "${cur}"))
        ;;
      *)
        local prev="api"
        COMPREPLY=($(compgen -W 'auth list delete info update readme sources clone' -- "${cur}"))
        ;;
      esac
      ;;

    compose)
      if [[ ${#COMP_WORDS[*]} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W 'update' -- "${cur}"))
      fi
      ;;

    minikube)
      if [[ ${#COMP_WORDS[*]} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        local prev="minikube"
        COMPREPLY=($(compgen -W 'delete init services dashboard' -- "${cur}"))
      fi
      ;;

    network)
      if [[ ${#COMP_WORDS[*]} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        local prev="network"
        COMPREPLY=($(compgen -W '$(___docker_net)' -- "${cur}"))
      fi
      ;;

    *)
      if [[ -n "$FILEDIR" ]]; then _filedir; fi
      if [[ "$ARRAY" = "show__none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show__filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show__commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      elif [[ -n "$ARRAY" ]]; then
        [ $COMP_CWORD -lt 2 ] &&
          COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [[ -n "$OPTS" ]]; then
        [ $COMP_CWORD -gt 2 ] &&
          COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      # elif [[ ${cword} -gt 2 ]]; then
      #   return
      # elif [[ ${cword} == 2 ]]; then
      #   _filedir
      #   compopt -o nospace
      #   return
      # elif [[ $cword -eq 1 ]]; then
      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
      #   compopt -o nospace
      #   return
      fi
      ;;
    esac
  fi
  #
  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _dockermgr dockermgr
