#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="$(basename "$0")"
VERSION="202108121903-git"
USER="${SUDO_USER:-${USER}}"
HOME="${USER_HOME:-${HOME}}"
SRC_DIR="${BASH_SOURCE%/*}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#set opts

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108121903-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : dotfiles --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Aug 12, 2021 19:03 EDT
# @File          : dotfiles
# @Description   : dotfiles installer script
# @TODO          :
# @Other         : This script is obsolete
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
_dotfiles() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/dotfiles"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/dotfiles}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1")"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--options --config --version --help --dir"
  local SHORTOPTS="-z"
  local LSBIN=$(ls /usr/local/share/CasjaysDev/scripts/bin/ 2>/dev/null)
  local ADMIN="installer postfix cron samba ssl ssh tor"
  local ARRAY="help describe stow install admin version cron update reset personal custom desktops minimal server"
  local LIST="fish geany git gtk-2.0 gtk-3.0 guake htop i3 jgmenu lemonbar lf misc mpd mutt nano neofetch neovim newsboat nitrogen openbox "
  local LIST+="pianobar picard polybar qterminal qtile ranger remmina rofi sakura screen smplayer smtube sway sxhkd terminology termite "
  local LIST+="Thunar tig tint2 tmux transmission variety vifm vim volumeicon xfce4 xfce4-terminal xmonad youtube-dl youtube-viewer  "
  local LIST+="ytmdl zsh nodejs ruby "
  local LIST+=""
  local STOW="$ARRAY"

  _init_completion || return

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options)
      local prev="--options"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --config)
      local prev="--config"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --help)
      prev="--help"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --version)
      local prev="--version"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    -z | --dir)
      local prev="dir"
      _filedir
      return
      ;;

    admin)
      COMPREPLY=($(compgen -W '--all ${ADMIN[*]}' -- "${cur[*]}"))
      return
      ;;

    install)
      COMPREPLY=($(compgen -W '--all ${LIST[*]}' -- "$cur"))
      return
      ;;

    stow)
      COMPREPLY=($(compgen -W ' ${STOW[*]}' -- "$cur"))
      return
      ;;

    config)
      COMPREPLY=($(compgen -W 'dircolors' -- "$cur"))
      return
      ;;

    update)
      COMPREPLY=($(compgen -W ' ${LIST[*]}' -- "$cur"))
      return
      ;;

    describe)
      COMPREPLY=($(compgen -W ' ${LSBIN}' -- "$cur"))
      ;;

    version)
      COMPREPLY=($(compgen -W ' ${LIST[*]} ${ADMIN[*]}' -- "$cur"))
      return
      ;;

    *)
      if [[ -n "$FILEDIR" ]]; then _filedir; fi
      if [[ "$ARRAY" = "show-none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show-_filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show-commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      # elif [[ ${cword} -gt 2 ]]; then
      #   return
      # elif [[ ${cword} == 2 ]]; then
      #   _filedir
      #   compopt -o nospace
      #   return
      # elif [[ $cword -eq 1 ]]; then
      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
      #   compopt -o nospace
      #   return
      fi
      ;;
    esac
  fi
  #
  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _dotfiles dotfiles
