#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108080336-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-readme --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Sunday, Aug 08, 2021 03:36 EDT
# @File          : gen-readme
# @Description   : gen-readme completion script
# @TODO          : 
# @Other         : 
# @Resource      : 
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gen-readme() {
  ___findcmd() { find -L "${1:-$SEARCHDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$SEARCHDIR}'##g' | grep '^' || return 1; }
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/gen-readme"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/gen-readme}/files"
  local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "4")"
  local DEFAULTARRAY="list search download custom all"
  local DEFAULTOPTS=""
  local LONGOPTS="--options --config --version --help --copy"
  local SHORTOPTS="-c -v -h"
  local OPTS="$DEFAULTOPTS"
  local ARRAY="$DEFAULTARRAY"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""

  _init_completion || return
  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi
  case ${COMP_WORDS[1]:-$prev} in
  -) COMPREPLY=($(compgen -W '${SHORTOPTS} ${LONGOPTS}' -- ${cur})) && prev="-" ;;
  --options) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--options" ;;
  -c | --config) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--config" ;;
  -h | --help) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--help" ;;
  -v | --version) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--version" ;;
  -l | --list) COMPREPLY=($(compgen -W '' -- "${cur}")) && prev="--list" ;;
  all) COMPREPLY=($(compgen -W '$SEARCHCMD' -- "$cur")); return    ;;
  projects) COMPREPLY=($(compgen -W '$(___findcmd "$SEARCHDIR/projects" "d" "1")' -- "$cur")); return    ;;
  installers) COMPREPLY=($(compgen -W '$(___findcmd "$SEARCHDIR/installers" "d" "1")' -- "$cur")); return    ;;
  *)
    if [ -n "$FILEDIR" ]; then _filedir; fi
    if [[ "$ARRAY" = "show-none" ]]; then
      COMPREPLY=($(compgen -W '' -- "${cur}"))
    elif [[ "$ARRAY" = "show-_filedir" ]]; then
      _filedir
    elif [[ "$ARRAY" = "show-commands" ]]; then
      COMPREPLY=($(compgen -c -- "${cur}"))
    elif [[ -n "$ARRAY" ]]; then
      #[ $COMP_CWORD -eq 3 ] && \
      COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
    elif [[ -n "$OPTS" ]]; then
      #[ $COMP_CWORD -gt 3 ] && \
      COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
    elif [[ ${cur} == --* ]]; then
      COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    elif [[ ${cur} == -* ]]; then
      COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    fi
    ;;
  esac
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-readme gen-readme
  
