#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-script --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gen-script
# @Description   : autocomplete for gen-script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [ ! -f "$HOME/.local/share/gen-script/opts.txt" ]; then
  mkdir -p "$HOME/.config/gen-script" &>/dev/null
  mkdir -p "$HOME/.local/share/gen-script" &>/dev/null
  gen-script -a -create &>/dev/null
fi
_gen-script() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${4:-$1}'##g' | grep '^' || return 1; }
  local cur prev words cword
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  if [ -d "$HOME/.config/gen-script/files" ]; then
    local GEN_SCRIPTS_TEMPLATE_DIR="$HOME/.config/gen-script/files"
  else
    local GEN_SCRIPTS_TEMPLATE_DIR="$CASJAYSDEVDIR/templates/scripts"
  fi
  mkdir -p "$HOME/.config/gen-script"
  local CONFDIR="$HOME/.config/gen-script"
  local OPTSDIR="$HOME/.local/share/gen-script"
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local FOLDERS="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/" "d" "1" "$GEN_SCRIPTS_TEMPLATE_DIR/" | grep -v ^'templates')"
  local OS="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/os/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/os")"
  local COMPLETIONS="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/completions/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/completions/")"
  local SHELL="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/shell/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/shell/")"
  local BASH="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/bash/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/bash/")"
  local OTHER="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/other/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/other/")"
  local READMES="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/other/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/other/")"
  local INSTALLERS="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/installers/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/installers/")"
  local ALL="$(___findcmd "$GEN_SCRIPTS_TEMPLATE_DIR/" "f" "3" "$GEN_SCRIPTS_TEMPLATE_DIR/")"
  local SHOW_COMP_OPTS=""
  local DEFAULTARRAY="$([ -f "$OPTSDIR/array" ] && grep -sEv '#|^$' "$OPTSDIR/array" || echo '--options --help --version')"
  local DEFAULTOPTS="$([ -f "$OPTSDIR/options" ] && grep -sEv '#|^$' "$OPTSDIR/options" || echo '--options --help --version')"
  local LONGOPTS="$(grep -sEv '#|^$' "$OPTSDIR/long_opts" || echo "$DEFAULTOPTS" | tr ' ' '\n' | grep '\--')"
  local SHORTOPTS="$(grep -sEv '#|^$' "$OPTSDIR/short_opts" || echo "$DEFAULTOPTS" | tr ' ' '\n' | grep -v '\--')"
  local OPTS="-list -config -copy -download"
  local ARGS="${SHORTOPTS} ${LONGOPTS}"
  local ARRAY="all ${FOLDERS}"

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o '${SHOW_COMP_OPTS_SEP}'
  fi
  if [[ ${#COMP_WORDS[@]} -eq 3 ]] && [[ ${COMP_WORDS[1]} = -header ]]; then
    COMPREPLY=($(compgen -c -- "$cur"))
  elif [[ ${#COMP_WORDS[@]} -gt 4 ]] && [[ ${COMP_WORDS[1]} = -header ]]; then
    COMPREPLY=($(compgen -W '${HEADEROPTS}' -- "${cur}"))
  elif [[ ${COMP_WORDS[1]} = -readme ]]; then
    COMPREPLY=($(compgen -W '--import . ${READMES}' -o plusdirs -- "${cur}")) && _filedir
  elif [[ "${cur}" == --* ]]; then
    COMPREPLY=($(compgen -W '${HEADEROPTS}' -- ${cur}))
  elif [[ "${cur}" == -* ]]; then
    COMPREPLY=($(compgen -W '${ARGS}' -- ${cur}))
  else
    if [[ "${prev}" = all ]]; then
      COMPREPLY=($(compgen -W '${ALL}' -- "${cur}"))
      return
    elif [[ "${prev}" = installers ]]; then
      COMPREPLY=($(compgen -W '${INSTALLERS}' -- "${cur}"))
      return
    elif [[ "${prev}" = bash ]]; then
      COMPREPLY=($(compgen -W '${BASH}' -- "${cur}"))
      return
    elif [[ "${prev}" = shell ]]; then
      COMPREPLY=($(compgen -W '${SHELL}' -- "${cur}"))
      return
    elif [[ "${prev}" = os ]]; then
      COMPREPLY=($(compgen -W '${OS}' -- "${cur}"))
      return
    elif [[ "${prev}" = "completions" ]]; then
      COMPREPLY=($(compgen -W '${COMPLETIONS}' -- "${cur}"))
      return
    elif [[ "${prev}" = other ]]; then
      COMPREPLY=($(compgen -W '${OTHER}' -- "${cur}"))
      return
    elif [[ "${prev}" = -readme ]]; then
      COMPREPLY=($(compgen -W '${OTHER}' -- "${cur}"))
    elif [[ "${prev}" = -header ]]; then
      COMPREPLY=($(compgen -W '${HEADEROPTS}' -- "${cur}"))
    else
      if [ "$ARRAY" = "show-commands" ]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" = "show-none" ]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [ "$ARRAY" = "show-_filedir" ]; then
        _filedir
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      fi
    fi
  fi
  return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-script gen-script
