#!/usr/bin/env bash
# shellcheck shell=bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202303101751-git
# @@Author           :  Jason Hempstead
# @@Contact          :  jason@casjaysdev.pro
# @@License          :  LICENSE.md
# @@ReadME           :  gen-dns --help
# @@Copyright        :  Copyright: (c) 2023 Jason Hempstead, Casjays Developments
# @@Created          :  Friday, Mar 10, 2023 18:39 EST
# @@File             :  gen-dns
# @@Description      :  Generate a dns zone
# @@Changelog        :  https://bash.cyberciti.biz/domain/create-bind9-domain-zone-configuration-file/
# @@TODO             :  Better documentation
# @@Other            :
# @@Resource         :  https://bash.cyberciti.biz/domain/create-bind9-domain-zone-configuration-file/
# @@Terminal App     :  no
# @@sudo/root        :  no
# @@Template         :  completions/system
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gen-dns_completion() {
  _init_completion || return
  #####################################################################
  local cur prev words cword opts split CONFDIR="" CONFFILE="" SEARCHDIR=""
  local SHOW_COMP_OPTS="" SHORTOPTS="" LONGOPTS="" ARRAY="" LIST="" SHOW_COMP_OPTS_SEP=""
  #####################################################################
  ___ls() { ls -A "$1" 2>/dev/null | grep -v '^$' | grep '^' || false; }
  ___grep() { GREP_COLORS="" grep -shE '^.*=*..*$' "$1" 2>/dev/null | sed 's|"||g' 2>/dev/null | grep '^' || false; }
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'/##g;s|.*/||g' | grep '^' || return 1; }
  #####################################################################
  cur="${COMP_WORDS[$COMP_CWORD]}"
  prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  #####################################################################
  CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  #####################################################################
  CONFFILE="settings.conf"
  CONFDIR="$HOME/.config/myscripts/gen-dns"
  SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/gen-dns}"
  #####################################################################
  SHOW_COMP_OPTS=""
  #####################################################################
  SHORTOPTS=""
  SHORTOPTS+=""
  #####################################################################
  LONGOPTS="--completions --config --debug --dir --help --options --raw --version --silent --copy "
  LONGOPTS+="--domain --hostip4 --hostip6 --dnsip4 --dnsip6 --force --forwarders --import --template --provider --transfer"
  #####################################################################
  ARRAY="edit "
  ARRAY+=""
  #####################################################################
  LIST="$(___findcmd "$HOME/.config/myscripts/gen-dns/named")"
  LIST+=""
  #####################################################################
  if [ "$SHOW_COMP_OPTS" != "" ]; then
    SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi
  #####################################################################
  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  elif [[ ${cur} == -* ]]; then
    if [ -n "$SHORTOPTS" ]; then
      COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    else
      COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    fi
  else
    case "${prev:-${COMP_WORDS[1]}}" in
    --completions)
      prev=""
      COMPREPLY=($(compgen -W 'long short list array' -- "$cur"))
      ;;
    --config | --debug | --help | --options | --raw | --version)
      COMPREPLY=($(compgen -W '${ARRAY} ${LONGOPTS} ${SHORTOPTS}' -- ${cur}))
      return 0
      ;;
    --copy)
      COMPREPLY=($(compgen -W '' -- "$cur"))
      ;;
    --dir)
      prev="dir"
      [ "$cword" -le 2 ] && _filedir -d || COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
      ;;
    --silent | --force)
      COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
      ;;
    --domain | --hostip4 | --hostip6 | --dnsip4 | --dnsip6 | --forwarders)
      prev="$cword"
      COMPREPLY=($(compgen -W '$(echo {0..9})' -- "$cur"))
      compopt -o nospace
      ;;
    --import)
      prev="import"
      _filedir -d
      ;;
    --provider)
      prev="provider"
      COMPREPLY=($(compgen -W 'pihole casjay bitly vercel github google redirect wordpress cloudflare' -- "$cur"))
      ;;
    edit)
      prev="edit"
      COMPREPLY=($(compgen -W '${LIST}' -- "$cur"))
      ;;
    *)
      COMPREPLY=($(compgen -W '- ${ARRAY}' -- "$cur"))
      return 0
      ;;
    esac
  fi
  #
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-dns_completion -o default gen-dns

# ex: ts=2 sw=2 et filetype=sh
