#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gen-script --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gen-script
# @Description   : autocomplete for gen-script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [ ! -f "$HOME/.local/share/gen-script/opts.txt" ]; then
  mkdir -p "$HOME/.config/gen-script" &>/dev/null
  mkdir -p "$HOME/.local/share/gen-script" &>/dev/null
  gen-script -a --force -create &>/dev/null
fi
_gen-script() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${4:-$1}'##g' | grep '^' || return 1; }
  local cur prev words cword
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  if [ -d "$HOME/.config/gen-script/files" ]; then
    local GEN_SCRIPT_TEMPLATE_DIR="$HOME/.config/gen-script/files"
  else
    local GEN_SCRIPT_TEMPLATE_DIR="$CASJAYSDEVDIR/templates/scripts"
  fi
  mkdir -p "$HOME/.config/gen-script"
  local CONFDIR="$HOME/.config/gen-script"
  local OPTSDIR="$HOME/.local/share/gen-script"
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local FOLDERS="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/" "d" "1" "$GEN_SCRIPT_TEMPLATE_DIR/" | grep -v ^'templates')"
  local OS="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/os/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/os")"
  local COMPLETIONS="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/completions/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/completions/")"
  local SHELL="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/shell/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/shell/")"
  local BASH="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/bash/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/bash/")"
  local OTHER="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/other/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/other/")"
  local READMES="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/other/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/other/")"
  local INSTALLERS="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/installers/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/installers/")"
  local ALL="$(___findcmd "$GEN_SCRIPT_TEMPLATE_DIR/" "f" "3" "$GEN_SCRIPT_TEMPLATE_DIR/")"
  local ARRAY="all ${FOLDERS}"
  local SHOW_COMP_OPTS=""
  local SHORTOPTS="$(grep -sEv '#|^$' "$OPTSDIR/opts-short.txt" || echo --options)"
  local LONGOPTS="$(grep -sEv '#|^$' "$OPTSDIR/opts-long.txt" || echo -long --help '-a -create')"
  local HEADEROPTS="$(grep -sEv '#|^$' "$OPTSDIR/opts-header.txt" || echo -header)"
  local ARGS="${SHORTOPTS} ${LONGOPTS}"

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi
  case ${COMP_WORDS[1]:-$prev} in
  -) prev="-" COMPREPLY=($(compgen -W '${SHORTOPTS} ${LONGOPTS}' -- ${cur})) ;;
  -a | --options) prev="--options" && COMPREPLY=($(compgen -W '--force -create' -- "${cur}")) ;;
  -c | --config) prev="--config" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
  -h | --help) prev="--help" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
  -v | --version) prev="--version" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
  -head)
    prev="head"
    COMPREPLY=($(compgen -W '${HEADEROPTS}' -- "${cur}"))
    if [[ "${prev}" = "head" ]]; then
      COMPREPLY=($(compgen -W '${HEADEROPTS}' -- "${cur}"))
    elif [[ ${#COMP_WORDS[@]} -eq 3 ]] && [[ ${COMP_WORDS[1]} = -header ]]; then
      COMPREPLY=($(compgen -c -- "$cur"))
    elif [[ ${#COMP_WORDS[@]} -gt 4 ]] && [[ ${COMP_WORDS[1]} = -header ]]; then
      COMPREPLY=($(compgen -W '${HEADEROPTS}' -- "${cur}"))
    fi
    ;;
  -readme)
    prev="-readme"
    COMPREPLY=($(compgen -W '--import . ${READMES}' -o plusdirs -- "${cur}")) && _filedir
    if [[ "${prev}" = --import ]]; then
      COMPREPLY=($(compgen -W '${OTHER}' -- "${cur}")) && prev=import
    fi
    ;;
  all | installers | bash | shell | os | other | completions)
    if [[ "${next}" = "prevScripts" ]]; then
      _filedir && next=filename
    elif [[ "${next}" = "filename" ]]; then
      COMPREPLY=($(compgen -W '${HEADEROPTS}' -- ${cur})) && next=header
    elif [[ "${next}" = "selected" ]] || [[ "${prev}" = "header" ]]; then
      COMPREPLY=($(compgen -W '${HEADEROPTS}' -- "${cur}")) && next=header
    elif [[ "${prev}" = "" ]]; then
      COMPREPLY=($(compgen -W '${ALL}' -- "${cur}")) && next=prevScripts
    fi
    if [[ "${prev}" = all ]]; then
      COMPREPLY=($(compgen -W '${ALL}' -- "${cur}")) && next=prevScripts
    elif [[ "${prev}" = installers ]]; then
      COMPREPLY=($(compgen -W '${INSTALLERS}' -- "${cur}")) && next=prevScripts
    elif [[ "${prev}" = bash ]]; then
      COMPREPLY=($(compgen -W '${BASH}' -- "${cur}")) && next=prevScripts
    elif [[ "${prev}" = shell ]]; then
      COMPREPLY=($(compgen -W '${SHELL}' -- "${cur}")) && next=prevScripts
    elif [[ "${prev}" = os ]]; then
      COMPREPLY=($(compgen -W '${OS}' -- "${cur}")) && next=prevScripts
    elif [[ "${prev}" = other ]]; then
      COMPREPLY=($(compgen -W '${OTHER}' -- "${cur}")) && next=prevScripts
    elif [[ "${prev}" = "completions" ]]; then
      COMPREPLY=($(compgen -W '${COMPLETIONS}' -- "${cur}")) && next=prevScripts
    fi
    ;;
  *)
    if [[ ${cur} == --* ]]; then
      COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    elif [[ ${cur} == -* ]]; then
      COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    else
      if [ "$ARRAY" = "show-commands" ]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" = "show-none" ]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [ "$ARRAY" = "show-_filedir" ]; then
        _filedir
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      fi
    fi
    ;;
  esac
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gen-script gen-script
