#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202601261105-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  gitcommit --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:03 EDT
# @File              :  gitcommit
# @Description       :  Commit changes to a git repo (self-contained)
# @TODO              :  N/A
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - -'
_gitcommit() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/gitcommit"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/gitcommit}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
  local SHOW_COMP_OPTS="default"
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--options --version --help --config --dir --message --amend"
  local SHORTOPTS="-m"
  local ARRAY="ai is all amend status log reset branch fixup squash push version files modified updated "
  local ARRAY+="deleted added renamed changed new improved fixed release "
  local ARRAY+="deploy docs test breaking refactor performance permissions "
  local ARRAY+="bugs docker node ruby php perl python scratchpad todo recipe "
  local ARRAY+="notes blog init emojify random custom tag tar spelling "
  _init_completion || return

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options)
      local prev="--options"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --config)
      local prev="--config"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --help)
      prev="--help"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --version)
      local prev="--version"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    is)
      local prev="is"
      COMPREPLY=($(compgen -W 'clean dirty' -- "${cur}"))
      ;;

    log)
      local prev="log"
      COMPREPLY=($(compgen -W 'show' -- "${cur}"))
      ;;

    tag)
      local prev="tag"
      COMPREPLY=($(compgen -W 'add remove' -- "${cur}"))
      ;;

    *)
      if [[ "$array" != "true" ]] && [[ ${#COMP_WORDS[@]} -le 2 ]]; then
        local array="true"
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      else
        _filedir
      fi
      ;;
    esac
  fi
  #
  # [[ ${#cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ ${#COMP_CWORD} -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ ${#COMP_CWORD} -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ ${#COMP_CWORD} -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gitcommit gitcommit
