#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 020520211122-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : gitadmin --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Friday, Feb 05, 2021 11:22 EST
# @File          : gitadmin
# @Description   : autocomplete for gitadmin
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_gitadmin() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/GEN_SCRIPT_REPLACE_FILENAME"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/GEN_SCRIPT_REPLACE_FILENAME}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1")"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--options --config --version --help --user --org --single"
  local SHORTOPTS="-c -v -h -u -o -s"
  local ARRAY="repos stow setup newsite private gitlab github single init gist org remote delete "
  local ARRAY+="create pull clone push user update commit branch log status cron issues shorten latest"
  local gitOPTS="init clone remote"
  local automatedOpts="--automated"
  local updateOpts="--while"
  local GIST="delete create list edit"

  _init_completion || return

  local special i
  for ((i = 1; i < ${#words[@]} - 1; i++)); do
    if [[ ${words[i]} == @(cron|update|remove) ]]; then
      special=${words[i]}
      break
    fi
  done

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
  else
    case ${COMP_WORDS[1]:-$prev} in
    --options) prev="--options" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -c | --config) prev="--config" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -h | --help) prev="--help" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -v | --version) prev="--version" && COMPREPLY=($(compgen -W '' -- "${cur}")) ;;
    -s | --single | -u | --user | -o | --org) prev="--single" && COMPREPLY=($(compgen -W '{a..z}' -- "${cur}")) ;;
    single) prev="single" && COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur")) ;;
    github) prev="github" && COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur")) ;;
    gitlab) prev="gitlab" && COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur")) ;;
    private) prev="private" && COMPREPLY=($(compgen -W '${gitOPTS}' -- "$cur")) ;;
    setup) prev="setup" && COMPREPLY=($(compgen -W '${automatedOpts}' -- "$cur")) ;;
    update) prev="update" && COMPREPLY=($(compgen -W '${updateOpts}' -- "$cur")) ;;
    gist) prev="gist" && COMPREPLY=($(compgen -W '${GIST}' -- '[a..z]' "$cur")) ;;
    clone) prev="clone" && COMPREPLY=($(compgen -W '/ http:// https:// git://' -- "$cur")) ;;

    org)
      COMPREPLY=($(compgen -W 'all' -- "$cur"))
      k=0
      i="$HOME/Projects"/*
      for d in $i/*; do
        for j in $(compgen -f "$d/$cur"); do
          [ -d "$j" ] && j="${j}"
          COMPREPLY[k++]=${j#$d/}
        done
      done
      return 0
      ;;

    push)
      k=0
      i="$HOME/Projects/"*
      for d in $(ls -d $i/*); do
        for j in $(compgen -f "$d/$cur"); do
          [ -d "$j" ] && j="${j}"
          COMPREPLY[k++]=${j}
        done
      done
      return 0
      ;;

    pull)
      k=0
      i="$HOME/Projects/*"
      for d in $i/*; do
        for j in $(compgen -f "$d/$cur"); do
          [ -d "$j" ] && j="${j} "
          COMPREPLY[k++]=${j}
        done
      done
      return 0
      ;;

    *)
      prev=""
      if [ -n "$FILEDIR" ]; then _filedir; fi
      if [[ "$ARRAY" = "show-none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show-_filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show-commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [[ -n "$ARRAY" ]]; then
        [ $COMP_CWORD -lt 2 ] &&
          COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [[ -n "$OPTS" ]]; then
        [ $COMP_CWORD -gt 2 ] &&
          COMPREPLY=($(compgen -W '' -- "${cur}"))
      fi
      ;;
    esac
  fi
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _gitadmin -o default gitadmin
