#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  020520211122-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  killall --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created           :  Friday, Feb 05, 2021 11:22 EST
# @File              :  killall
# @Description       :  autocomplete for killall
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[[ $OSTYPE == *@(linux|freebsd|darwin)* ]] || return 1
_killall() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword split

  _init_completion -s || return
  case $prev in
  --context | --older-than | --younger-than | --version | -!(-*)@([Zoy]|V*))
    return
    ;;

  --signal | -!(-*)s)
    _signals
    return
    ;;

  --user | -!(-*)u)
    _allowed_users
    return
    ;;
  esac

  $split && return
  if [[ $cur == -* ]]; then
    COMPREPLY=($(compgen -W '$(_parse_help "$1")' -- "$cur"))
    [[ $cword -eq 1 ]] && _signals -
    return
  fi
  _pnames
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _killall killall &&
  complete -F _killall killproc
