#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  020520211122-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  newsboat --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created           :  Friday, Feb 05, 2021 11:22 EST
# @File              :  newsboat
# @Description       :  autocomplete for newsboat
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_newsboat() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local ARRAY="-e --export-to-opml -r --refresh-on-start -i --import-from-opml -u --url-file "
  local ARRAY+="-c --cache-file -C --config-file -X  --vacuum -x --execute -q --quiet  -v --version "
  local ARRAY+="-l --log-level -d --log-file -E --export-to-file -I --import-from-file -h --help "

  _init_completion || return

  case $prev in
  -f)
    COMPREPLY=($(compgen -W \
      '$(newsboat -l 2>/dev/null | tail -n +2)' -- "$cur"))
    return
    ;;
  *)
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _newsboat -o default newsboat
