#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  020520211122-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.com
# @License           :  WTFPL
# @ReadME            :  pasteit --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created           :  Friday, Feb 05, 2021 11:22 EST
# @File              :  pasteit
# @Description       :  autocomplete for pasteit
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_pasteit() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local ARRAY="--help --title --name --private --language --expire --reply -b --apikey"

  _init_completion || return

  COMPREPLY=($(compgen -W '${ARRAY}' -- "$prev"))

  case $cur in
  -n)
    COMPREPLY=($(compgen -W '${USER}' -- "$cur"))
    return
    ;;

  -*)
    COMPREPLY=($(compgen -W '${ARRAY}' -- "$cur"))
    return
    ;;
  *)
    _filedir
    return
    ;;
  esac
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _pasteit -o default pasteit
