#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  020520211122-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.com
# @License           :  WTFPL
# @ReadME            :  pb --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created           :  Friday, Feb 05, 2021 11:22 EST
# @File              :  pb
# @Description       :  autocomplete for pb
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_pb() {
  local -a commands
  commands=(
    '0x0.st'
    'catbox.moe'
    'clbin.com'
    'dmca.gripe'
    'dumpz.org'
    'fiery.me'
    'ix.io'
    'p.iotek.org'
    'pastebin.com'
    'sprunge.us'
    'uguu.se'
    'w1r3.net'
  )
  if ((CURRENT == 2)); then
    _describe -t commands 'commands' commands
  else
    _files
  fi
  return 0
} &&
  complete -F _pb pb
