#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202409241900-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  screenshot-menu --help
# @Copyright         :  Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created           :  Thursday, Aug 12, 2021 19:03 EDT
# @File              :  screenshot-menu
# @Description       :  Choose type of screenshot
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - -'
_screenshot-menu() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/screenshot-menu"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/screenshot-menu}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--help --config --debug --version --raw --silent --options --completions --delay --cursor --no-cursor --quality --format --tool --clipboard --file --both --upload --no-sound --open"
  local SHORTOPTS=""
  local ARRAY="full window region monitor quick annotate record"
  local TOOLS="auto maim scrot flameshot spectacle gnome-screenshot import grim"
  local FORMATS="png jpg jpeg webp"
  local QUALITIES="100 90 80 70 60 50"
  local DELAYS="0 1 2 3 5 10"

  _init_completion || return

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${prev}" in
    --delay)
      COMPREPLY=($(compgen -W '${DELAYS}' -- "${cur}"))
      ;;
    --quality)
      COMPREPLY=($(compgen -W '${QUALITIES}' -- "${cur}"))
      ;;
    --format)
      COMPREPLY=($(compgen -W '${FORMATS}' -- "${cur}"))
      ;;
    --tool)
      COMPREPLY=($(compgen -W '${TOOLS}' -- "${cur}"))
      ;;
    --completions)
      COMPREPLY=($(compgen -W 'short long array list' -- "${cur}"))
      ;;
    --dir)
      _filedir
      return
      ;;
    --config|--help|--version|--options|--debug|--raw|--silent|--cursor|--no-cursor|--clipboard|--file|--both|--upload|--no-sound|--open)
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;
    *)
      # Complete with available commands
      COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      ;;
    esac
  fi
  #
  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _screenshot-menu screenshot-menu
