#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202207120126-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  todo --help
# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created           :  Tuesday, Jul 12, 2022 01:26 EDT
# @File              :  todo
# @Description       :  Setup a console base todo
# @TODO              :  Clean up code
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
_todo() {
  ___findcmd() { find -L ${1:-$CONFDIR/*} -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.local/share/editors/todos"
  local SEARCHDIR="${CONFDIR:-$HOME/.local/share/editors/todos}"
  local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | grep -v '.git/*' | sort -u)"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS="$(echo {0..9} {a..z})"
  local LONGOPTS="--debug --options --config --version --help --dir "
  local SHORTOPTS="-p"
  local ARRAY="archive completed import list search edit update"

  _init_completion || return

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options)
      local prev="--options"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --config)
      local prev="--config"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --help)
      prev="--help"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --version)
      local prev="--version"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --dir)
      local prev="dir"
      _filedir
      return
      ;;
    list)
      local prev="list"
      [[ ${cword} -gt 3 ]] && COMPREPLY=($(compgen -W '' -- "${cur}"))
      COMPREPLY=($(compgen -W 'archive completed all' '' -- "${cur}"))
      ;;
    search)
      local prev="$cword"
      COMPREPLY=($(compgen -W '${OPTS}' '' -- "${cur}"))
      compopt -o nospace
      ;;

    archive | completed | import | edit)
      local prev="$cword"
      [[ $cword -eq 3 ]] && COMPREPLY=($(compgen -W '${SEARCHCMD}' -- "${cur}"))
      [[ $cword -gt 3 ]] && COMPREPLY=($(compgen -W '' -- "${cur}"))
      COMPREPLY=($(compgen -W '-p' -- "${cur}"))
      ;;

    *)
      [[ ${cword} -le 2 ]] &&
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}")) ||
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;
    esac
  fi
  #
  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _todo todo
