#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202201121106-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.pro
# @License           :  WTFPL
# @ReadME            :  virt-display --help
# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created           :  Wednesday, Jan 12, 2022 11:06 EST
# @File              :  virt-display
# @Description       :
# @TODO              :
# @Other             :
# @Resource          :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -'
_virt-display() {
  ___findcmd() { find -L "${1:-$CONFDIR/}" -maxdepth ${3:-3} -type ${2:-f} 2>/dev/null | sed 's#'${1:-$CONFDIR}'##g' | grep '^' || return 1; }
  ___vm_list() { sudo virsh list --all | grep -E 'running|shut off' | awk '{print $2}' | grep '^' || return 1; }
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword opts split
  local cur="${COMP_WORDS[$COMP_CWORD]}"
  local prev="${COMP_WORDS[$COMP_CWORD - 1]}"
  local CONFFILE="settings.conf"
  local CONFDIR="$HOME/.config/myscripts/virt-display"
  local SEARCHDIR="${CONFDIR:-$HOME/.config/myscripts/virt-display}"
  #local SEARCHCMD="$(___findcmd "$SEARCHDIR/" "d" "1" | sort -u)"
  local SHOW_COMP_OPTS=""
  local FILEDIR=""
  local OPTS=""
  local LONGOPTS="--options --config --version --help --dir"
  local SHORTOPTS=""
  local ARRAY="list start ssh restore create ip new delete open "

  _init_completion || return

  if [[ "$SHOW_COMP_OPTS" != "" ]]; then
    local SHOW_COMP_OPTS_SEP="${SHOW_COMP_OPTS//,/ }"
    compopt -o $SHOW_COMP_OPTS_SEP
  fi

  if [[ ${cur} == --* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
    return
  elif [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${SHORTOPTS}' -- ${cur}))
    return
  else
    case "${COMP_WORDS[1]:-$prev}" in
    --options)
      local prev="--options"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --config)
      local prev="--config"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --help)
      prev="--help"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --version)
      local prev="--version"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    --dir)
      local prev="dir"
      _filedir
      return
      ;;

    list)
      prev="list"
      COMPREPLY=($(compgen -W '' -- "${cur}"))
      ;;

    ssh)
      prev="ssh"
      if [[ ${cword} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ ${cword} -eq 3 ]]; then
        prev="${COMP_WORDS[2]}"
        COMPREPLY=($(compgen -W '${USER} ${prev} root' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '$(___vm_list)' -- "${cur}"))
      fi
      ;;

    start | restore | create | ip | delete)
      prev="create"
      #echo $cword
      if [[ ${cword} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ ${cword} -eq 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '$(___vm_list)' -- "${cur}"))
      fi
      ;;

    new)
      prev="new"
      #echo $cword
      if [[ ${cword} -gt 3 ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ ${cword} -ge 3 ]]; then
        compopt -o nospace
        _filedir
      else
        compopt -o nospace
        COMPREPLY=($(compgen -W '{a..z}' -- "${cur}"))
      fi
      ;;

    *)
      if [[ -n "$FILEDIR" ]]; then _filedir; fi
      # if [[ $cword -gt 2 ]]; then
      #   return
      # elif [[ $cword == 2 ]]; then
      #   _filedir
      #   compopt -o nospace
      #   return
      # elif [[ $cword -eq 1 ]]; then
      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
      #   compopt -o nospace
      #   return
      if [[ "$ARRAY" = "show__none" ]]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [[ "$ARRAY" = "show__filedir" ]]; then
        _filedir
      elif [[ "$ARRAY" = "show__commands" ]]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      else
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      # elif [[ $cword -gt 2 ]]; then
      #   return
      # elif [[ $cword == 2 ]]; then
      #   _filedir
      #   compopt -o nospace
      #   return
      # elif [[ $cword -eq 1 ]]; then
      #   COMPREPLY=($(compgen -W '{a..z}{a..z}' -- "${cur}"))
      #   compopt -o nospace
      #   return
      fi
      ;;
    esac
  fi
  #
  # [[ ${cword} == 2 ]] && _filedir && compopt -o nospace
  # [[ $COMP_CWORD -eq 2 ] && COMPREPLY=($(compgen -W '{a..z} {A..Z} {0..9}' -o nospace -- "${cur}"))
  # [[ $COMP_CWORD -eq 3 ] && COMPREPLY=($(compgen -W '$(_filedir)' -o filenames -o dirnames -- "${cur}"))
  # [[ $COMP_CWORD -gt 3 ] && COMPREPLY=($(compgen -W '' -- "${cur}"))
  #prev=""
  #compopt -o nospace
  $split && return
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _virt-display virt-display
