#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202304031205-git
# @@Author           :  Jason Hempstead
# @@Contact          :  git-admin@casjaysdev.pro
# @@License          :  LICENSE.md
# @@ReadME           :  make-completion-wrapper --help
# @@Copyright        :  Copyright: (c) 2023 Jason Hempstead, Casjays Developments
# @@Created          :  Monday, Apr 03, 2023 16:25 EDT
# @@File             :  make-completion-wrapper
# @@Description      :  Wraps a completion function, eg for use with an alias.
# @@Changelog        :  newScript
# @@TODO             :  Refactor code
# @@Other            :
# @@Resource         :  https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases
# @@Terminal App     :  no
# @@sudo/root        :  no
# @@Template         :  bash/system
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
function make-completion-wrapper {
  if [ $# -ge 3 ]; then
    local function_name="$2"
    local arg_count=$(($# - 3))
    local comp_function_name="$1"
    shift 2
    local function="function $function_name {
      (( COMP_CWORD += $arg_count ))
      COMP_WORDS=( \"\$@\" \${COMP_WORDS[@]:1} )
      \"$comp_function_name\"
    }"
    eval "$function"
    # echo "$function"
  else
    printf '%s\n' 'Usage: make-completion-wrapper <actual completion function> <name of new func.> <command name> <arguments>'
    printf '%s\n' 'IE: alias agi='apt-get install''
    return 1
  fi
}
export -f make-completion-wrapper
